-- Catalog-only snapshot. Does not read application rows, auth identities, secrets or job payloads.
begin read only;
set local statement_timeout = '30s';
select jsonb_build_object(
 'database_version', current_setting('server_version'),
 'schemas', (select jsonb_agg(jsonb_build_object('name',nspname,'owner',pg_get_userbyid(nspowner),'acl',nspacl::text) order by nspname) from pg_namespace where nspname not like 'pg_%' and nspname <> 'information_schema'),
 'extensions', (select jsonb_agg(jsonb_build_object('name',e.extname,'version',e.extversion,'schema',n.nspname) order by e.extname) from pg_extension e join pg_namespace n on n.oid=e.extnamespace),
 'roles', (select jsonb_agg(jsonb_build_object('name',rolname,'superuser',rolsuper,'inherit',rolinherit,'create_role',rolcreaterole,'create_db',rolcreatedb,'login',rolcanlogin,'bypass_rls',rolbypassrls) order by rolname) from pg_roles where rolname not like 'pg_%' and rolname not like 'cli_%'),
 'relations', (select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',c.relname,'kind',c.relkind,'owner',pg_get_userbyid(c.relowner),'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity,'acl',c.relacl::text,'options',c.reloptions,'replica_identity',c.relreplident,'persistence',c.relpersistence,'partition',case when c.relkind='p' then pg_get_partkeydef(c.oid) else null end,'view',case when c.relkind in ('v','m') then pg_get_viewdef(c.oid,true) else null end) order by n.nspname,c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','api','orcaly_private','ecosystem_private','auth','storage') and c.relkind in ('r','p','v','m','S','f')),
 'columns', (select jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',a.attname,'position',a.attnum,'type',format_type(a.atttypid,a.atttypmod),'not_null',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid),'identity',a.attidentity,'generated',a.attgenerated,'acl',a.attacl::text,'collation',case when a.attcollation<>0 then a.attcollation::regcollation::text else null end) order by n.nspname,c.relname,a.attnum) from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where n.nspname in ('public','api','orcaly_private','ecosystem_private','auth','storage') and c.relkind in ('r','p','v','m') and a.attnum>0 and not a.attisdropped),
 'constraints', (select jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',co.conname,'type',co.contype,'definition',pg_get_constraintdef(co.oid,true),'validated',co.convalidated,'deferrable',co.condeferrable,'initially_deferred',co.condeferred) order by n.nspname,c.relname,co.conname) from pg_constraint co join pg_class c on c.oid=co.conrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','api','orcaly_private','ecosystem_private','auth','storage')),
 'indexes', (select jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',ic.relname,'definition',pg_get_indexdef(i.indexrelid),'valid',i.indisvalid,'replica_identity',i.indisreplident,'constraint',co.conname) order by n.nspname,ic.relname) from pg_index i join pg_class c on c.oid=i.indrelid join pg_class ic on ic.oid=i.indexrelid join pg_namespace n on n.oid=c.relnamespace left join pg_constraint co on co.conindid=i.indexrelid and co.contype in ('p','u','x') where n.nspname in ('public','api','orcaly_private','ecosystem_private','auth','storage')),
 'functions', (select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',p.proname,'args',pg_get_function_identity_arguments(p.oid),'definition',pg_get_functiondef(p.oid),'owner',pg_get_userbyid(p.proowner),'security_definer',p.prosecdef,'config',p.proconfig,'acl',p.proacl::text,'language',l.lanname) order by n.nspname,p.proname,pg_get_function_identity_arguments(p.oid)) from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname in ('public','api','orcaly_private','ecosystem_private','auth','storage') and p.prokind in ('f','p') and not exists(select 1 from pg_depend dep where dep.classid='pg_proc'::regclass and dep.objid=p.oid and dep.deptype='e')),
 'policies', (select jsonb_agg(to_jsonb(p) order by schemaname,tablename,policyname) from pg_policies p where schemaname in ('public','api','orcaly_private','ecosystem_private','auth','storage')),
 'triggers', (select jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',t.tgname,'enabled',t.tgenabled,'definition',pg_get_triggerdef(t.oid,true),'function_schema',fn.nspname,'function',p.proname) order by n.nspname,c.relname,t.tgname) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace join pg_proc p on p.oid=t.tgfoid join pg_namespace fn on fn.oid=p.pronamespace where not t.tgisinternal and n.nspname in ('public','api','orcaly_private','ecosystem_private','auth','storage')),
 'types', (select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',t.typname,'kind',t.typtype,'base',format_type(t.typbasetype,t.typtypmod),'owner',pg_get_userbyid(t.typowner),'acl',t.typacl::text,'enum_labels',(select jsonb_agg(e.enumlabel order by e.enumsortorder) from pg_enum e where e.enumtypid=t.oid)) order by n.nspname,t.typname) from pg_type t join pg_namespace n on n.oid=t.typnamespace where n.nspname in ('public','api','orcaly_private','ecosystem_private') and t.typtype in ('e','d')),
 'sequences', (select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',c.relname,'type',format_type(s.seqtypid,null),'start',s.seqstart::text,'increment',s.seqincrement::text,'min',s.seqmin::text,'max',s.seqmax::text,'cache',s.seqcache::text,'cycle',s.seqcycle,'owned_by',(select format('%I.%I.%I',onsp.nspname,oc.relname,a.attname) from pg_depend dep join pg_class oc on oc.oid=dep.refobjid join pg_namespace onsp on onsp.oid=oc.relnamespace join pg_attribute a on a.attrelid=oc.oid and a.attnum=dep.refobjsubid where dep.classid='pg_class'::regclass and dep.objid=c.oid and dep.deptype in ('a','i') limit 1)) order by n.nspname,c.relname) from pg_sequence s join pg_class c on c.oid=s.seqrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','api','orcaly_private','ecosystem_private')),
 'default_acl', (select jsonb_agg(jsonb_build_object('role',pg_get_userbyid(d.defaclrole),'schema',coalesce(n.nspname,''),'type',d.defaclobjtype,'acl',d.defaclacl::text) order by pg_get_userbyid(d.defaclrole),n.nspname,d.defaclobjtype) from pg_default_acl d left join pg_namespace n on n.oid=d.defaclnamespace),
 'publications', (select jsonb_agg(jsonb_build_object('name',p.pubname,'all_tables',p.puballtables,'insert',p.pubinsert,'update',p.pubupdate,'delete',p.pubdelete,'truncate',p.pubtruncate,'tables',(select jsonb_agg(jsonb_build_object('schema',pt.schemaname,'table',pt.tablename) order by pt.schemaname,pt.tablename) from pg_publication_tables pt where pt.pubname=p.pubname)) order by p.pubname) from pg_publication p),
 'event_triggers', (select jsonb_agg(jsonb_build_object('name',evtname,'event',evtevent,'enabled',evtenabled,'tags',evttags,'function',evtfoid::regprocedure::text,'owner',pg_get_userbyid(evtowner)) order by evtname) from pg_event_trigger)
) as snapshot;
commit;
