param(
    [string]$ProjectRoot = "",
    [switch]$SkipInitialBuild,
    [switch]$SkipFinalBuild
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

try {
    [Console]::OutputEncoding = New-Object System.Text.UTF8Encoding($false)
    $OutputEncoding = New-Object System.Text.UTF8Encoding($false)
} catch {}

$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$ExpectedSha = "3821A0371A77C824929B735239A7AD2A2C599B2682B8E47ED3EFD7DD3FD44BC4"
$DesiredSha = "E4C9D5DAB8B2933C7BBD2216E1CAD110D2A291F55400D57FB7B86A9D66D3BD43"
$MarkerOld = "ORCALY_ORDER_WHATSAPP_MESSAGE_V1"
$MarkerNew = "ORCALY_ORDER_WHATSAPP_UNICODE_V2"

if ([string]::IsNullOrWhiteSpace($ProjectRoot)) {
    $ProjectRoot = (Get-Location).Path
} else {
    $ProjectRoot = (Resolve-Path -LiteralPath $ProjectRoot).Path
}

$Target = Join-Path $ProjectRoot "lib\order-whatsapp.ts"
$Timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$BackupRoot = Join-Path $ProjectRoot (".orcaly-backups\whatsapp-unicode-" + $Timestamp)
$BackupFile = Join-Path $BackupRoot "lib\order-whatsapp.ts"

function Step([string]$Text) {
    Write-Host ""
    Write-Host ("==> " + $Text) -ForegroundColor Cyan
}

function Ok([string]$Text) {
    Write-Host ("[OK] " + $Text) -ForegroundColor Green
}

function Warn([string]$Text) {
    Write-Host ("[AVISO] " + $Text) -ForegroundColor Yellow
}

function Sha([string]$Path) {
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        return ""
    }

    return (
        Get-FileHash -LiteralPath $Path -Algorithm SHA256
    ).Hash.ToUpperInvariant()
}

function Restore {
    if (Test-Path -LiteralPath $BackupFile -PathType Leaf) {
        Copy-Item -LiteralPath $BackupFile -Destination $Target -Force
        Warn "Rollback concluido: lib/order-whatsapp.ts restaurado."
    }
}

try {
    Write-Host ""
    Write-Host "ORCALY - WHATSAPP UNICODE V2" -ForegroundColor Cyan
    Write-Host "Emojis seguros para Windows, Git, URL e WhatsApp." -ForegroundColor DarkCyan

    if (-not (Test-Path -LiteralPath (Join-Path $ProjectRoot "package.json") -PathType Leaf)) {
        throw "Execute este script na raiz do projeto Orcaly."
    }

    Set-Location $ProjectRoot

    if (-not (Test-Path -LiteralPath $Target -PathType Leaf)) {
        throw "lib/order-whatsapp.ts nao existe. A melhoria anterior precisa estar aplicada."
    }

    $currentText = [IO.File]::ReadAllText($Target)

    if (-not $currentText.Contains($MarkerOld)) {
        throw "O gerador WhatsApp atual nao possui o marcador esperado."
    }

    if ($currentText.Contains($MarkerNew)) {
        Ok "A correcao Unicode ja esta aplicada."
        exit 0
    }

    $currentSha = Sha $Target

    if ($currentSha -ne $ExpectedSha) {
        throw (
            "lib/order-whatsapp.ts mudou desde a versao auditada. " +
            "O script recusou sobrescrever. SHA atual: " +
            $currentSha
        )
    }

    Ok "Gerador WhatsApp corresponde exatamente a versao V3 auditada."

    if (-not $SkipInitialBuild) {
        Step "Build inicial"
        & npm.cmd run build

        if ($LASTEXITCODE -ne 0) {
            throw "O projeto ja falha no build antes desta correcao. Nada foi alterado."
        }

        Ok "Build inicial passou."
    }

    Step "Criando backup"

    [IO.Directory]::CreateDirectory((Split-Path -Parent $BackupFile)) | Out-Null
    Copy-Item -LiteralPath $Target -Destination $BackupFile -Force
    Ok ("Backup: " + $BackupFile)

    Step "Aplicando Unicode seguro"

    $bytes = [Convert]::FromBase64String("Ly8gT1JDQUxZX09SREVSX1dIQVRTQVBQX01FU1NBR0VfVjEKLy8gT1JDQUxZX09SREVSX1dIQVRTQVBQX1VOSUNPREVfVjIKCnR5cGUgVW5rbm93blJlY29yZCA9IFJlY29yZDxzdHJpbmcsIHVua25vd24+CgpmdW5jdGlvbiBhc1JlY29yZCh2YWx1ZTogdW5rbm93bik6IFVua25vd25SZWNvcmQgfCBudWxsIHsKICByZXR1cm4gdmFsdWUgJiYgdHlwZW9mIHZhbHVlID09PSAnb2JqZWN0JyAmJiAhQXJyYXkuaXNBcnJheSh2YWx1ZSkKICAgID8gKHZhbHVlIGFzIFVua25vd25SZWNvcmQpCiAgICA6IG51bGwKfQoKZnVuY3Rpb24gYXNBcnJheSh2YWx1ZTogdW5rbm93bik6IHVua25vd25bXSB7CiAgcmV0dXJuIEFycmF5LmlzQXJyYXkodmFsdWUpID8gdmFsdWUgOiBbXQp9CgpmdW5jdGlvbiBmaXJzdFRleHQoCiAgcmVjb3JkOiBVbmtub3duUmVjb3JkLAogIGtleXM6IHN0cmluZ1tdLAopOiBzdHJpbmcgewogIGZvciAoY29uc3Qga2V5IG9mIGtleXMpIHsKICAgIGNvbnN0IHZhbHVlID0gcmVjb3JkW2tleV0KCiAgICBpZiAoCiAgICAgIHR5cGVvZiB2YWx1ZSA9PT0gJ3N0cmluZycgJiYKICAgICAgdmFsdWUudHJpbSgpCiAgICApIHsKICAgICAgcmV0dXJuIHZhbHVlLnRyaW0oKQogICAgfQoKICAgIGlmICgKICAgICAgdHlwZW9mIHZhbHVlID09PSAnbnVtYmVyJyAmJgogICAgICBOdW1iZXIuaXNGaW5pdGUodmFsdWUpCiAgICApIHsKICAgICAgcmV0dXJuIFN0cmluZyh2YWx1ZSkKICAgIH0KICB9CgogIHJldHVybiAnJwp9CgpmdW5jdGlvbiBmaXJzdE51bWJlcigKICByZWNvcmQ6IFVua25vd25SZWNvcmQsCiAga2V5czogc3RyaW5nW10sCik6IG51bWJlciB7CiAgZm9yIChjb25zdCBrZXkgb2Yga2V5cykgewogICAgY29uc3QgcGFyc2VkID0gTnVtYmVyKHJlY29yZFtrZXldKQoKICAgIGlmIChOdW1iZXIuaXNGaW5pdGUocGFyc2VkKSAmJiBwYXJzZWQgIT09IDApIHsKICAgICAgcmV0dXJuIHBhcnNlZAogICAgfQogIH0KCiAgcmV0dXJuIDAKfQoKZnVuY3Rpb24gbW9uZXkodmFsdWU6IHVua25vd24pIHsKICBjb25zdCBwYXJzZWQgPSBOdW1iZXIodmFsdWUgfHwgMCkKCiAgcmV0dXJuIHBhcnNlZC50b0xvY2FsZVN0cmluZygncHQtQlInLCB7CiAgICBzdHlsZTogJ2N1cnJlbmN5JywKICAgIGN1cnJlbmN5OiAnQlJMJywKICB9KQp9CgpmdW5jdGlvbiBub3JtYWxpemVTdGF0dXModmFsdWU6IHVua25vd24pIHsKICByZXR1cm4gU3RyaW5nKHZhbHVlIHx8ICcnKQogICAgLnRyaW0oKQogICAgLnRvTG93ZXJDYXNlKCkKfQoKZnVuY3Rpb24gcGF5bWVudFN0YXR1c0xhYmVsKHZhbHVlOiB1bmtub3duKSB7CiAgY29uc3Qgc3RhdHVzID0gbm9ybWFsaXplU3RhdHVzKHZhbHVlKQoKICBjb25zdCBsYWJlbHM6IFJlY29yZDxzdHJpbmcsIHN0cmluZz4gPSB7CiAgICBwYWlkOiAnUGFnbycsCiAgICBhcHByb3ZlZDogJ1BhZ28nLAogICAgYXV0aG9yaXplZDogJ0F1dG9yaXphZG8nLAogICAgcGVuZGluZzogJ1BlbmRlbnRlJywKICAgIGluX3Byb2Nlc3M6ICdFbSBwcm9jZXNzYW1lbnRvJywKICAgIGZhaWxlZDogJ0ZhbGhvdScsCiAgICByZWplY3RlZDogJ1JlY3VzYWRvJywKICAgIHJlZnVuZGVkOiAnRXN0b3JuYWRvJywKICAgIGNhbmNlbGxlZDogJ0NhbmNlbGFkbycsCiAgICBjYW5jZWxlZDogJ0NhbmNlbGFkbycsCiAgfQoKICByZXR1cm4gbGFiZWxzW3N0YXR1c10gfHwgU3RyaW5nKHZhbHVlIHx8ICcnKS50cmltKCkKfQoKZnVuY3Rpb24gZGVsaXZlcnlUeXBlTGFiZWwodmFsdWU6IHVua25vd24pIHsKICBjb25zdCBzdGF0dXMgPSBub3JtYWxpemVTdGF0dXModmFsdWUpCgogIGNvbnN0IGxhYmVsczogUmVjb3JkPHN0cmluZywgc3RyaW5nPiA9IHsKICAgIGRlbGl2ZXJ5OiAnRW50cmVnYScsCiAgICBlbnRyZWdhOiAnRW50cmVnYScsCiAgICBwaWNrdXA6ICdSZXRpcmFkYScsCiAgICByZXRpcmFkYTogJ1JldGlyYWRhJywKICAgIHRha2VvdXQ6ICdSZXRpcmFkYScsCiAgfQoKICByZXR1cm4gbGFiZWxzW3N0YXR1c10gfHwgU3RyaW5nKHZhbHVlIHx8ICcnKS50cmltKCkKfQoKZnVuY3Rpb24gZm9ybWF0RGF0ZVRpbWVQYXJ0cyh2YWx1ZTogdW5rbm93bikgewogIGlmICghdmFsdWUpIHsKICAgIHJldHVybiB7CiAgICAgIGRhdGU6ICcnLAogICAgICB0aW1lOiAnJywKICAgIH0KICB9CgogIGNvbnN0IHBhcnNlZCA9IG5ldyBEYXRlKFN0cmluZyh2YWx1ZSkpCgogIGlmIChOdW1iZXIuaXNOYU4ocGFyc2VkLmdldFRpbWUoKSkpIHsKICAgIHJldHVybiB7CiAgICAgIGRhdGU6ICcnLAogICAgICB0aW1lOiAnJywKICAgIH0KICB9CgogIHJldHVybiB7CiAgICBkYXRlOiBuZXcgSW50bC5EYXRlVGltZUZvcm1hdCgncHQtQlInLCB7CiAgICAgIGRheTogJzItZGlnaXQnLAogICAgICBtb250aDogJzItZGlnaXQnLAogICAgICB5ZWFyOiAnbnVtZXJpYycsCiAgICB9KS5mb3JtYXQocGFyc2VkKSwKICAgIHRpbWU6IG5ldyBJbnRsLkRhdGVUaW1lRm9ybWF0KCdwdC1CUicsIHsKICAgICAgaG91cjogJzItZGlnaXQnLAogICAgICBtaW51dGU6ICcyLWRpZ2l0JywKICAgIH0pLmZvcm1hdChwYXJzZWQpLAogIH0KfQoKZnVuY3Rpb24gZm9ybWF0RGF0ZVRpbWUodmFsdWU6IHVua25vd24pIHsKICBpZiAoIXZhbHVlKSByZXR1cm4gJycKCiAgY29uc3QgcGFyc2VkID0gbmV3IERhdGUoU3RyaW5nKHZhbHVlKSkKICBpZiAoTnVtYmVyLmlzTmFOKHBhcnNlZC5nZXRUaW1lKCkpKSByZXR1cm4gJycKCiAgcmV0dXJuIG5ldyBJbnRsLkRhdGVUaW1lRm9ybWF0KCdwdC1CUicsIHsKICAgIGRhdGVTdHlsZTogJ3Nob3J0JywKICAgIHRpbWVTdHlsZTogJ3Nob3J0JywKICB9KS5mb3JtYXQocGFyc2VkKQp9CgpmdW5jdGlvbiBvcHRpb25MYWJlbCh2YWx1ZTogdW5rbm93bikgewogIGlmICh0eXBlb2YgdmFsdWUgPT09ICdzdHJpbmcnKSB7CiAgICByZXR1cm4gdmFsdWUudHJpbSgpCiAgfQoKICBpZiAoCiAgICB0eXBlb2YgdmFsdWUgPT09ICdudW1iZXInICYmCiAgICBOdW1iZXIuaXNGaW5pdGUodmFsdWUpCiAgKSB7CiAgICByZXR1cm4gU3RyaW5nKHZhbHVlKQogIH0KCiAgY29uc3QgcmVjb3JkID0gYXNSZWNvcmQodmFsdWUpCgogIGlmICghcmVjb3JkKSByZXR1cm4gJycKCiAgY29uc3QgbGFiZWwgPSBmaXJzdFRleHQocmVjb3JkLCBbCiAgICAnbmFtZScsCiAgICAnbGFiZWwnLAogICAgJ3RpdGxlJywKICAgICd2YWx1ZScsCiAgICAnb3B0aW9uX25hbWUnLAogICAgJ3ZhcmlhdGlvbl9uYW1lJywKICBdKQoKICBjb25zdCBkZXRhaWwgPSBmaXJzdFRleHQocmVjb3JkLCBbCiAgICAnb3B0aW9uJywKICAgICdjaG9pY2UnLAogICAgJ2Rlc2NyaXB0aW9uJywKICBdKQoKICBpZiAobGFiZWwgJiYgZGV0YWlsICYmIGRldGFpbCAhPT0gbGFiZWwpIHsKICAgIHJldHVybiBgJHtsYWJlbH06ICR7ZGV0YWlsfWAKICB9CgogIHJldHVybiBsYWJlbCB8fCBkZXRhaWwKfQoKZnVuY3Rpb24gYWRkb25MYWJlbCh2YWx1ZTogdW5rbm93bikgewogIGlmICh0eXBlb2YgdmFsdWUgPT09ICdzdHJpbmcnKSB7CiAgICByZXR1cm4gdmFsdWUudHJpbSgpCiAgfQoKICBjb25zdCByZWNvcmQgPSBhc1JlY29yZCh2YWx1ZSkKCiAgaWYgKCFyZWNvcmQpIHJldHVybiAnJwoKICBjb25zdCBuYW1lID0gZmlyc3RUZXh0KHJlY29yZCwgWwogICAgJ25hbWUnLAogICAgJ2xhYmVsJywKICAgICd0aXRsZScsCiAgICAncHJvZHVjdF9uYW1lJywKICBdKQoKICBpZiAoIW5hbWUpIHJldHVybiAnJwoKICBjb25zdCBxdWFudGl0eSA9IGZpcnN0TnVtYmVyKHJlY29yZCwgWwogICAgJ3F1YW50aXR5JywKICAgICdxdHknLAogIF0pCgogIGNvbnN0IHByaWNlID0gZmlyc3ROdW1iZXIocmVjb3JkLCBbCiAgICAncHJpY2UnLAogICAgJ3VuaXRfcHJpY2UnLAogICAgJ2Ftb3VudCcsCiAgXSkKCiAgY29uc3QgcGllY2VzID0gWwogICAgcXVhbnRpdHkgPiAxID8gYCR7cXVhbnRpdHl9eCAke25hbWV9YCA6IG5hbWUsCiAgXQoKICBpZiAocHJpY2UgPiAwKSB7CiAgICBwaWVjZXMucHVzaChtb25leShwcmljZSkpCiAgfQoKICByZXR1cm4gcGllY2VzLmpvaW4oJyDigJQgJykKfQoKZXhwb3J0IGZ1bmN0aW9uIGdldE9yZGVyRGlzcGxheU51bWJlcigKICBvcmRlclZhbHVlOiB1bmtub3duLAopIHsKICBjb25zdCBvcmRlciA9IGFzUmVjb3JkKG9yZGVyVmFsdWUpIHx8IHt9CgogIGNvbnN0IGV4cGxpY2l0ID0gZmlyc3RUZXh0KG9yZGVyLCBbCiAgICAnb3JkZXJfbnVtYmVyJywKICAgICdudW1lcm9fcGVkaWRvJywKICAgICdudW1iZXInLAogICAgJ2NvZGUnLAogICAgJ3B1YmxpY19pZCcsCiAgXSkKCiAgaWYgKGV4cGxpY2l0KSB7CiAgICByZXR1cm4gZXhwbGljaXQKICAgICAgLnJlcGxhY2UoL14jKy8sICcnKQogICAgICAudHJpbSgpCiAgICAgIC50b1VwcGVyQ2FzZSgpCiAgfQoKICBjb25zdCBpZCA9IGZpcnN0VGV4dChvcmRlciwgWydpZCddKQogICAgLnJlcGxhY2UoL1teYS16QS1aMC05XS9nLCAnJykKICAgIC50b1VwcGVyQ2FzZSgpCgogIGlmICghaWQpIHJldHVybiAnU0VNLVJFRicKCiAgcmV0dXJuIGlkLnNsaWNlKDAsIDgpCn0KCmV4cG9ydCBmdW5jdGlvbiBnZXRPcmRlcldoYXRzQXBwUGhvbmUoCiAgb3JkZXJWYWx1ZTogdW5rbm93biwKKSB7CiAgY29uc3Qgb3JkZXIgPSBhc1JlY29yZChvcmRlclZhbHVlKSB8fCB7fQoKICByZXR1cm4gZmlyc3RUZXh0KG9yZGVyLCBbCiAgICAnY3VzdG9tZXJfcGhvbmUnLAogICAgJ3RlbGVmb25lJywKICAgICdwaG9uZScsCiAgXSkKfQoKZXhwb3J0IGZ1bmN0aW9uIGhhc09yZGVyV2hhdHNBcHBQaG9uZSgKICBvcmRlclZhbHVlOiB1bmtub3duLAopIHsKICByZXR1cm4gQm9vbGVhbigKICAgIGdldE9yZGVyV2hhdHNBcHBQaG9uZShvcmRlclZhbHVlKQogICAgICAucmVwbGFjZSgvXEQvZywgJycpLAogICkKfQoKZnVuY3Rpb24gbm9ybWFsaXplZFdoYXRzQXBwUGhvbmUoCiAgb3JkZXJWYWx1ZTogdW5rbm93biwKKSB7CiAgY29uc3QgY2xlYW4gPSBnZXRPcmRlcldoYXRzQXBwUGhvbmUob3JkZXJWYWx1ZSkKICAgIC5yZXBsYWNlKC9cRC9nLCAnJykKCiAgaWYgKCFjbGVhbikgcmV0dXJuICcnCgogIHJldHVybiBjbGVhbi5zdGFydHNXaXRoKCc1NScpCiAgICA/IGNsZWFuCiAgICA6IGA1NSR7Y2xlYW59YAp9CgpmdW5jdGlvbiBidWlsZEl0ZW1zU2VjdGlvbihvcmRlcjogVW5rbm93blJlY29yZCkgewogIGNvbnN0IHNuYXBzaG90ID0gYXNBcnJheShvcmRlci5pdGVtc19zbmFwc2hvdCkKICBjb25zdCBsaW5lczogc3RyaW5nW10gPSBbXQoKICBpZiAoc25hcHNob3QubGVuZ3RoID4gMCkgewogICAgc25hcHNob3QuZm9yRWFjaCgocmF3SXRlbSwgaW5kZXgpID0+IHsKICAgICAgY29uc3QgaXRlbSA9IGFzUmVjb3JkKHJhd0l0ZW0pCgogICAgICBpZiAoIWl0ZW0pIHJldHVybgoKICAgICAgY29uc3QgcHJvZHVjdE5hbWUgPQogICAgICAgIGZpcnN0VGV4dChpdGVtLCBbCiAgICAgICAgICAncHJvZHVjdF9uYW1lJywKICAgICAgICAgICduYW1lJywKICAgICAgICAgICd0aXRsZScsCiAgICAgICAgXSkgfHwgYEl0ZW0gJHtpbmRleCArIDF9YAoKICAgICAgY29uc3QgcXVhbnRpdHkgPQogICAgICAgIGZpcnN0TnVtYmVyKGl0ZW0sIFsKICAgICAgICAgICdxdWFudGl0eScsCiAgICAgICAgICAncXR5JywKICAgICAgICBdKSB8fCAxCgogICAgICBsaW5lcy5wdXNoKAogICAgICAgIGAke2luZGV4ICsgMX0uICoke3F1YW50aXR5fXggJHtwcm9kdWN0TmFtZX0qYCwKICAgICAgKQoKICAgICAgY29uc3QgdmFyaWF0aW9uID0gb3B0aW9uTGFiZWwoaXRlbS52YXJpYXRpb24pCgogICAgICBpZiAodmFyaWF0aW9uKSB7CiAgICAgICAgbGluZXMucHVzaChgICAg4oCiIFZhcmlhw6fDo286ICR7dmFyaWF0aW9ufWApCiAgICAgIH0KCiAgICAgIGNvbnN0IGFkZG9ucyA9IGFzQXJyYXkoaXRlbS5hZGRvbnMpCiAgICAgICAgLm1hcChhZGRvbkxhYmVsKQogICAgICAgIC5maWx0ZXIoQm9vbGVhbikKCiAgICAgIGlmIChhZGRvbnMubGVuZ3RoID4gMCkgewogICAgICAgIGxpbmVzLnB1c2goCiAgICAgICAgICBgICAg4oCiIEFkaWNpb25haXM6ICR7YWRkb25zLmpvaW4oJywgJyl9YCwKICAgICAgICApCiAgICAgIH0KCiAgICAgIGNvbnN0IG5vdGVzID0gZmlyc3RUZXh0KGl0ZW0sIFsKICAgICAgICAnbm90ZXMnLAogICAgICAgICdvYnNlcnZhdGlvbicsCiAgICAgICAgJ29ic2VydmFjYW8nLAogICAgICBdKQoKICAgICAgaWYgKG5vdGVzKSB7CiAgICAgICAgbGluZXMucHVzaChgICAg4oCiIE9ic2VydmHDp8OjbzogJHtub3Rlc31gKQogICAgICB9CgogICAgICBjb25zdCB1bml0UHJpY2UgPSBmaXJzdE51bWJlcihpdGVtLCBbCiAgICAgICAgJ3VuaXRfcHJpY2UnLAogICAgICAgICdiYXNlX3ByaWNlJywKICAgICAgXSkKCiAgICAgIGNvbnN0IHN1YnRvdGFsID0gZmlyc3ROdW1iZXIoaXRlbSwgWwogICAgICAgICdzdWJ0b3RhbCcsCiAgICAgICAgJ3RvdGFsJywKICAgICAgXSkKCiAgICAgIGlmICh1bml0UHJpY2UgPiAwKSB7CiAgICAgICAgbGluZXMucHVzaCgKICAgICAgICAgIGAgICDigKIgVmFsb3IgdW5pdMOhcmlvOiAke21vbmV5KHVuaXRQcmljZSl9YCwKICAgICAgICApCiAgICAgIH0KCiAgICAgIGlmIChzdWJ0b3RhbCA+IDApIHsKICAgICAgICBsaW5lcy5wdXNoKAogICAgICAgICAgYCAgIOKAoiBTdWJ0b3RhbDogJHttb25leShzdWJ0b3RhbCl9YCwKICAgICAgICApCiAgICAgIH0KICAgIH0pCiAgfQoKICBpZiAobGluZXMubGVuZ3RoID4gMCkgewogICAgcmV0dXJuIGxpbmVzCiAgfQoKICBjb25zdCBwcm9kdWN0ID0gZmlyc3RUZXh0KG9yZGVyLCBbCiAgICAncHJvZHV0bycsCiAgICAncHJvZHVjdF9uYW1lJywKICBdKQoKICBjb25zdCBzdW1tYXJ5ID0gZmlyc3RUZXh0KG9yZGVyLCBbCiAgICAnaXRlbnNfcmVzdW1vJywKICBdKQoKICBjb25zdCBxdWFudGl0eSA9CiAgICBmaXJzdE51bWJlcihvcmRlciwgWydxdWFudGlkYWRlJ10pIHx8IDEKCiAgaWYgKHByb2R1Y3QpIHsKICAgIGxpbmVzLnB1c2goYDEuICoke3F1YW50aXR5fXggJHtwcm9kdWN0fSpgKQoKICAgIGNvbnN0IHdpZHRoID0gZmlyc3ROdW1iZXIob3JkZXIsIFsnbGFyZ3VyYSddKQogICAgY29uc3QgaGVpZ2h0ID0gZmlyc3ROdW1iZXIob3JkZXIsIFsnYWx0dXJhJ10pCgogICAgaWYgKHdpZHRoID4gMCB8fCBoZWlnaHQgPiAwKSB7CiAgICAgIGxpbmVzLnB1c2goCiAgICAgICAgYCAgIOKAoiBNZWRpZGE6ICR7d2lkdGggfHwgJy0nfSB4ICR7aGVpZ2h0IHx8ICctJ31gLAogICAgICApCiAgICB9CiAgfSBlbHNlIGlmIChzdW1tYXJ5KSB7CiAgICBsaW5lcy5wdXNoKGAxLiAqJHtzdW1tYXJ5fSpgKQogIH0KCiAgcmV0dXJuIGxpbmVzCn0KCmZ1bmN0aW9uIHB1c2hTZWN0aW9uKAogIHRhcmdldDogc3RyaW5nW10sCiAgdGl0bGU6IHN0cmluZywKICByb3dzOiBzdHJpbmdbXSwKKSB7CiAgY29uc3QgY2xlYW5Sb3dzID0gcm93cy5maWx0ZXIoQm9vbGVhbikKCiAgaWYgKGNsZWFuUm93cy5sZW5ndGggPT09IDApIHJldHVybgoKICB0YXJnZXQucHVzaCgnJykKICB0YXJnZXQucHVzaCh0aXRsZSkKICB0YXJnZXQucHVzaCguLi5jbGVhblJvd3MpCn0KCmV4cG9ydCBmdW5jdGlvbiBidWlsZE9yZGVyV2hhdHNBcHBNZXNzYWdlKAogIG9yZGVyVmFsdWU6IHVua25vd24sCikgewogIGNvbnN0IG9yZGVyID0gYXNSZWNvcmQob3JkZXJWYWx1ZSkgfHwge30KCiAgY29uc3QgY3VzdG9tZXJOYW1lID0KICAgIGZpcnN0VGV4dChvcmRlciwgWwogICAgICAnY3VzdG9tZXJfbmFtZScsCiAgICAgICdub21lJywKICAgIF0pIHx8ICdjbGllbnRlJwoKICBjb25zdCBvcmRlck51bWJlciA9CiAgICBnZXRPcmRlckRpc3BsYXlOdW1iZXIob3JkZXIpCgogIGNvbnN0IHB1cmNoYXNlRGF0ZSA9CiAgICBmb3JtYXREYXRlVGltZVBhcnRzKG9yZGVyLmNyZWF0ZWRfYXQpCgogIGNvbnN0IG9yZGVyU3RhdHVzID0KICAgIGZpcnN0VGV4dChvcmRlciwgWydzdGF0dXMnXSkgfHwgJ1JlY2ViaWRvJwoKICBjb25zdCBwYXltZW50U3RhdHVzID0KICAgIHBheW1lbnRTdGF0dXNMYWJlbChvcmRlci5wYXltZW50X3N0YXR1cykKCiAgY29uc3QgaXRlbXMgPSBidWlsZEl0ZW1zU2VjdGlvbihvcmRlcikKCiAgY29uc3QgbGluZXM6IHN0cmluZ1tdID0gWwogICAgYE9sw6EsICoke2N1c3RvbWVyTmFtZX0qISBcdXsxRjQ0Qn1gLAogICAgJycsCiAgICAnVHVkbyBiZW0/IEVzdGFtb3MgZW50cmFuZG8gZW0gY29udGF0byBwYXJhIGZhbGFyIHNvYnJlIG8gc2V1IHBlZGlkby4gUGFyYSBmYWNpbGl0YXIsIGRlaXhhbW9zIG8gcmVzdW1vIGNvbXBsZXRvIGxvZ28gYWJhaXhvOicsCiAgICAnJywKICAgICfilIHilIHilIHilIHilIHilIHilIHilIHilIHilIHilIHilIHilIHilIHilIHilIHilIHilIEnLAogICAgYFx1ezFGNEU2fSAqUEVESURPICMke29yZGVyTnVtYmVyfSpgLAogICAgJ+KUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgScsCiAgXQoKICBpZiAocHVyY2hhc2VEYXRlLmRhdGUpIHsKICAgIGxpbmVzLnB1c2goCiAgICAgIGBcdXsxRjRDNX0gKkRhdGEgZGEgY29tcHJhOiogJHtwdXJjaGFzZURhdGUuZGF0ZX1gLAogICAgKQogIH0KCiAgaWYgKHB1cmNoYXNlRGF0ZS50aW1lKSB7CiAgICBsaW5lcy5wdXNoKAogICAgICBgXHV7MUY1NTJ9ICpIb3LDoXJpbyBkYSBjb21wcmE6KiAke3B1cmNoYXNlRGF0ZS50aW1lfWAsCiAgICApCiAgfQoKICBsaW5lcy5wdXNoKGBcdXsxRjRDQ30gKlN0YXR1cyBkbyBwZWRpZG86KiAke29yZGVyU3RhdHVzfWApCgogIGlmIChwYXltZW50U3RhdHVzKSB7CiAgICBsaW5lcy5wdXNoKAogICAgICBgXHV7MUY0QjN9ICpTdGF0dXMgZG8gcGFnYW1lbnRvOiogJHtwYXltZW50U3RhdHVzfWAsCiAgICApCiAgfQoKICBjb25zdCBkZWFkbGluZSA9IGZvcm1hdERhdGVUaW1lKG9yZGVyLnByYXpvX2VudHJlZ2EpCgogIGlmIChkZWFkbGluZSkgewogICAgbGluZXMucHVzaChgXHV7MjNGMX1cdXtGRTBGfSAqUHJhem8gcHJldmlzdG86KiAke2RlYWRsaW5lfWApCiAgfQoKICBwdXNoU2VjdGlvbigKICAgIGxpbmVzLAogICAgJ1x1ezFGNkNEfVx1e0ZFMEZ9ICpJVEVOUyBETyBQRURJRE8qJywKICAgIGl0ZW1zLAogICkKCiAgY29uc3QgZGVsaXZlcnlUeXBlID0gZGVsaXZlcnlUeXBlTGFiZWwoCiAgICBvcmRlci5kZWxpdmVyeV90eXBlLAogICkKCiAgY29uc3QgYWRkcmVzcyA9CiAgICBmaXJzdFRleHQob3JkZXIsIFsKICAgICAgJ2FkZHJlc3MnLAogICAgICAnZW5kZXJlY29fZW50cmVnYScsCiAgICBdKQoKICBjb25zdCBuZWlnaGJvcmhvb2QgPQogICAgZmlyc3RUZXh0KG9yZGVyLCBbJ25laWdoYm9yaG9vZCddKQoKICBjb25zdCBjb21wbGVtZW50ID0KICAgIGZpcnN0VGV4dChvcmRlciwgWydjb21wbGVtZW50J10pCgogIGNvbnN0IHJlZmVyZW5jZVBvaW50ID0KICAgIGZpcnN0VGV4dChvcmRlciwgWydyZWZlcmVuY2VfcG9pbnQnXSkKCiAgY29uc3QgZGVsaXZlcnlGZWUgPQogICAgZmlyc3ROdW1iZXIob3JkZXIsIFsnZGVsaXZlcnlfZmVlJ10pCgogIGNvbnN0IGRlbGl2ZXJ5Um93czogc3RyaW5nW10gPSBbXQoKICBpZiAoZGVsaXZlcnlUeXBlKSB7CiAgICBkZWxpdmVyeVJvd3MucHVzaCgKICAgICAgYFx1ezFGNjlBfSAqTW9kYWxpZGFkZToqICR7ZGVsaXZlcnlUeXBlfWAsCiAgICApCiAgfQoKICBpZiAoYWRkcmVzcykgewogICAgZGVsaXZlcnlSb3dzLnB1c2goYFx1ezFGNENEfSAqRW5kZXJlw6dvOiogJHthZGRyZXNzfWApCiAgfQoKICBpZiAobmVpZ2hib3Job29kKSB7CiAgICBkZWxpdmVyeVJvd3MucHVzaCgKICAgICAgYFx1ezFGM0Q4fVx1e0ZFMEZ9ICpCYWlycm86KiAke25laWdoYm9yaG9vZH1gLAogICAgKQogIH0KCiAgaWYgKGNvbXBsZW1lbnQpIHsKICAgIGRlbGl2ZXJ5Um93cy5wdXNoKAogICAgICBgXHV7MUYzRTB9ICpDb21wbGVtZW50bzoqICR7Y29tcGxlbWVudH1gLAogICAgKQogIH0KCiAgaWYgKHJlZmVyZW5jZVBvaW50KSB7CiAgICBkZWxpdmVyeVJvd3MucHVzaCgKICAgICAgYFx1ezFGOUVEfSAqUG9udG8gZGUgcmVmZXLDqm5jaWE6KiAke3JlZmVyZW5jZVBvaW50fWAsCiAgICApCiAgfQoKICBpZiAoZGVsaXZlcnlGZWUgPiAwKSB7CiAgICBkZWxpdmVyeVJvd3MucHVzaCgKICAgICAgYFx1ezFGNkY1fSAqVGF4YSBkZSBlbnRyZWdhOiogJHttb25leShkZWxpdmVyeUZlZSl9YCwKICAgICkKICB9CgogIHB1c2hTZWN0aW9uKAogICAgbGluZXMsCiAgICBkZWxpdmVyeVR5cGUKICAgICAgPyBgXHV7MUY2OUF9ICoke2RlbGl2ZXJ5VHlwZS50b1VwcGVyQ2FzZSgpfSpgCiAgICAgIDogJ1x1ezFGNjlBfSAqRU5UUkVHQSAvIFJFVElSQURBKicsCiAgICBkZWxpdmVyeVJvd3MsCiAgKQoKICBjb25zdCBwYXltZW50TWV0aG9kID0gZmlyc3RUZXh0KG9yZGVyLCBbCiAgICAncGF5bWVudF9tZXRob2QnLAogICAgJ2Zvcm1hX3BhZ2FtZW50bycsCiAgXSkKCiAgY29uc3Qgc3VidG90YWwgPSBmaXJzdE51bWJlcihvcmRlciwgWwogICAgJ3N1YnRvdGFsJywKICBdKQoKICBjb25zdCBkaXNjb3VudCA9IGZpcnN0TnVtYmVyKG9yZGVyLCBbCiAgICAnZGlzY291bnRfYW1vdW50JywKICAgICd2YWxvcl9kZXNjb250bycsCiAgXSkKCiAgY29uc3QgY291cG9uID0gZmlyc3RUZXh0KG9yZGVyLCBbCiAgICAnY291cG9uX2NvZGUnLAogICAgJ2N1cG9tX2NvZGlnbycsCiAgXSkKCiAgY29uc3QgdG90YWwgPSBmaXJzdE51bWJlcihvcmRlciwgWwogICAgJ3RvdGFsX2Ftb3VudCcsCiAgICAndG90YWwnLAogICAgJ3ZhbG9yX3RvdGFsJywKICAgICdwcmVjb19lc3RpbWFkbycsCiAgXSkKCiAgY29uc3QgY2hhbmdlRm9yID0gZmlyc3ROdW1iZXIob3JkZXIsIFsKICAgICdjaGFuZ2VfZm9yJywKICBdKQoKICBjb25zdCBpbnN0YWxsbWVudHMgPSBmaXJzdE51bWJlcihvcmRlciwgWwogICAgJ3BhcmNlbGFzJywKICBdKQoKICBjb25zdCBwYXltZW50Um93czogc3RyaW5nW10gPSBbXQoKICBpZiAocGF5bWVudE1ldGhvZCkgewogICAgcGF5bWVudFJvd3MucHVzaCgKICAgICAgYFx1ezFGNEIzfSAqRm9ybWEgZGUgcGFnYW1lbnRvOiogJHtwYXltZW50TWV0aG9kfWAsCiAgICApCiAgfQoKICBpZiAoaW5zdGFsbG1lbnRzID4gMSkgewogICAgcGF5bWVudFJvd3MucHVzaCgKICAgICAgYFx1ezFGOUZFfSAqUGFyY2VsYXM6KiAke2luc3RhbGxtZW50c314YCwKICAgICkKICB9CgogIGlmIChzdWJ0b3RhbCA+IDApIHsKICAgIHBheW1lbnRSb3dzLnB1c2goCiAgICAgIGBcdXsxRjRCMH0gKlN1YnRvdGFsOiogJHttb25leShzdWJ0b3RhbCl9YCwKICAgICkKICB9CgogIGlmIChkaXNjb3VudCA+IDApIHsKICAgIHBheW1lbnRSb3dzLnB1c2goCiAgICAgIGBcdXsxRjNGN31cdXtGRTBGfSAqRGVzY29udG86KiAtJHttb25leShkaXNjb3VudCl9YCwKICAgICkKICB9CgogIGlmIChjb3Vwb24pIHsKICAgIHBheW1lbnRSb3dzLnB1c2goCiAgICAgIGBcdXsxRjM5Rn1cdXtGRTBGfSAqQ3Vwb206KiAke2NvdXBvbn1gLAogICAgKQogIH0KCiAgaWYgKGRlbGl2ZXJ5RmVlID4gMCkgewogICAgcGF5bWVudFJvd3MucHVzaCgKICAgICAgYFx1ezFGNkY1fSAqRW50cmVnYToqICR7bW9uZXkoZGVsaXZlcnlGZWUpfWAsCiAgICApCiAgfQoKICBpZiAodG90YWwgPiAwKSB7CiAgICBwYXltZW50Um93cy5wdXNoKAogICAgICBgXHV7MUY0QjV9ICpUT1RBTCBETyBQRURJRE86KiAqJHttb25leSh0b3RhbCl9KmAsCiAgICApCiAgfQoKICBpZiAoY2hhbmdlRm9yID4gMCkgewogICAgcGF5bWVudFJvd3MucHVzaCgKICAgICAgYFx1ezFGNEI4fSAqVHJvY28gcGFyYToqICR7bW9uZXkoY2hhbmdlRm9yKX1gLAogICAgKQogIH0KCiAgcHVzaFNlY3Rpb24oCiAgICBsaW5lcywKICAgICdcdXsxRjRCMH0gKlBBR0FNRU5UTyBFIFZBTE9SRVMqJywKICAgIHBheW1lbnRSb3dzLAogICkKCiAgY29uc3QgY3VzdG9tZXJOb3RlcyA9IGZpcnN0VGV4dChvcmRlciwgWwogICAgJ29ic2VydmFjb2VzJywKICBdKQoKICBpZiAoY3VzdG9tZXJOb3RlcykgewogICAgcHVzaFNlY3Rpb24oCiAgICAgIGxpbmVzLAogICAgICAnXHV7MUY0RER9ICpPQlNFUlZBw4fDlUVTIERPIFBFRElETyonLAogICAgICBbY3VzdG9tZXJOb3Rlc10sCiAgICApCiAgfQoKICBsaW5lcy5wdXNoKCcnKQogIGxpbmVzLnB1c2goJ+KUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgeKUgScpCiAgbGluZXMucHVzaCgKICAgICdTZSBwcmVjaXNhciBjb3JyaWdpciBhbGd1bWEgaW5mb3JtYcOnw6NvIG91IHRpdmVyIGFsZ3VtYSBkw7p2aWRhLCBwb2RlIHJlc3BvbmRlciBwb3IgYXF1aS4gXHV7MUY2MEF9JywKICApCgogIHJldHVybiBsaW5lcy5qb2luKCdcbicpCn0KCmV4cG9ydCBmdW5jdGlvbiBidWlsZE9yZGVyV2hhdHNBcHBMaW5rKAogIG9yZGVyVmFsdWU6IHVua25vd24sCikgewogIGNvbnN0IHBob25lID0gbm9ybWFsaXplZFdoYXRzQXBwUGhvbmUob3JkZXJWYWx1ZSkKCiAgaWYgKCFwaG9uZSkgcmV0dXJuICcjJwoKICBjb25zdCBtZXNzYWdlID0KICAgIGJ1aWxkT3JkZXJXaGF0c0FwcE1lc3NhZ2Uob3JkZXJWYWx1ZSkKCiAgcmV0dXJuIGBodHRwczovL3dhLm1lLyR7cGhvbmV9P3RleHQ9JHtlbmNvZGVVUklDb21wb25lbnQobWVzc2FnZSl9YAp9Cg==")
    $content = [Text.Encoding]::UTF8.GetString($bytes)
    [IO.File]::WriteAllText($Target, $content, $Utf8NoBom)

    if ((Sha $Target) -ne $DesiredSha) {
        throw "O arquivo gravado nao corresponde ao conteudo validado."
    }

    $after = [IO.File]::ReadAllText($Target)

    if (-not $after.Contains($MarkerNew)) {
        throw "Marcador Unicode nao encontrado."
    }

    if (-not $after.Contains('\u{1F4E6} *PEDIDO #')) {
        throw "Emoji do pedido nao foi convertido para escape Unicode."
    }

    if (-not $after.Contains('\u{1F4B5} *TOTAL DO PEDIDO:*')) {
        throw "Emoji do total nao foi convertido para escape Unicode."
    }

    if (-not $after.Contains('\u{1F60A}')) {
        throw "Emoji final nao foi convertido para escape Unicode."
    }

    Ok "Todos os emojis da mensagem agora sao gerados por escapes Unicode."

    Step "Lint"
    & npx.cmd eslint "lib/order-whatsapp.ts"

    if ($LASTEXITCODE -ne 0) {
        throw "O gerador WhatsApp falhou no lint."
    }

    Ok "Lint passou."

    if (-not $SkipFinalBuild) {
        Step "Build final"
        & npm.cmd run build

        if ($LASTEXITCODE -ne 0) {
            throw "O build final falhou apos a correcao Unicode."
        }

        Ok "Build final passou."
    }

    Step "Resumo"

    Write-Host ""
    Write-Host "WHATSAPP UNICODE CORRIGIDO" -ForegroundColor Green
    Write-Host ""
    Write-Host " - emojis literais removidos do codigo-fonte"
    Write-Host " - emojis reconstruidos por Unicode no navegador"
    Write-Host " - encodeURIComponent continua protegendo a URL wa.me"
    Write-Host " - mensagem e dados do pedido foram preservados"
    Write-Host " - nenhum banco, checkout ou API foi alterado"
    Write-Host ""
    Write-Host "Teste agora em /painel/pedidos."
    Write-Host ""
    Write-Host "Nenhum commit, push ou deploy foi executado." -ForegroundColor Cyan
}
catch {
    Write-Host ""
    Write-Host ("[ERRO] " + $_.Exception.Message) -ForegroundColor Red

    if (Test-Path -LiteralPath $BackupFile -PathType Leaf) {
        Restore
    }

    Write-Host ("Backup/diagnostico: " + $BackupRoot) -ForegroundColor Yellow
    exit 1
}
