$ErrorActionPreference = "Stop"

$project = "C:\Users\arauj\grafica-flash"

if (!(Test-Path -LiteralPath $project)) {
  Write-Host "Projeto nao encontrado em $project" -ForegroundColor Red
  exit 1
}

Set-Location -LiteralPath $project

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-Base64File($relativePath, $base64Content) {
  $target = Join-Path $project $relativePath
  $directory = Split-Path $target -Parent
  New-Item -ItemType Directory -Force -Path $directory | Out-Null

  $bytes = [System.Convert]::FromBase64String($base64Content.Trim())
  $content = [System.Text.Encoding]::UTF8.GetString($bytes)
  [System.IO.File]::WriteAllText($target, $content, $utf8NoBom)

  Write-Host "Corrigido: $relativePath" -ForegroundColor Green
}

Write-Base64File "lib\admin-auth.ts" @"
aW1wb3J0IHsgTmV4dFJlcXVlc3QsIE5leHRSZXNwb25zZSB9IGZyb20gJ25leHQvc2VydmVyJwppbXBvcnQgeyBjcmVhdGVDbGllbnQgfSBmcm9tICdAc3VwYWJhc2Uvc3VwYWJhc2UtanMnCgpleHBvcnQgY29uc3Qgc3VwYWJhc2VBZG1pbiA9IGNyZWF0ZUNsaWVudCgKICBwcm9jZXNzLmVudi5ORVhUX1BVQkxJQ19TVVBBQkFTRV9VUkwhLAogIHByb2Nlc3MuZW52LlNVUEFCQVNFX1NFUlZJQ0VfUk9MRV9LRVkhLAogIHsgYXV0aDogeyBwZXJzaXN0U2Vzc2lvbjogZmFsc2UgfSB9CikKCmV4cG9ydCB0eXBlIEFkbWluU2Vzc2lvbiA9IHsKICBpZDogc3RyaW5nCiAgZW1haWw6IHN0cmluZwogIG5vbWU6IHN0cmluZwogIHJvbGU6ICdzdXBlcl9hZG1pbicgfCAnYWRtaW4nIHwgJ3N1cG9ydGUnCiAgcGVybWlzc2lvbnM6IFJlY29yZDxzdHJpbmcsIGFueT4KfQoKZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIGdldEN1cnJlbnRBZG1pbihyZXF1ZXN0OiBOZXh0UmVxdWVzdCk6IFByb21pc2U8QWRtaW5TZXNzaW9uIHwgbnVsbD4gewogIGNvbnN0IHRva2VuID0gKHJlcXVlc3QuaGVhZGVycy5nZXQoJ2F1dGhvcml6YXRpb24nKSB8fCAnJykucmVwbGFjZSgnQmVhcmVyICcsICcnKS50cmltKCkKCiAgaWYgKCF0b2tlbikgcmV0dXJuIG51bGwKCiAgY29uc3QgeyBkYXRhLCBlcnJvciB9ID0gYXdhaXQgc3VwYWJhc2VBZG1pbi5hdXRoLmdldFVzZXIodG9rZW4pCgogIGlmIChlcnJvciB8fCAhZGF0YS51c2VyPy5lbWFpbCkgcmV0dXJuIG51bGwKCiAgY29uc3QgZW1haWwgPSBkYXRhLnVzZXIuZW1haWwudG9Mb3dlckNhc2UoKQoKICBjb25zdCB7IGRhdGE6IGFkbWluIH0gPSBhd2FpdCBzdXBhYmFzZUFkbWluCiAgICAuZnJvbSgnYWRtaW5fdXNlcnMnKQogICAgLnNlbGVjdCgnZW1haWwsbm9tZSxyb2xlLGF0aXZvLHBlcm1pc3Npb25zJykKICAgIC5lcSgnYXRpdm8nLCB0cnVlKQogICAgLmlsaWtlKCdlbWFpbCcsIGVtYWlsKQogICAgLm1heWJlU2luZ2xlKCkKCiAgaWYgKCFhZG1pbiAmJiBlbWFpbCAhPT0gJ2FyYXVqb3ZpbmljaXVzMjQ5QGdtYWlsLmNvbScpIHJldHVybiBudWxsCgogIHJldHVybiB7CiAgICBpZDogZGF0YS51c2VyLmlkLAogICAgZW1haWwsCiAgICBub21lOiBhZG1pbj8ubm9tZSB8fCBkYXRhLnVzZXIudXNlcl9tZXRhZGF0YT8ubm9tZSB8fCAnQWRtaW4nLAogICAgcm9sZTogYWRtaW4/LnJvbGUgfHwgJ3N1cGVyX2FkbWluJywKICAgIHBlcm1pc3Npb25zOiBhZG1pbj8ucGVybWlzc2lvbnMgfHwgeyBhbGw6IHRydWUgfSwKICB9Cn0KCmV4cG9ydCBmdW5jdGlvbiBjYW4oYWRtaW46IEFkbWluU2Vzc2lvbiwgcGVybWlzc2lvbjogc3RyaW5nKSB7CiAgaWYgKGFkbWluLnJvbGUgPT09ICdzdXBlcl9hZG1pbicpIHJldHVybiB0cnVlCiAgaWYgKGFkbWluLnBlcm1pc3Npb25zPy5hbGwpIHJldHVybiB0cnVlCiAgcmV0dXJuIEJvb2xlYW4oYWRtaW4ucGVybWlzc2lvbnM/LltwZXJtaXNzaW9uXSkKfQoKLyoqCiAqIENvbXBhdGliaWxpZGFkZSBjb20gcm90YXMgYW50aWdhcyBkbyBBZG1pbiBNYXN0ZXIuCiAqIEFsZ3VtYXMgcm90YXMgYWluZGEgaW1wb3J0YW0gcmVxdWlyZUFkbWluIGRlICdAL2xpYi9hZG1pbi1hdXRoJy4KICogTWFudGVtb3MgZXNzZSBleHBvcnQgcGFyYSBvIGJ1aWxkIG7Do28gcXVlYnJhciBlbnF1YW50byBvIGFkbWluIG5vdm8gdXNhIGdldEN1cnJlbnRBZG1pbi4KICovCmV4cG9ydCBhc3luYyBmdW5jdGlvbiByZXF1aXJlQWRtaW4ocmVxdWVzdDogTmV4dFJlcXVlc3QsIHBlcm1pc3Npb24/OiBzdHJpbmcpOiBQcm9taXNlPGFueT4gewogIGNvbnN0IGFkbWluID0gYXdhaXQgZ2V0Q3VycmVudEFkbWluKHJlcXVlc3QpCgogIGlmICghYWRtaW4pIHsKICAgIHJldHVybiBOZXh0UmVzcG9uc2UuanNvbih7IGVycm9yOiAnQWNlc3NvIG5lZ2Fkby4nIH0sIHsgc3RhdHVzOiA0MDMgfSkKICB9CgogIGlmIChwZXJtaXNzaW9uICYmICFjYW4oYWRtaW4sIHBlcm1pc3Npb24pKSB7CiAgICByZXR1cm4gTmV4dFJlc3BvbnNlLmpzb24oeyBlcnJvcjogJ1NlbSBwZXJtaXNzw6NvIHBhcmEgZXN0YSBhw6fDo28uJyB9LCB7IHN0YXR1czogNDAzIH0pCiAgfQoKICByZXR1cm4gYWRtaW4KfQoKZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIGF1ZGl0TG9nKAogIGFkbWluRW1haWw6IHN0cmluZywKICBhY3Rpb246IHN0cmluZywKICB0YXJnZXRUeXBlPzogc3RyaW5nLAogIHRhcmdldElkPzogc3RyaW5nLAogIHRhcmdldExhYmVsPzogc3RyaW5nLAogIHBheWxvYWQ/OiBhbnkKKSB7CiAgYXdhaXQgc3VwYWJhc2VBZG1pbi5mcm9tKCdhZG1pbl9hdWRpdF9sb2dzJykuaW5zZXJ0KHsKICAgIGFkbWluX2VtYWlsOiBhZG1pbkVtYWlsLAogICAgYWN0aW9uLAogICAgdGFyZ2V0X3R5cGU6IHRhcmdldFR5cGUgfHwgbnVsbCwKICAgIHRhcmdldF9pZDogdGFyZ2V0SWQgfHwgbnVsbCwKICAgIHRhcmdldF9sYWJlbDogdGFyZ2V0TGFiZWwgfHwgbnVsbCwKICAgIHBheWxvYWQ6IHBheWxvYWQgfHwge30sCiAgfSkKfQoKZXhwb3J0IGZ1bmN0aW9uIGZhaWwoZXJyb3I6IHN0cmluZywgc3RhdHVzID0gNDAwKSB7CiAgcmV0dXJuIE5leHRSZXNwb25zZS5qc29uKHsgZXJyb3IgfSwgeyBzdGF0dXMgfSkKfQo=
"@

Remove-Item -Recurse -Force ".next" -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "Compatibilidade requireAdmin restaurada." -ForegroundColor Green
Write-Host "Agora rode: npm run build" -ForegroundColor Yellow
