$ErrorActionPreference = "Stop"

$project = "C:\Users\arauj\grafica-flash"

if (!(Test-Path $project)) {
  Write-Host "Projeto nao encontrado em $project" -ForegroundColor Red
  exit 1
}

Set-Location $project

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-Base64File($relativePath, $base64Content) {
  $target = Join-Path $project $relativePath
  $directory = Split-Path $target -Parent

  New-Item -ItemType Directory -Force $directory | Out-Null

  $bytes = [System.Convert]::FromBase64String($base64Content.Trim())
  $content = [System.Text.Encoding]::UTF8.GetString($bytes)

  [System.IO.File]::WriteAllText($target, $content, $utf8NoBom)
}


Write-Base64File "proxy.ts" @"
aW1wb3J0IHsgTmV4dFJlcXVlc3QsIE5leHRSZXNwb25zZSB9IGZyb20gJ25leHQvc2VydmVyJwoKY29uc3QgUk9PVF9ET01BSU4gPSAocHJvY2Vzcy5lbnYuTkVYVF9QVUJMSUNfUk9PVF9ET01BSU4gfHwgJ29yY2FseS5jb20uYnInKS50b0xvd2VyQ2FzZSgpCgpjb25zdCBSRVNFUlZFRF9TVUJET01BSU5TID0gbmV3IFNldChbCiAgJ3d3dycsCiAgJ2FkbWluJywKICAnYXBpJywKICAnYXBwJywKICAnbG9naW4nLAogICdwYWluZWwnLAogICdkYXNoYm9hcmQnLAogICdjYWRhc3RybycsCiAgJ2NoZWNrb3V0JywKICAnYXNzaW5hdHVyYScsCiAgJ3Byb3Bvc3RhJywKICAncHJvcG9zdGFzJywKICAnYXNzZXRzJywKICAnc3RhdGljJywKICAncHVibGljJywKICAncHJpdmF0ZScsCiAgJ2NvbmZpZycsCiAgJ3NldHRpbmdzJywKICAnc2VjdXJpdHknLAogICdhdXRoJywKXSkKCmZ1bmN0aW9uIGFwcGx5U2VjdXJpdHlIZWFkZXJzKHJlc3BvbnNlOiBOZXh0UmVzcG9uc2UpIHsKICByZXNwb25zZS5oZWFkZXJzLnNldCgnWC1GcmFtZS1PcHRpb25zJywgJ0RFTlknKQogIHJlc3BvbnNlLmhlYWRlcnMuc2V0KCdYLUNvbnRlbnQtVHlwZS1PcHRpb25zJywgJ25vc25pZmYnKQogIHJlc3BvbnNlLmhlYWRlcnMuc2V0KCdSZWZlcnJlci1Qb2xpY3knLCAnc3RyaWN0LW9yaWdpbi13aGVuLWNyb3NzLW9yaWdpbicpCiAgcmVzcG9uc2UuaGVhZGVycy5zZXQoJ1gtRE5TLVByZWZldGNoLUNvbnRyb2wnLCAnb2ZmJykKICByZXNwb25zZS5oZWFkZXJzLnNldCgnUGVybWlzc2lvbnMtUG9saWN5JywgJ2NhbWVyYT0oKSwgbWljcm9waG9uZT0oKSwgZ2VvbG9jYXRpb249KCksIHBheW1lbnQ9KCknKQogIHJlc3BvbnNlLmhlYWRlcnMuc2V0KCdDcm9zcy1PcmlnaW4tT3BlbmVyLVBvbGljeScsICdzYW1lLW9yaWdpbicpCgogIHJldHVybiByZXNwb25zZQp9CgpmdW5jdGlvbiBjbGVhblN1YmRvbWFpbih2YWx1ZTogc3RyaW5nKSB7CiAgcmV0dXJuIHZhbHVlCiAgICAudG9Mb3dlckNhc2UoKQogICAgLnJlcGxhY2UoL1teYS16MC05XS9nLCAnJykKICAgIC5zbGljZSgwLCA0MikKfQoKZnVuY3Rpb24gZ2V0SG9zdG5hbWUocmVxdWVzdDogTmV4dFJlcXVlc3QpIHsKICBjb25zdCBob3N0ID0gcmVxdWVzdC5oZWFkZXJzLmdldCgnaG9zdCcpIHx8ICcnCiAgcmV0dXJuIGhvc3Quc3BsaXQoJzonKVswXS50b0xvd2VyQ2FzZSgpCn0KCmZ1bmN0aW9uIGdldFBvcnQocmVxdWVzdDogTmV4dFJlcXVlc3QpIHsKICBjb25zdCBob3N0ID0gcmVxdWVzdC5oZWFkZXJzLmdldCgnaG9zdCcpIHx8ICcnCiAgY29uc3QgcGFydHMgPSBob3N0LnNwbGl0KCc6JykKICByZXR1cm4gcGFydHMubGVuZ3RoID4gMSA/IGA6JHtwYXJ0c1sxXX1gIDogJycKfQoKZnVuY3Rpb24gZ2V0VGVuYW50U3ViZG9tYWluKGhvc3RuYW1lOiBzdHJpbmcpIHsKICBpZiAoIWhvc3RuYW1lKSByZXR1cm4gbnVsbAoKICBpZiAoaG9zdG5hbWUgPT09IFJPT1RfRE9NQUlOIHx8IGhvc3RuYW1lID09PSBgd3d3LiR7Uk9PVF9ET01BSU59YCkgewogICAgcmV0dXJuIG51bGwKICB9CgogIGlmIChob3N0bmFtZS5lbmRzV2l0aChgLiR7Uk9PVF9ET01BSU59YCkpIHsKICAgIGNvbnN0IGxlZnQgPSBob3N0bmFtZS5zbGljZSgwLCAtKGAuJHtST09UX0RPTUFJTn1gKS5sZW5ndGgpCiAgICBjb25zdCBmaXJzdCA9IGxlZnQuc3BsaXQoJy4nKVswXQogICAgY29uc3Qgc3ViZG9tYWluID0gY2xlYW5TdWJkb21haW4oZmlyc3QpCgogICAgaWYgKCFzdWJkb21haW4gfHwgUkVTRVJWRURfU1VCRE9NQUlOUy5oYXMoc3ViZG9tYWluKSkgcmV0dXJuIG51bGwKCiAgICByZXR1cm4gc3ViZG9tYWluCiAgfQoKICAvLyBBanVkYSBubyBhbWJpZW50ZSBsb2NhbDogaHR0cDovL2dyYWZpY2FmbGFzaC5sb2NhbGhvc3Q6MzAwMAogIGlmIChob3N0bmFtZS5lbmRzV2l0aCgnLmxvY2FsaG9zdCcpKSB7CiAgICBjb25zdCBmaXJzdCA9IGhvc3RuYW1lLnJlcGxhY2UoJy5sb2NhbGhvc3QnLCAnJykuc3BsaXQoJy4nKVswXQogICAgY29uc3Qgc3ViZG9tYWluID0gY2xlYW5TdWJkb21haW4oZmlyc3QpCgogICAgaWYgKCFzdWJkb21haW4gfHwgUkVTRVJWRURfU1VCRE9NQUlOUy5oYXMoc3ViZG9tYWluKSkgcmV0dXJuIG51bGwKCiAgICByZXR1cm4gc3ViZG9tYWluCiAgfQoKICByZXR1cm4gbnVsbAp9CgpmdW5jdGlvbiBpc1B1YmxpY0ZpbGUocGF0aG5hbWU6IHN0cmluZykgewogIHJldHVybiAvXC4oPzpwbmd8anBnfGpwZWd8Z2lmfHdlYnB8c3ZnfGljb3xjc3N8anN8dHh0fHhtbHx3ZWJtYW5pZmVzdHxtYXApJC9pLnRlc3QocGF0aG5hbWUpCn0KCmZ1bmN0aW9uIHNob3VsZEJ5cGFzcyhwYXRobmFtZTogc3RyaW5nKSB7CiAgcmV0dXJuICgKICAgIHBhdGhuYW1lLnN0YXJ0c1dpdGgoJy9fbmV4dCcpIHx8CiAgICBwYXRobmFtZS5zdGFydHNXaXRoKCcvYXBpJykgfHwKICAgIHBhdGhuYW1lLnN0YXJ0c1dpdGgoJy9mYXZpY29uJykgfHwKICAgIGlzUHVibGljRmlsZShwYXRobmFtZSkKICApCn0KCmZ1bmN0aW9uIGlzUm9vdERvbWFpbihob3N0bmFtZTogc3RyaW5nKSB7CiAgcmV0dXJuIGhvc3RuYW1lID09PSBST09UX0RPTUFJTiB8fCBob3N0bmFtZSA9PT0gYHd3dy4ke1JPT1RfRE9NQUlOfWAgfHwgaG9zdG5hbWUgPT09ICdsb2NhbGhvc3QnCn0KCmZ1bmN0aW9uIHJlZGlyZWN0Um9vdE9yY2FtZW50b1RvU3ViZG9tYWluKHJlcXVlc3Q6IE5leHRSZXF1ZXN0LCBob3N0bmFtZTogc3RyaW5nKSB7CiAgY29uc3QgeyBwYXRobmFtZSB9ID0gcmVxdWVzdC5uZXh0VXJsCgogIGlmICghaXNSb290RG9tYWluKGhvc3RuYW1lKSkgcmV0dXJuIG51bGwKICBpZiAoIXBhdGhuYW1lLnN0YXJ0c1dpdGgoJy9vcmNhbWVudG8vJykpIHJldHVybiBudWxsCgogIGNvbnN0IHJhd1NsdWcgPSBwYXRobmFtZS5zcGxpdCgnLycpWzJdIHx8ICcnCiAgY29uc3Qgc3ViZG9tYWluID0gY2xlYW5TdWJkb21haW4ocmF3U2x1ZykKCiAgaWYgKCFzdWJkb21haW4gfHwgUkVTRVJWRURfU1VCRE9NQUlOUy5oYXMoc3ViZG9tYWluKSkgcmV0dXJuIG51bGwKCiAgY29uc3QgdXJsID0gcmVxdWVzdC5uZXh0VXJsLmNsb25lKCkKICBjb25zdCBwb3J0ID0gZ2V0UG9ydChyZXF1ZXN0KQoKICBpZiAoaG9zdG5hbWUgPT09ICdsb2NhbGhvc3QnKSB7CiAgICB1cmwuaG9zdG5hbWUgPSBgJHtzdWJkb21haW59LmxvY2FsaG9zdGAKICAgIGlmIChwb3J0KSB1cmwucG9ydCA9IHBvcnQucmVwbGFjZSgnOicsICcnKQogICAgdXJsLnBhdGhuYW1lID0gJy8nCiAgICByZXR1cm4gYXBwbHlTZWN1cml0eUhlYWRlcnMoTmV4dFJlc3BvbnNlLnJlZGlyZWN0KHVybCkpCiAgfQoKICB1cmwuaG9zdG5hbWUgPSBgJHtzdWJkb21haW59LiR7Uk9PVF9ET01BSU59YAogIHVybC5wYXRobmFtZSA9ICcvJwogIHJldHVybiBhcHBseVNlY3VyaXR5SGVhZGVycyhOZXh0UmVzcG9uc2UucmVkaXJlY3QodXJsKSkKfQoKZXhwb3J0IGZ1bmN0aW9uIHByb3h5KHJlcXVlc3Q6IE5leHRSZXF1ZXN0KSB7CiAgY29uc3QgaG9zdG5hbWUgPSBnZXRIb3N0bmFtZShyZXF1ZXN0KQogIGNvbnN0IHBhdGhuYW1lID0gcmVxdWVzdC5uZXh0VXJsLnBhdGhuYW1lCgogIGNvbnN0IHJvb3RSZWRpcmVjdCA9IHJlZGlyZWN0Um9vdE9yY2FtZW50b1RvU3ViZG9tYWluKHJlcXVlc3QsIGhvc3RuYW1lKQogIGlmIChyb290UmVkaXJlY3QpIHJldHVybiByb290UmVkaXJlY3QKCiAgaWYgKHNob3VsZEJ5cGFzcyhwYXRobmFtZSkpIHsKICAgIHJldHVybiBhcHBseVNlY3VyaXR5SGVhZGVycyhOZXh0UmVzcG9uc2UubmV4dCgpKQogIH0KCiAgY29uc3QgdGVuYW50U3ViZG9tYWluID0gZ2V0VGVuYW50U3ViZG9tYWluKGhvc3RuYW1lKQoKICBpZiAoIXRlbmFudFN1YmRvbWFpbikgewogICAgcmV0dXJuIGFwcGx5U2VjdXJpdHlIZWFkZXJzKE5leHRSZXNwb25zZS5uZXh0KCkpCiAgfQoKICAvLyBTZSBhbGd1w6ltIGFjZXNzYXIgZ3JhZmljYWZsYXNoLm9yY2FseS5jb20uYnIvb3JjYW1lbnRvL2dyYWZpY2FmbGFzaCwKICAvLyBtYW50w6ltIG8gZG9tw61uaW8gYm9uaXRvIGUgbGltcGEgbyBjYW1pbmhvLgogIGlmIChwYXRobmFtZS5zdGFydHNXaXRoKCcvb3JjYW1lbnRvLycpKSB7CiAgICBjb25zdCB1cmwgPSByZXF1ZXN0Lm5leHRVcmwuY2xvbmUoKQogICAgdXJsLnBhdGhuYW1lID0gJy8nCiAgICByZXR1cm4gYXBwbHlTZWN1cml0eUhlYWRlcnMoTmV4dFJlc3BvbnNlLnJlZGlyZWN0KHVybCkpCiAgfQoKICAvLyBSb3RhcyBpbnRlcm5hcyBjb250aW51YW0gZnVuY2lvbmFuZG8gbm8gbWVzbW8gc3ViZG9tw61uaW8uCiAgLy8gRXguOiBncmFmaWNhZmxhc2gub3JjYWx5LmNvbS5ici9wcm9wb3N0YS90b2tlbiBvdSAvbG9naW4KICBjb25zdCBpbnRlcm5hbFJvdXRlcyA9IFsKICAgICcvYWRtaW4nLAogICAgJy9wYWluZWwnLAogICAgJy9sb2dpbicsCiAgICAnL2NhZGFzdHJvJywKICAgICcvY2hlY2tvdXQnLAogICAgJy9hc3NpbmF0dXJhJywKICAgICcvcHJvcG9zdGEnLAogIF0KCiAgaWYgKGludGVybmFsUm91dGVzLnNvbWUoKHJvdXRlKSA9PiBwYXRobmFtZSA9PT0gcm91dGUgfHwgcGF0aG5hbWUuc3RhcnRzV2l0aChgJHtyb3V0ZX0vYCkpKSB7CiAgICByZXR1cm4gYXBwbHlTZWN1cml0eUhlYWRlcnMoTmV4dFJlc3BvbnNlLm5leHQoKSkKICB9CgogIC8vIFF1YWxxdWVyIHDDoWdpbmEgcMO6YmxpY2EgZGEgZW1wcmVzYSBubyBzdWJkb23DrW5pbyBjYWkgbmEgbG9qYSBkYSBlbXByZXNhLAogIC8vIG1hcyBhIFVSTCBjb250aW51YSBncmFmaWNhZmxhc2gub3JjYWx5LmNvbS5ici4KICBjb25zdCByZXdyaXRlVXJsID0gcmVxdWVzdC5uZXh0VXJsLmNsb25lKCkKICByZXdyaXRlVXJsLnBhdGhuYW1lID0gYC9vcmNhbWVudG8vJHt0ZW5hbnRTdWJkb21haW59YAoKICByZXR1cm4gYXBwbHlTZWN1cml0eUhlYWRlcnMoTmV4dFJlc3BvbnNlLnJld3JpdGUocmV3cml0ZVVybCkpCn0KCmV4cG9ydCBjb25zdCBjb25maWcgPSB7CiAgbWF0Y2hlcjogWwogICAgJy8oKD8hX25leHQvc3RhdGljfF9uZXh0L2ltYWdlfGZhdmljb24uaWNvKS4qKScsCiAgXSwKfQo=
"@

Write-Base64File "lib\domain.ts" @"
ZXhwb3J0IGNvbnN0IFJPT1RfRE9NQUlOID0gcHJvY2Vzcy5lbnYuTkVYVF9QVUJMSUNfUk9PVF9ET01BSU4gfHwgJ29yY2FseS5jb20uYnInCgpleHBvcnQgZnVuY3Rpb24gY3JpYXJTdWJkb21pbmlvU2VndXJvKHZhbG9yOiBzdHJpbmcpIHsKICByZXR1cm4gdmFsb3IKICAgIC5ub3JtYWxpemUoJ05GRCcpCiAgICAucmVwbGFjZSgvW1x1MDMwMC1cdTAzNmZdL2csICcnKQogICAgLnRvTG93ZXJDYXNlKCkKICAgIC5yZXBsYWNlKC9bXmEtejAtOV0vZywgJycpCiAgICAuc2xpY2UoMCwgNDIpCn0KCmV4cG9ydCBmdW5jdGlvbiBtb250YXJEb21pbmlvRW1wcmVzYShzbHVnT3VTdWJkb21pbmlvOiBzdHJpbmcpIHsKICBjb25zdCBzdWJkb21haW4gPSBjcmlhclN1YmRvbWluaW9TZWd1cm8oc2x1Z091U3ViZG9taW5pbykKCiAgaWYgKCFzdWJkb21haW4pIHJldHVybiBST09UX0RPTUFJTgoKICByZXR1cm4gYCR7c3ViZG9tYWlufS4ke1JPT1RfRE9NQUlOfWAKfQoKZXhwb3J0IGZ1bmN0aW9uIG1vbnRhclVybEVtcHJlc2Eoc2x1Z091U3ViZG9taW5pbzogc3RyaW5nLCBwYXRoID0gJy8nKSB7CiAgY29uc3QgZG9taW5pbyA9IG1vbnRhckRvbWluaW9FbXByZXNhKHNsdWdPdVN1YmRvbWluaW8pCiAgY29uc3QgcGF0aG5hbWUgPSBwYXRoLnN0YXJ0c1dpdGgoJy8nKSA/IHBhdGggOiBgLyR7cGF0aH1gCgogIHJldHVybiBgaHR0cHM6Ly8ke2RvbWluaW99JHtwYXRobmFtZX1gCn0K
"@

# Next 16 recomenda proxy.ts. Se existir middleware.ts, faz backup e remove para acabar com o aviso.
if (Test-Path "middleware.ts") {
  Copy-Item "middleware.ts" "middleware.backup-before-proxy.ts" -Force
  Remove-Item "middleware.ts" -Force
  Write-Host "middleware.ts removido e salvo como middleware.backup-before-proxy.ts" -ForegroundColor Yellow
}

# Ajusta app/orcamento/[slug]/page.tsx para aceitar slug OU subdomain_slug.
$loja = Join-Path $project "app\orcamento\[slug]\page.tsx"

if (Test-Path $loja) {
  $content = [System.IO.File]::ReadAllText($loja)

  # Inclui subdomain_slug no select se ainda não estiver.
  if ($content -notmatch "subdomain_slug") {
    $content = $content.Replace(
      "id, nome, slug, logo_url",
      "id, nome, slug, subdomain_slug, logo_url"
    )
  }

  # Troca busca exata por slug para aceitar subdomain_slug também.
  $content = $content.Replace(
    ".eq('slug', slug)",
    ".or(`slug.eq.${slug},subdomain_slug.eq.${slug}`)"
  )

  [System.IO.File]::WriteAllText($loja, $content, $utf8NoBom)
  Write-Host "Loja publica ajustada para slug e subdomain_slug." -ForegroundColor Green
} else {
  Write-Host "Nao encontrei app\orcamento\[slug]\page.tsx" -ForegroundColor Yellow
}

# Se cadastro tiver insert de companies, adiciona subdomain_slug visualmente. O trigger do banco ja cobre isso,
# mas assim o front tambem manda o valor limpo.
$cadastro = Join-Path $project "app\cadastro\page.tsx"

if (Test-Path $cadastro) {
  $content = [System.IO.File]::ReadAllText($cadastro)

  if ($content -notmatch "@/lib/domain") {
    $content = $content -replace "(?m)^import .* from '@/lib/security'.*$", '$0' + "`nimport { criarSubdominioSeguro } from '@/lib/domain'"
  }

  if ($content -notmatch "subdomain_slug") {
    $content = $content.Replace(
      "slug: slugValidado.slug,",
      "slug: slugValidado.slug,`n          subdomain_slug: criarSubdominioSeguro(nomeEmpresa),"
    )
  }

  [System.IO.File]::WriteAllText($cadastro, $content, $utf8NoBom)
  Write-Host "Cadastro ajustado para salvar subdomain_slug." -ForegroundColor Green
}

# Garante .env.example com domínio raiz sem expor segredo.
$envExample = Join-Path $project ".env.example"
if (!(Test-Path $envExample)) {
  [System.IO.File]::WriteAllText($envExample, "", $utf8NoBom)
}

$envContent = [System.IO.File]::ReadAllText($envExample)

if ($envContent -notmatch "NEXT_PUBLIC_ROOT_DOMAIN") {
  Add-Content -Path $envExample -Value "NEXT_PUBLIC_ROOT_DOMAIN=orcaly.com.br"
}

Remove-Item -Recurse -Force ".next" -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "Subdominio por empresa instalado." -ForegroundColor Green
Write-Host "Exemplo: graficaflash.orcaly.com.br" -ForegroundColor Cyan
Write-Host "Agora rode: npm run build" -ForegroundColor Yellow
