$ErrorActionPreference = "Stop"

$project = "C:\Users\arauj\grafica-flash"

if (!(Test-Path $project)) {
  Write-Host "Projeto nao encontrado em $project" -ForegroundColor Red
  exit 1
}

Set-Location $project

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-Base64File($relativePath, $base64Content) {
  $target = Join-Path $project $relativePath
  $directory = Split-Path $target -Parent

  New-Item -ItemType Directory -Force $directory | Out-Null

  $bytes = [System.Convert]::FromBase64String($base64Content.Trim())
  $content = [System.Text.Encoding]::UTF8.GetString($bytes)

  [System.IO.File]::WriteAllText($target, $content, $utf8NoBom)
}


Write-Base64File "proxy.ts" @"
aW1wb3J0IHsgTmV4dFJlcXVlc3QsIE5leHRSZXNwb25zZSB9IGZyb20gJ25leHQvc2VydmVyJwoKY29uc3QgUk9PVF9ET01BSU4gPSAocHJvY2Vzcy5lbnYuTkVYVF9QVUJMSUNfUk9PVF9ET01BSU4gfHwgJ29yY2FseS5jb20uYnInKS50b0xvd2VyQ2FzZSgpCgpjb25zdCBSRVNFUlZFRF9TVUJET01BSU5TID0gbmV3IFNldChbCiAgJ3d3dycsCiAgJ2FkbWluJywKICAnYXBpJywKICAnYXBwJywKICAnbG9naW4nLAogICdwYWluZWwnLAogICdkYXNoYm9hcmQnLAogICdjYWRhc3RybycsCiAgJ2NoZWNrb3V0JywKICAnYXNzaW5hdHVyYScsCiAgJ3Byb3Bvc3RhJywKICAncHJvcG9zdGFzJywKICAnYXNzZXRzJywKICAnc3RhdGljJywKICAncHVibGljJywKICAncHJpdmF0ZScsCiAgJ2NvbmZpZycsCiAgJ3NldHRpbmdzJywKICAnc2VjdXJpdHknLAogICdhdXRoJywKXSkKCmZ1bmN0aW9uIGFwcGx5U2VjdXJpdHlIZWFkZXJzKHJlc3BvbnNlOiBOZXh0UmVzcG9uc2UpIHsKICByZXNwb25zZS5oZWFkZXJzLnNldCgnWC1GcmFtZS1PcHRpb25zJywgJ0RFTlknKQogIHJlc3BvbnNlLmhlYWRlcnMuc2V0KCdYLUNvbnRlbnQtVHlwZS1PcHRpb25zJywgJ25vc25pZmYnKQogIHJlc3BvbnNlLmhlYWRlcnMuc2V0KCdSZWZlcnJlci1Qb2xpY3knLCAnc3RyaWN0LW9yaWdpbi13aGVuLWNyb3NzLW9yaWdpbicpCiAgcmVzcG9uc2UuaGVhZGVycy5zZXQoJ1gtRE5TLVByZWZldGNoLUNvbnRyb2wnLCAnb2ZmJykKICByZXNwb25zZS5oZWFkZXJzLnNldCgnUGVybWlzc2lvbnMtUG9saWN5JywgJ2NhbWVyYT0oKSwgbWljcm9waG9uZT0oKSwgZ2VvbG9jYXRpb249KCksIHBheW1lbnQ9KCknKQogIHJlc3BvbnNlLmhlYWRlcnMuc2V0KCdDcm9zcy1PcmlnaW4tT3BlbmVyLVBvbGljeScsICdzYW1lLW9yaWdpbicpCgogIHJldHVybiByZXNwb25zZQp9CgpmdW5jdGlvbiBjbGVhblN1YmRvbWFpbih2YWx1ZTogc3RyaW5nKSB7CiAgcmV0dXJuIHZhbHVlCiAgICAudG9Mb3dlckNhc2UoKQogICAgLnJlcGxhY2UoL1teYS16MC05XS9nLCAnJykKICAgIC5zbGljZSgwLCA0MikKfQoKZnVuY3Rpb24gZ2V0SG9zdG5hbWUocmVxdWVzdDogTmV4dFJlcXVlc3QpIHsKICBjb25zdCBob3N0ID0gcmVxdWVzdC5oZWFkZXJzLmdldCgnaG9zdCcpIHx8ICcnCiAgcmV0dXJuIGhvc3Quc3BsaXQoJzonKVswXS50b0xvd2VyQ2FzZSgpCn0KCmZ1bmN0aW9uIGdldFBvcnQocmVxdWVzdDogTmV4dFJlcXVlc3QpIHsKICBjb25zdCBob3N0ID0gcmVxdWVzdC5oZWFkZXJzLmdldCgnaG9zdCcpIHx8ICcnCiAgY29uc3QgcGFydHMgPSBob3N0LnNwbGl0KCc6JykKICByZXR1cm4gcGFydHMubGVuZ3RoID4gMSA/IGA6JHtwYXJ0c1sxXX1gIDogJycKfQoKZnVuY3Rpb24gZ2V0VGVuYW50U3ViZG9tYWluKGhvc3RuYW1lOiBzdHJpbmcpIHsKICBpZiAoIWhvc3RuYW1lKSByZXR1cm4gbnVsbAoKICBpZiAoaG9zdG5hbWUgPT09IFJPT1RfRE9NQUlOIHx8IGhvc3RuYW1lID09PSBgd3d3LiR7Uk9PVF9ET01BSU59YCkgewogICAgcmV0dXJuIG51bGwKICB9CgogIGlmIChob3N0bmFtZS5lbmRzV2l0aChgLiR7Uk9PVF9ET01BSU59YCkpIHsKICAgIGNvbnN0IGxlZnQgPSBob3N0bmFtZS5zbGljZSgwLCAtKGAuJHtST09UX0RPTUFJTn1gKS5sZW5ndGgpCiAgICBjb25zdCBmaXJzdCA9IGxlZnQuc3BsaXQoJy4nKVswXQogICAgY29uc3Qgc3ViZG9tYWluID0gY2xlYW5TdWJkb21haW4oZmlyc3QpCgogICAgaWYgKCFzdWJkb21haW4gfHwgUkVTRVJWRURfU1VCRE9NQUlOUy5oYXMoc3ViZG9tYWluKSkgcmV0dXJuIG51bGwKCiAgICByZXR1cm4gc3ViZG9tYWluCiAgfQoKICBpZiAoaG9zdG5hbWUuZW5kc1dpdGgoJy5sb2NhbGhvc3QnKSkgewogICAgY29uc3QgZmlyc3QgPSBob3N0bmFtZS5yZXBsYWNlKCcubG9jYWxob3N0JywgJycpLnNwbGl0KCcuJylbMF0KICAgIGNvbnN0IHN1YmRvbWFpbiA9IGNsZWFuU3ViZG9tYWluKGZpcnN0KQoKICAgIGlmICghc3ViZG9tYWluIHx8IFJFU0VSVkVEX1NVQkRPTUFJTlMuaGFzKHN1YmRvbWFpbikpIHJldHVybiBudWxsCgogICAgcmV0dXJuIHN1YmRvbWFpbgogIH0KCiAgcmV0dXJuIG51bGwKfQoKZnVuY3Rpb24gaXNQdWJsaWNGaWxlKHBhdGhuYW1lOiBzdHJpbmcpIHsKICByZXR1cm4gL1wuKD86cG5nfGpwZ3xqcGVnfGdpZnx3ZWJwfHN2Z3xpY298Y3NzfGpzfHR4dHx4bWx8d2VibWFuaWZlc3R8bWFwKSQvaS50ZXN0KHBhdGhuYW1lKQp9CgpmdW5jdGlvbiBzaG91bGRCeXBhc3MocGF0aG5hbWU6IHN0cmluZykgewogIHJldHVybiAoCiAgICBwYXRobmFtZS5zdGFydHNXaXRoKCcvX25leHQnKSB8fAogICAgcGF0aG5hbWUuc3RhcnRzV2l0aCgnL2FwaScpIHx8CiAgICBwYXRobmFtZS5zdGFydHNXaXRoKCcvZmF2aWNvbicpIHx8CiAgICBpc1B1YmxpY0ZpbGUocGF0aG5hbWUpCiAgKQp9CgpmdW5jdGlvbiBpc1Jvb3REb21haW4oaG9zdG5hbWU6IHN0cmluZykgewogIHJldHVybiBob3N0bmFtZSA9PT0gUk9PVF9ET01BSU4gfHwgaG9zdG5hbWUgPT09IGB3d3cuJHtST09UX0RPTUFJTn1gIHx8IGhvc3RuYW1lID09PSAnbG9jYWxob3N0Jwp9CgpmdW5jdGlvbiByZWRpcmVjdFJvb3RPcmNhbWVudG9Ub1N1YmRvbWFpbihyZXF1ZXN0OiBOZXh0UmVxdWVzdCwgaG9zdG5hbWU6IHN0cmluZykgewogIGNvbnN0IHsgcGF0aG5hbWUgfSA9IHJlcXVlc3QubmV4dFVybAoKICBpZiAoIWlzUm9vdERvbWFpbihob3N0bmFtZSkpIHJldHVybiBudWxsCiAgaWYgKCFwYXRobmFtZS5zdGFydHNXaXRoKCcvb3JjYW1lbnRvLycpKSByZXR1cm4gbnVsbAoKICBjb25zdCByYXdTbHVnID0gcGF0aG5hbWUuc3BsaXQoJy8nKVsyXSB8fCAnJwogIGNvbnN0IHN1YmRvbWFpbiA9IGNsZWFuU3ViZG9tYWluKHJhd1NsdWcpCgogIGlmICghc3ViZG9tYWluIHx8IFJFU0VSVkVEX1NVQkRPTUFJTlMuaGFzKHN1YmRvbWFpbikpIHJldHVybiBudWxsCgogIGNvbnN0IHVybCA9IHJlcXVlc3QubmV4dFVybC5jbG9uZSgpCiAgY29uc3QgcG9ydCA9IGdldFBvcnQocmVxdWVzdCkKCiAgaWYgKGhvc3RuYW1lID09PSAnbG9jYWxob3N0JykgewogICAgdXJsLmhvc3RuYW1lID0gYCR7c3ViZG9tYWlufS5sb2NhbGhvc3RgCiAgICBpZiAocG9ydCkgdXJsLnBvcnQgPSBwb3J0LnJlcGxhY2UoJzonLCAnJykKICAgIHVybC5wYXRobmFtZSA9ICcvJwogICAgcmV0dXJuIGFwcGx5U2VjdXJpdHlIZWFkZXJzKE5leHRSZXNwb25zZS5yZWRpcmVjdCh1cmwpKQogIH0KCiAgdXJsLmhvc3RuYW1lID0gYCR7c3ViZG9tYWlufS4ke1JPT1RfRE9NQUlOfWAKICB1cmwucGF0aG5hbWUgPSAnLycKICByZXR1cm4gYXBwbHlTZWN1cml0eUhlYWRlcnMoTmV4dFJlc3BvbnNlLnJlZGlyZWN0KHVybCkpCn0KCmV4cG9ydCBmdW5jdGlvbiBwcm94eShyZXF1ZXN0OiBOZXh0UmVxdWVzdCkgewogIGNvbnN0IGhvc3RuYW1lID0gZ2V0SG9zdG5hbWUocmVxdWVzdCkKICBjb25zdCBwYXRobmFtZSA9IHJlcXVlc3QubmV4dFVybC5wYXRobmFtZQoKICBjb25zdCByb290UmVkaXJlY3QgPSByZWRpcmVjdFJvb3RPcmNhbWVudG9Ub1N1YmRvbWFpbihyZXF1ZXN0LCBob3N0bmFtZSkKICBpZiAocm9vdFJlZGlyZWN0KSByZXR1cm4gcm9vdFJlZGlyZWN0CgogIGlmIChzaG91bGRCeXBhc3MocGF0aG5hbWUpKSB7CiAgICByZXR1cm4gYXBwbHlTZWN1cml0eUhlYWRlcnMoTmV4dFJlc3BvbnNlLm5leHQoKSkKICB9CgogIGNvbnN0IHRlbmFudFN1YmRvbWFpbiA9IGdldFRlbmFudFN1YmRvbWFpbihob3N0bmFtZSkKCiAgaWYgKCF0ZW5hbnRTdWJkb21haW4pIHsKICAgIHJldHVybiBhcHBseVNlY3VyaXR5SGVhZGVycyhOZXh0UmVzcG9uc2UubmV4dCgpKQogIH0KCiAgaWYgKHBhdGhuYW1lLnN0YXJ0c1dpdGgoJy9vcmNhbWVudG8vJykpIHsKICAgIGNvbnN0IHVybCA9IHJlcXVlc3QubmV4dFVybC5jbG9uZSgpCiAgICB1cmwucGF0aG5hbWUgPSAnLycKICAgIHJldHVybiBhcHBseVNlY3VyaXR5SGVhZGVycyhOZXh0UmVzcG9uc2UucmVkaXJlY3QodXJsKSkKICB9CgogIGNvbnN0IGludGVybmFsUm91dGVzID0gWwogICAgJy9hZG1pbicsCiAgICAnL3BhaW5lbCcsCiAgICAnL2xvZ2luJywKICAgICcvY2FkYXN0cm8nLAogICAgJy9jaGVja291dCcsCiAgICAnL2Fzc2luYXR1cmEnLAogICAgJy9wcm9wb3N0YScsCiAgXQoKICBpZiAoaW50ZXJuYWxSb3V0ZXMuc29tZSgocm91dGUpID0+IHBhdGhuYW1lID09PSByb3V0ZSB8fCBwYXRobmFtZS5zdGFydHNXaXRoKGAke3JvdXRlfS9gKSkpIHsKICAgIHJldHVybiBhcHBseVNlY3VyaXR5SGVhZGVycyhOZXh0UmVzcG9uc2UubmV4dCgpKQogIH0KCiAgY29uc3QgcmV3cml0ZVVybCA9IHJlcXVlc3QubmV4dFVybC5jbG9uZSgpCiAgcmV3cml0ZVVybC5wYXRobmFtZSA9IGAvb3JjYW1lbnRvLyR7dGVuYW50U3ViZG9tYWlufWAKCiAgcmV0dXJuIGFwcGx5U2VjdXJpdHlIZWFkZXJzKE5leHRSZXNwb25zZS5yZXdyaXRlKHJld3JpdGVVcmwpKQp9CgpleHBvcnQgY29uc3QgY29uZmlnID0gewogIG1hdGNoZXI6IFsKICAgICcvKCg/IV9uZXh0L3N0YXRpY3xfbmV4dC9pbWFnZXxmYXZpY29uLmljbykuKiknLAogIF0sCn0K
"@

Write-Base64File "lib\domain.ts" @"
ZXhwb3J0IGNvbnN0IFJPT1RfRE9NQUlOID0gcHJvY2Vzcy5lbnYuTkVYVF9QVUJMSUNfUk9PVF9ET01BSU4gfHwgJ29yY2FseS5jb20uYnInCgpleHBvcnQgZnVuY3Rpb24gY3JpYXJTdWJkb21pbmlvU2VndXJvKHZhbG9yOiBzdHJpbmcpIHsKICByZXR1cm4gdmFsb3IKICAgIC5ub3JtYWxpemUoJ05GRCcpCiAgICAucmVwbGFjZSgvW1x1MDMwMC1cdTAzNmZdL2csICcnKQogICAgLnRvTG93ZXJDYXNlKCkKICAgIC5yZXBsYWNlKC9bXmEtejAtOV0vZywgJycpCiAgICAuc2xpY2UoMCwgNDIpCn0KCmV4cG9ydCBmdW5jdGlvbiBtb250YXJEb21pbmlvRW1wcmVzYShzbHVnT3VTdWJkb21pbmlvOiBzdHJpbmcpIHsKICBjb25zdCBzdWJkb21haW4gPSBjcmlhclN1YmRvbWluaW9TZWd1cm8oc2x1Z091U3ViZG9taW5pbykKCiAgaWYgKCFzdWJkb21haW4pIHJldHVybiBST09UX0RPTUFJTgoKICByZXR1cm4gYCR7c3ViZG9tYWlufS4ke1JPT1RfRE9NQUlOfWAKfQoKZXhwb3J0IGZ1bmN0aW9uIG1vbnRhclVybEVtcHJlc2Eoc2x1Z091U3ViZG9taW5pbzogc3RyaW5nLCBwYXRoID0gJy8nKSB7CiAgY29uc3QgZG9taW5pbyA9IG1vbnRhckRvbWluaW9FbXByZXNhKHNsdWdPdVN1YmRvbWluaW8pCiAgY29uc3QgcGF0aG5hbWUgPSBwYXRoLnN0YXJ0c1dpdGgoJy8nKSA/IHBhdGggOiBgLyR7cGF0aH1gCgogIHJldHVybiBgaHR0cHM6Ly8ke2RvbWluaW99JHtwYXRobmFtZX1gCn0K
"@

# Next 16 recomenda proxy.ts. Se existir middleware.ts, faz backup e remove para acabar com o aviso.
if (Test-Path "middleware.ts") {
  Copy-Item "middleware.ts" "middleware.backup-before-proxy.ts" -Force
  Remove-Item "middleware.ts" -Force
  Write-Host "middleware.ts removido e salvo como middleware.backup-before-proxy.ts" -ForegroundColor Yellow
}

# Ajusta app/orcamento/[slug]/page.tsx para aceitar slug OU subdomain_slug.
$loja = Join-Path $project "app\orcamento\[slug]\page.tsx"

if (Test-Path $loja) {
  $content = [System.IO.File]::ReadAllText($loja)

  # Troca busca exata por slug para aceitar subdomain_slug também.
  $content = $content.Replace(".eq('slug', slug)", '.or(`slug.eq.${slug},subdomain_slug.eq.${slug}`)')

  [System.IO.File]::WriteAllText($loja, $content, $utf8NoBom)
  Write-Host "Loja publica ajustada para slug e subdomain_slug." -ForegroundColor Green
} else {
  Write-Host "Nao encontrei app\orcamento\[slug]\page.tsx" -ForegroundColor Yellow
}

# Garante .env.example com domínio raiz sem expor segredo.
$envExample = Join-Path $project ".env.example"
if (!(Test-Path $envExample)) {
  [System.IO.File]::WriteAllText($envExample, "", $utf8NoBom)
}

$envContent = [System.IO.File]::ReadAllText($envExample)

if ($envContent -notmatch "NEXT_PUBLIC_ROOT_DOMAIN") {
  Add-Content -Path $envExample -Value "NEXT_PUBLIC_ROOT_DOMAIN=orcaly.com.br"
}

Remove-Item -Recurse -Force ".next" -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "Subdominio por empresa instalado sem mexer no cadastro." -ForegroundColor Green
Write-Host "Exemplo: graficaflash.orcaly.com.br" -ForegroundColor Cyan
Write-Host "Agora rode: npm run build" -ForegroundColor Yellow
