param(
  [switch]$SkipBuild
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$Root = (Get-Location).Path
$Target = Join-Path $Root "app\api\mercado-pago\webhook\route.ts"
$SubscriptionModule = Join-Path $Root "lib\payments\subscription\mercado-pago.ts"
$Stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$Backup = Join-Path $Root ".orcaly-backups\reescrever-webhook-assinatura-$Stamp\route.ts"
$Utf8 = New-Object System.Text.UTF8Encoding($false)

if (-not (Test-Path -LiteralPath (Join-Path $Root "package.json"))) {
  throw "Execute este script na raiz do projeto Orcaly."
}

$Branch = (& git branch --show-current 2>$null | Out-String).Trim()

if ($Branch -ne "feature/asaas-sandbox") {
  throw "Branch atual: $Branch. Execute na branch feature/asaas-sandbox."
}

if (-not (Test-Path -LiteralPath $Target)) {
  throw "Arquivo nao encontrado: app/api/mercado-pago/webhook/route.ts"
}

if (-not (Test-Path -LiteralPath $SubscriptionModule)) {
  throw "O modulo isolado da assinatura nao existe. Nao execute este script antes do isolamento."
}

New-Item -ItemType Directory -Force -Path (Split-Path $Backup -Parent) | Out-Null
Copy-Item -LiteralPath $Target -Destination $Backup -Force

Write-Host ""
Write-Host "==================================================" -ForegroundColor Cyan
Write-Host "ORCALY - REVISAO COMPLETA DO WEBHOOK" -ForegroundColor Cyan
Write-Host "Assinatura Mercado Pago totalmente tipada" -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan

$RouteCode = [Text.Encoding]::UTF8.GetString(
  [Convert]::FromBase64String("aW1wb3J0IHsgTmV4dFJlcXVlc3QsIE5leHRSZXNwb25zZSB9IGZyb20gIm5leHQvc2VydmVyIjsKaW1wb3J0IHsKICBhcHBseUFwcHJvdmVkU3Vic2NyaXB0aW9uUGF5bWVudCwKICBmaW5kQ29tcGFueUZvclByb3ZpZGVyUmVmZXJlbmNlLAogIGdldFN1cGFiYXNlQWRtaW4sCiAgbWVyY2Fkb1BhZ29QbGF0Zm9ybVJlcXVlc3QsCiAgcGFyc2VPcmNhbHlTdWJzY3JpcHRpb25SZWZlcmVuY2UsCiAgcmVjb3JkU3Vic2NyaXB0aW9uRXZlbnQsCn0gZnJvbSAiQC9saWIvc3Vic2NyaXB0aW9uLXNlcnZpY2UiOwppbXBvcnQgewogIGdldFN1YnNjcmlwdGlvbldlYmhvb2tTZWNyZXQsCn0gZnJvbSAiQC9saWIvcGF5bWVudHMvc3Vic2NyaXB0aW9uL21lcmNhZG8tcGFnbyI7CmltcG9ydCB7CiAgdmVyaWZ5TWVyY2Fkb1BhZ29XZWJob29rU2lnbmF0dXJlLAp9IGZyb20gIkAvbGliL21lcmNhZG8tcGFnbyI7Cgp0eXBlIEpzb25SZWNvcmQgPSBSZWNvcmQ8c3RyaW5nLCB1bmtub3duPjsKCmZ1bmN0aW9uIHRleHQodmFsdWU6IHVua25vd24pIHsKICByZXR1cm4gU3RyaW5nKHZhbHVlIHx8ICIiKS50cmltKCk7Cn0KCmZ1bmN0aW9uIHJlY29yZCh2YWx1ZTogdW5rbm93bik6IEpzb25SZWNvcmQgewogIGlmICghdmFsdWUgfHwgdHlwZW9mIHZhbHVlICE9PSAib2JqZWN0IiB8fCBBcnJheS5pc0FycmF5KHZhbHVlKSkgewogICAgcmV0dXJuIHt9OwogIH0KCiAgcmV0dXJuIHZhbHVlIGFzIEpzb25SZWNvcmQ7Cn0KCmZ1bmN0aW9uIHBvc2l0aXZlTnVtYmVyT3JOdWxsKHZhbHVlOiB1bmtub3duKSB7CiAgY29uc3QgcGFyc2VkID0gTnVtYmVyKHZhbHVlIHx8IDApOwoKICByZXR1cm4gTnVtYmVyLmlzRmluaXRlKHBhcnNlZCkgJiYgcGFyc2VkID4gMAogICAgPyBwYXJzZWQKICAgIDogbnVsbDsKfQoKZnVuY3Rpb24gZXh0cmFjdFJlc291cmNlSWQoYm9keTogSnNvblJlY29yZCwgdXJsOiBVUkwpIHsKICBjb25zdCBkYXRhID0gcmVjb3JkKGJvZHkuZGF0YSk7CgogIHJldHVybiB0ZXh0KAogICAgZGF0YS5pZCB8fAogICAgICBib2R5LmlkIHx8CiAgICAgIGJvZHkucmVzb3VyY2UgfHwKICAgICAgdXJsLnNlYXJjaFBhcmFtcy5nZXQoImRhdGEuaWQiKSB8fAogICAgICB1cmwuc2VhcmNoUGFyYW1zLmdldCgiaWQiKSB8fAogICAgICB1cmwuc2VhcmNoUGFyYW1zLmdldCgicHJlYXBwcm92YWxfaWQiKSwKICApOwp9CgpmdW5jdGlvbiBleHRyYWN0VG9waWMoYm9keTogSnNvblJlY29yZCwgdXJsOiBVUkwpIHsKICByZXR1cm4gdGV4dCgKICAgIGJvZHkudHlwZSB8fAogICAgICBib2R5LnRvcGljIHx8CiAgICAgIHVybC5zZWFyY2hQYXJhbXMuZ2V0KCJ0eXBlIikgfHwKICAgICAgdXJsLnNlYXJjaFBhcmFtcy5nZXQoInRvcGljIiksCiAgKS50b0xvd2VyQ2FzZSgpOwp9CgpmdW5jdGlvbiB2YWxpZFdlYmhvb2tTaWduYXR1cmUoCiAgcmVxdWVzdDogTmV4dFJlcXVlc3QsCiAgcmVzb3VyY2VJZDogc3RyaW5nLAopIHsKICByZXR1cm4gdmVyaWZ5TWVyY2Fkb1BhZ29XZWJob29rU2lnbmF0dXJlKHsKICAgIHhTaWduYXR1cmU6IHJlcXVlc3QuaGVhZGVycy5nZXQoIngtc2lnbmF0dXJlIiksCiAgICB4UmVxdWVzdElkOiByZXF1ZXN0LmhlYWRlcnMuZ2V0KCJ4LXJlcXVlc3QtaWQiKSwKICAgIGRhdGFJZDogcmVzb3VyY2VJZCB8fCBudWxsLAogICAgc2VjcmV0OiBnZXRTdWJzY3JpcHRpb25XZWJob29rU2VjcmV0KCksCiAgfSk7Cn0KCmFzeW5jIGZ1bmN0aW9uIHByb2Nlc3NQcmVhcHByb3ZhbChyZXNvdXJjZUlkOiBzdHJpbmcpIHsKICBjb25zdCBhZG1pbiA9IGdldFN1cGFiYXNlQWRtaW4oKTsKICBjb25zdCBzdWJzY3JpcHRpb24gPSByZWNvcmQoCiAgICBhd2FpdCBtZXJjYWRvUGFnb1BsYXRmb3JtUmVxdWVzdCgKICAgICAgYC9wcmVhcHByb3ZhbC8ke2VuY29kZVVSSUNvbXBvbmVudChyZXNvdXJjZUlkKX1gLAogICAgKSwKICApOwogIGNvbnN0IHN1YnNjcmlwdGlvbklkID0KICAgIHRleHQoc3Vic2NyaXB0aW9uLmlkKSB8fCByZXNvdXJjZUlkOwogIGNvbnN0IGZvdW5kID0gYXdhaXQgZmluZENvbXBhbnlGb3JQcm92aWRlclJlZmVyZW5jZSgKICAgIGFkbWluLAogICAgc3Vic2NyaXB0aW9uLmV4dGVybmFsX3JlZmVyZW5jZSwKICAgIHN1YnNjcmlwdGlvbklkLAogICk7CgogIGlmICghZm91bmQuY29tcGFueT8uaWQpIHsKICAgIHJldHVybiB7CiAgICAgIHJlY2VpdmVkOiB0cnVlLAogICAgICBpZ25vcmVkOiB0cnVlLAogICAgICByZWFzb246ICJBc3NpbmF0dXJhIHNlbSBlbXByZXNhIHZpbmN1bGFkYS4iLAogICAgfTsKICB9CgogIGNvbnN0IGNvbXBhbnkgPSBmb3VuZC5jb21wYW55OwogIGNvbnN0IHJlbW90ZVN0YXR1cyA9ICgKICAgIHRleHQoc3Vic2NyaXB0aW9uLnN0YXR1cykgfHwgInBlbmRpbmciCiAgKS50b0xvd2VyQ2FzZSgpOwogIGNvbnN0IG5vdyA9IG5ldyBEYXRlKCk7CiAgY29uc3QgYWNjZXNzVW50aWwgPQogICAgY29tcGFueS5hY2Nlc3NfdW50aWwgfHwKICAgIGNvbXBhbnkuYXNzaW5hdHVyYV9leHBpcmFfZW0gfHwKICAgIG51bGw7CiAgY29uc3QgaGFzRnV0dXJlQWNjZXNzID0gYWNjZXNzVW50aWwKICAgID8gbmV3IERhdGUoYWNjZXNzVW50aWwpID4gbm93CiAgICA6IGZhbHNlOwogIGxldCBpbnRlcm5hbFN0YXR1cyA9CiAgICBjb21wYW55LmFzc2luYXR1cmFfc3RhdHVzIHx8ICJwZW5kZW50ZSI7CgogIGlmICgKICAgIGNvbXBhbnkudHJpYWxfZW5kc19hdCAmJgogICAgbmV3IERhdGUoY29tcGFueS50cmlhbF9lbmRzX2F0KSA+IG5vdwogICkgewogICAgaW50ZXJuYWxTdGF0dXMgPSAidHJpYWxpbmciOwogIH0gZWxzZSBpZiAoCiAgICBjb21wYW55LmNhbmNlbF9hdF9wZXJpb2RfZW5kICYmCiAgICBoYXNGdXR1cmVBY2Nlc3MKICApIHsKICAgIGludGVybmFsU3RhdHVzID0gImNhbmNlbF9hdF9wZXJpb2RfZW5kIjsKICB9IGVsc2UgaWYgKHJlbW90ZVN0YXR1cyA9PT0gImF1dGhvcml6ZWQiKSB7CiAgICBpbnRlcm5hbFN0YXR1cyA9ICJhdGl2YSI7CiAgfSBlbHNlIGlmICgKICAgIFsiY2FuY2VsZWQiLCAiY2FuY2VsbGVkIl0uaW5jbHVkZXMocmVtb3RlU3RhdHVzKQogICkgewogICAgaW50ZXJuYWxTdGF0dXMgPSBoYXNGdXR1cmVBY2Nlc3MKICAgICAgPyAiY2FuY2VsX2F0X3BlcmlvZF9lbmQiCiAgICAgIDogImNhbmNlbGFkYSI7CiAgfSBlbHNlIGlmIChyZW1vdGVTdGF0dXMgPT09ICJwYXVzZWQiKSB7CiAgICBpbnRlcm5hbFN0YXR1cyA9ICJwYXN0X2R1ZSI7CiAgfSBlbHNlIGlmICgKICAgIHJlbW90ZVN0YXR1cyA9PT0gInBlbmRpbmciICYmCiAgICAhaGFzRnV0dXJlQWNjZXNzCiAgKSB7CiAgICBpbnRlcm5hbFN0YXR1cyA9ICJwZW5kZW50ZSI7CiAgfQoKICBjb25zdCBjaGVja291dFVybCA9CiAgICB0ZXh0KHN1YnNjcmlwdGlvbi5pbml0X3BvaW50KSB8fAogICAgdGV4dChzdWJzY3JpcHRpb24uc2FuZGJveF9pbml0X3BvaW50KSB8fAogICAgdGV4dChjb21wYW55LmFzc2luYXR1cmFfY2hlY2tvdXRfdXJsKSB8fAogICAgbnVsbDsKICBjb25zdCBuZXh0UGF5bWVudERhdGUgPQogICAgdGV4dChzdWJzY3JpcHRpb24ubmV4dF9wYXltZW50X2RhdGUpIHx8IG51bGw7CiAgY29uc3QgcGF5ZXJFbWFpbCA9CiAgICB0ZXh0KHN1YnNjcmlwdGlvbi5wYXllcl9lbWFpbCkgfHwKICAgIHRleHQoY29tcGFueS5tZXJjYWRvX3BhZ29fY3VzdG9tZXJfZW1haWwpIHx8CiAgICBudWxsOwoKICBhd2FpdCBhZG1pbgogICAgLmZyb20oImNvbXBhbmllcyIpCiAgICAudXBkYXRlKHsKICAgICAgYXNzaW5hdHVyYV9zdGF0dXM6IGludGVybmFsU3RhdHVzLAogICAgICBhc3NpbmF0dXJhX2F1dG9fcmVjb3JyZW50ZToKICAgICAgICByZW1vdGVTdGF0dXMgPT09ICJhdXRob3JpemVkIiAmJgogICAgICAgICFjb21wYW55LmNhbmNlbF9hdF9wZXJpb2RfZW5kLAogICAgICBhc3NpbmF0dXJhX2NoZWNrb3V0X3VybDogY2hlY2tvdXRVcmwsCiAgICAgIGFzc2luYXR1cmFfcHJveGltYV9jb2JyYW5jYTogbmV4dFBheW1lbnREYXRlLAogICAgICBtZXJjYWRvX3BhZ29fc3Vic2NyaXB0aW9uX2lkOiBzdWJzY3JpcHRpb25JZCwKICAgICAgbWVyY2Fkb19wYWdvX3N1YnNjcmlwdGlvbl9zdGF0dXM6IHJlbW90ZVN0YXR1cywKICAgICAgbWVyY2Fkb19wYWdvX2N1c3RvbWVyX2VtYWlsOiBwYXllckVtYWlsLAogICAgICBhc3NpbmF0dXJhX21wX3BheWxvYWQ6IHN1YnNjcmlwdGlvbiwKICAgICAgdXBkYXRlZF9hdDogbm93LnRvSVNPU3RyaW5nKCksCiAgICB9KQogICAgLmVxKCJpZCIsIGNvbXBhbnkuaWQpOwoKICBhd2FpdCByZWNvcmRTdWJzY3JpcHRpb25FdmVudChhZG1pbiwgewogICAgY29tcGFueUlkOiBTdHJpbmcoY29tcGFueS5pZCksCiAgICBldmVudFR5cGU6ICJzdWJzY3JpcHRpb25fc3RhdHVzX3VwZGF0ZWQiLAogICAgb2xkU3RhdHVzOgogICAgICBjb21wYW55LmFzc2luYXR1cmFfc3RhdHVzIHx8IG51bGwsCiAgICBuZXdTdGF0dXM6IGludGVybmFsU3RhdHVzLAogICAgcHJvdmlkZXJSZWZlcmVuY2U6CiAgICAgIGAke3N1YnNjcmlwdGlvbklkfToke3JlbW90ZVN0YXR1c31gLAogICAgbWV0YWRhdGE6IHsKICAgICAgcHJvdmlkZXJfc3RhdHVzOiByZW1vdGVTdGF0dXMsCiAgICB9LAogIH0pOwoKICByZXR1cm4gewogICAgcmVjZWl2ZWQ6IHRydWUsCiAgICBraW5kOiAic3Vic2NyaXB0aW9uX3ByZWFwcHJvdmFsIiwKICAgIHN0YXR1czogcmVtb3RlU3RhdHVzLAogIH07Cn0KCmFzeW5jIGZ1bmN0aW9uIHByb2Nlc3NBdXRob3JpemVkUGF5bWVudCgKICByZXNvdXJjZUlkOiBzdHJpbmcsCikgewogIGNvbnN0IGFkbWluID0gZ2V0U3VwYWJhc2VBZG1pbigpOwogIGNvbnN0IGF1dGhvcml6ZWRQYXltZW50ID0gcmVjb3JkKAogICAgYXdhaXQgbWVyY2Fkb1BhZ29QbGF0Zm9ybVJlcXVlc3QoCiAgICAgIGAvYXV0aG9yaXplZF9wYXltZW50cy8ke2VuY29kZVVSSUNvbXBvbmVudCgKICAgICAgICByZXNvdXJjZUlkLAogICAgICApfWAsCiAgICApLAogICk7CiAgY29uc3QgcGF5bWVudCA9IHJlY29yZChhdXRob3JpemVkUGF5bWVudC5wYXltZW50KTsKICBjb25zdCBwcmVhcHByb3ZhbElkID0KICAgIHRleHQoYXV0aG9yaXplZFBheW1lbnQucHJlYXBwcm92YWxfaWQpIHx8IG51bGw7CiAgY29uc3Qgc3Vic2NyaXB0aW9uID0gcHJlYXBwcm92YWxJZAogICAgPyByZWNvcmQoCiAgICAgICAgYXdhaXQgbWVyY2Fkb1BhZ29QbGF0Zm9ybVJlcXVlc3QoCiAgICAgICAgICBgL3ByZWFwcHJvdmFsLyR7ZW5jb2RlVVJJQ29tcG9uZW50KAogICAgICAgICAgICBwcmVhcHByb3ZhbElkLAogICAgICAgICAgKX1gLAogICAgICAgICksCiAgICAgICkKICAgIDogbnVsbDsKICBjb25zdCByZWZlcmVuY2UgPQogICAgdGV4dChhdXRob3JpemVkUGF5bWVudC5leHRlcm5hbF9yZWZlcmVuY2UpIHx8CiAgICB0ZXh0KHN1YnNjcmlwdGlvbj8uZXh0ZXJuYWxfcmVmZXJlbmNlKSB8fAogICAgbnVsbDsKICBjb25zdCBmb3VuZCA9IGF3YWl0IGZpbmRDb21wYW55Rm9yUHJvdmlkZXJSZWZlcmVuY2UoCiAgICBhZG1pbiwKICAgIHJlZmVyZW5jZSwKICAgIHByZWFwcHJvdmFsSWQsCiAgKTsKCiAgaWYgKCFmb3VuZC5jb21wYW55Py5pZCkgewogICAgcmV0dXJuIHsKICAgICAgcmVjZWl2ZWQ6IHRydWUsCiAgICAgIGlnbm9yZWQ6IHRydWUsCiAgICAgIHJlYXNvbjoKICAgICAgICAiUGFnYW1lbnRvIHJlY29ycmVudGUgc2VtIGVtcHJlc2EgdmluY3VsYWRhLiIsCiAgICB9OwogIH0KCiAgY29uc3QgcGF5bWVudFN0YXR1cyA9ICgKICAgIHRleHQocGF5bWVudC5zdGF0dXMpIHx8CiAgICB0ZXh0KGF1dGhvcml6ZWRQYXltZW50LnN0YXR1cykgfHwKICAgICJwZW5kaW5nIgogICkudG9Mb3dlckNhc2UoKTsKICBjb25zdCBwcm92aWRlclJlZmVyZW5jZSA9CiAgICB0ZXh0KHBheW1lbnQuaWQpIHx8IHJlc291cmNlSWQ7CiAgY29uc3QgbmV4dFBheW1lbnREYXRlID0KICAgIHRleHQoc3Vic2NyaXB0aW9uPy5uZXh0X3BheW1lbnRfZGF0ZSkgfHwgbnVsbDsKCiAgaWYgKHBheW1lbnRTdGF0dXMgPT09ICJhcHByb3ZlZCIpIHsKICAgIGF3YWl0IGFwcGx5QXBwcm92ZWRTdWJzY3JpcHRpb25QYXltZW50KAogICAgICBhZG1pbiwKICAgICAgZm91bmQuY29tcGFueSwKICAgICAgewogICAgICAgIHBsYW46IGZvdW5kLnBhcnNlZD8ucGxhbiwKICAgICAgICBwcm92aWRlclJlZmVyZW5jZSwKICAgICAgICBwcmVhcHByb3ZhbElkLAogICAgICAgIG5leHRQYXltZW50RGF0ZSwKICAgICAgICBwYXltZW50VHlwZTogImNhcmRfcmVjdXJyaW5nIiwKICAgICAgICBhbW91bnQ6IHBvc2l0aXZlTnVtYmVyT3JOdWxsKAogICAgICAgICAgcGF5bWVudC50cmFuc2FjdGlvbl9hbW91bnQsCiAgICAgICAgKSwKICAgICAgfSwKICAgICk7CiAgfSBlbHNlIHsKICAgIGF3YWl0IHJlY29yZFN1YnNjcmlwdGlvbkV2ZW50KGFkbWluLCB7CiAgICAgIGNvbXBhbnlJZDogU3RyaW5nKGZvdW5kLmNvbXBhbnkuaWQpLAogICAgICBldmVudFR5cGU6ICJwYXltZW50X3BlbmRpbmciLAogICAgICBvbGRTdGF0dXM6CiAgICAgICAgZm91bmQuY29tcGFueS5hc3NpbmF0dXJhX3N0YXR1cyB8fCBudWxsLAogICAgICBuZXdTdGF0dXM6CiAgICAgICAgZm91bmQuY29tcGFueS5hc3NpbmF0dXJhX3N0YXR1cyB8fCBudWxsLAogICAgICBwcm92aWRlclJlZmVyZW5jZSwKICAgICAgbWV0YWRhdGE6IHsKICAgICAgICBwcm92aWRlcl9zdGF0dXM6IHBheW1lbnRTdGF0dXMsCiAgICAgIH0sCiAgICB9KTsKICB9CgogIHJldHVybiB7CiAgICByZWNlaXZlZDogdHJ1ZSwKICAgIGtpbmQ6ICJzdWJzY3JpcHRpb25fYXV0aG9yaXplZF9wYXltZW50IiwKICAgIHN0YXR1czogcGF5bWVudFN0YXR1cywKICB9Owp9Cgphc3luYyBmdW5jdGlvbiBwcm9jZXNzUGF5bWVudCgKICByZXNvdXJjZUlkOiBzdHJpbmcsCiAgYm9keTogSnNvblJlY29yZCwKKSB7CiAgY29uc3QgYWRtaW4gPSBnZXRTdXBhYmFzZUFkbWluKCk7CiAgY29uc3QgcGF5bWVudCA9IHJlY29yZCgKICAgIGF3YWl0IG1lcmNhZG9QYWdvUGxhdGZvcm1SZXF1ZXN0KAogICAgICBgL3YxL3BheW1lbnRzLyR7ZW5jb2RlVVJJQ29tcG9uZW50KHJlc291cmNlSWQpfWAsCiAgICApLAogICk7CiAgY29uc3QgcmVmZXJlbmNlID0KICAgIHRleHQocGF5bWVudC5leHRlcm5hbF9yZWZlcmVuY2UpIHx8IG51bGw7CiAgY29uc3QgcGFyc2VkID0KICAgIHBhcnNlT3JjYWx5U3Vic2NyaXB0aW9uUmVmZXJlbmNlKHJlZmVyZW5jZSk7CgogIGlmICgKICAgICFwYXJzZWQgJiYKICAgIHRleHQocmVmZXJlbmNlKS5zdGFydHNXaXRoKCJvcmNhbHlfbWFya2V0cGxhY2UiKQogICkgewogICAgcmV0dXJuIHsKICAgICAgcmVjZWl2ZWQ6IHRydWUsCiAgICAgIGlnbm9yZWQ6IHRydWUsCiAgICAgIHJlYXNvbjogIldlYmhvb2sgcGVydGVuY2VudGUgYW8gbWFya2V0cGxhY2UuIiwKICAgIH07CiAgfQoKICBjb25zdCBmb3VuZCA9IGF3YWl0IGZpbmRDb21wYW55Rm9yUHJvdmlkZXJSZWZlcmVuY2UoCiAgICBhZG1pbiwKICAgIHJlZmVyZW5jZSwKICAgIG51bGwsCiAgKTsKCiAgaWYgKCFmb3VuZC5jb21wYW55Py5pZCkgewogICAgcmV0dXJuIHsKICAgICAgcmVjZWl2ZWQ6IHRydWUsCiAgICAgIGlnbm9yZWQ6IHRydWUsCiAgICAgIHJlYXNvbjoKICAgICAgICAiUGFnYW1lbnRvIHNlbSBhc3NpbmF0dXJhIE9yw6dhbHkgdmluY3VsYWRhLiIsCiAgICB9OwogIH0KCiAgY29uc3Qgc3RhdHVzID0gKAogICAgdGV4dChwYXltZW50LnN0YXR1cykgfHwgInBlbmRpbmciCiAgKS50b0xvd2VyQ2FzZSgpOwogIGNvbnN0IHBheW1lbnRSb3dJZCA9CiAgICBwYXJzZWQ/LnBheW1lbnRSb3dJZCB8fAogICAgKHJlZmVyZW5jZSAmJiAvXlswLTlhLWYtXXszNn0kL2kudGVzdChyZWZlcmVuY2UpCiAgICAgID8gcmVmZXJlbmNlCiAgICAgIDogbnVsbCk7CiAgY29uc3QgcHJvdmlkZXJSZWZlcmVuY2UgPQogICAgdGV4dChwYXltZW50LmlkKSB8fCByZXNvdXJjZUlkOwoKICBpZiAocGF5bWVudFJvd0lkKSB7CiAgICBhd2FpdCBhZG1pbgogICAgICAuZnJvbSgicGxhbl9wYXltZW50cyIpCiAgICAgIC51cGRhdGUoewogICAgICAgIHN0YXR1cywKICAgICAgICBtZXJjYWRvX3BhZ29fcGF5bWVudF9pZDoKICAgICAgICAgIHByb3ZpZGVyUmVmZXJlbmNlLAogICAgICAgIHBheW1lbnRfbWV0aG9kOgogICAgICAgICAgdGV4dChwYXltZW50LnBheW1lbnRfbWV0aG9kX2lkKSB8fCAicGl4IiwKICAgICAgICByYXdfd2ViaG9vazogYm9keSwKICAgICAgICByYXdfcGF5bWVudDogcGF5bWVudCwKICAgICAgICBwYWlkX2F0OgogICAgICAgICAgc3RhdHVzID09PSAiYXBwcm92ZWQiCiAgICAgICAgICAgID8gbmV3IERhdGUoKS50b0lTT1N0cmluZygpCiAgICAgICAgICAgIDogbnVsbCwKICAgICAgICB1cGRhdGVkX2F0OiBuZXcgRGF0ZSgpLnRvSVNPU3RyaW5nKCksCiAgICAgIH0pCiAgICAgIC5lcSgiaWQiLCBwYXltZW50Um93SWQpOwogIH0KCiAgaWYgKHN0YXR1cyA9PT0gImFwcHJvdmVkIikgewogICAgYXdhaXQgYXBwbHlBcHByb3ZlZFN1YnNjcmlwdGlvblBheW1lbnQoCiAgICAgIGFkbWluLAogICAgICBmb3VuZC5jb21wYW55LAogICAgICB7CiAgICAgICAgcGxhbjogcGFyc2VkPy5wbGFuLAogICAgICAgIHByb3ZpZGVyUmVmZXJlbmNlLAogICAgICAgIHBheW1lbnRUeXBlOiAicGl4IiwKICAgICAgICBhbW91bnQ6IHBvc2l0aXZlTnVtYmVyT3JOdWxsKAogICAgICAgICAgcGF5bWVudC50cmFuc2FjdGlvbl9hbW91bnQsCiAgICAgICAgKSwKICAgICAgfSwKICAgICk7CiAgfSBlbHNlIHsKICAgIGF3YWl0IHJlY29yZFN1YnNjcmlwdGlvbkV2ZW50KGFkbWluLCB7CiAgICAgIGNvbXBhbnlJZDogU3RyaW5nKGZvdW5kLmNvbXBhbnkuaWQpLAogICAgICBldmVudFR5cGU6CiAgICAgICAgc3RhdHVzID09PSAicmVqZWN0ZWQiCiAgICAgICAgICA/ICJwYXltZW50X2ZhaWxlZCIKICAgICAgICAgIDogInBheW1lbnRfcGVuZGluZyIsCiAgICAgIG9sZFN0YXR1czoKICAgICAgICBmb3VuZC5jb21wYW55LmFzc2luYXR1cmFfc3RhdHVzIHx8IG51bGwsCiAgICAgIG5ld1N0YXR1czoKICAgICAgICBmb3VuZC5jb21wYW55LmFzc2luYXR1cmFfc3RhdHVzIHx8IG51bGwsCiAgICAgIHByb3ZpZGVyUmVmZXJlbmNlLAogICAgICBtZXRhZGF0YTogewogICAgICAgIHByb3ZpZGVyX3N0YXR1czogc3RhdHVzLAogICAgICAgIHBheW1lbnRfdHlwZTogInBpeCIsCiAgICAgIH0sCiAgICB9KTsKICB9CgogIHJldHVybiB7CiAgICByZWNlaXZlZDogdHJ1ZSwKICAgIGtpbmQ6ICJzdWJzY3JpcHRpb25fcGl4X3BheW1lbnQiLAogICAgc3RhdHVzLAogIH07Cn0KCmV4cG9ydCBhc3luYyBmdW5jdGlvbiBQT1NUKHJlcXVlc3Q6IE5leHRSZXF1ZXN0KSB7CiAgdHJ5IHsKICAgIGNvbnN0IHVybCA9IG5ldyBVUkwocmVxdWVzdC51cmwpOwogICAgY29uc3QgYm9keSA9IHJlY29yZCgKICAgICAgYXdhaXQgcmVxdWVzdC5qc29uKCkuY2F0Y2goKCkgPT4gKHt9KSksCiAgICApOwogICAgY29uc3QgdG9waWMgPSBleHRyYWN0VG9waWMoYm9keSwgdXJsKTsKICAgIGNvbnN0IHJlc291cmNlSWQgPSBleHRyYWN0UmVzb3VyY2VJZChib2R5LCB1cmwpOwoKICAgIGlmICghcmVzb3VyY2VJZCkgewogICAgICByZXR1cm4gTmV4dFJlc3BvbnNlLmpzb24oewogICAgICAgIHJlY2VpdmVkOiB0cnVlLAogICAgICAgIGlnbm9yZWQ6IHRydWUsCiAgICAgICAgcmVhc29uOiAiUmVjdXJzbyBhdXNlbnRlLiIsCiAgICAgIH0pOwogICAgfQoKICAgIGlmICgKICAgICAgIXZhbGlkV2ViaG9va1NpZ25hdHVyZShyZXF1ZXN0LCByZXNvdXJjZUlkKQogICAgKSB7CiAgICAgIHJldHVybiBOZXh0UmVzcG9uc2UuanNvbigKICAgICAgICB7IGVycm9yOiAiQXNzaW5hdHVyYSBpbnbDoWxpZGEuIiB9LAogICAgICAgIHsgc3RhdHVzOiA0MDEgfSwKICAgICAgKTsKICAgIH0KCiAgICBpZiAoCiAgICAgIHRvcGljLmluY2x1ZGVzKAogICAgICAgICJzdWJzY3JpcHRpb25fcHJlYXBwcm92YWwiLAogICAgICApCiAgICApIHsKICAgICAgcmV0dXJuIE5leHRSZXNwb25zZS5qc29uKAogICAgICAgIGF3YWl0IHByb2Nlc3NQcmVhcHByb3ZhbChyZXNvdXJjZUlkKSwKICAgICAgKTsKICAgIH0KCiAgICBpZiAoCiAgICAgIHRvcGljLmluY2x1ZGVzKAogICAgICAgICJzdWJzY3JpcHRpb25fYXV0aG9yaXplZF9wYXltZW50IiwKICAgICAgKQogICAgKSB7CiAgICAgIHJldHVybiBOZXh0UmVzcG9uc2UuanNvbigKICAgICAgICBhd2FpdCBwcm9jZXNzQXV0aG9yaXplZFBheW1lbnQocmVzb3VyY2VJZCksCiAgICAgICk7CiAgICB9CgogICAgcmV0dXJuIE5leHRSZXNwb25zZS5qc29uKAogICAgICBhd2FpdCBwcm9jZXNzUGF5bWVudChyZXNvdXJjZUlkLCBib2R5KSwKICAgICk7CiAgfSBjYXRjaCAoZXJyb3IpIHsKICAgIGNvbnN0IG1lc3NhZ2UgPQogICAgICBlcnJvciBpbnN0YW5jZW9mIEVycm9yCiAgICAgICAgPyBlcnJvci5tZXNzYWdlCiAgICAgICAgOiAiRXJybyBubyB3ZWJob29rIGRlIGFzc2luYXR1cmEuIjsKCiAgICBjb25zb2xlLmVycm9yKAogICAgICAib3JjYWx5X3N1YnNjcmlwdGlvbl93ZWJob29rX2Vycm9yIiwKICAgICAgbWVzc2FnZSwKICAgICk7CgogICAgcmV0dXJuIE5leHRSZXNwb25zZS5qc29uKAogICAgICB7CiAgICAgICAgZXJyb3I6CiAgICAgICAgICAiTsOjbyBmb2kgcG9zc8OtdmVsIHByb2Nlc3NhciBvIHdlYmhvb2suIiwKICAgICAgfSwKICAgICAgeyBzdGF0dXM6IDUwMCB9LAogICAgKTsKICB9Cn0KCmV4cG9ydCBhc3luYyBmdW5jdGlvbiBHRVQoKSB7CiAgcmV0dXJuIE5leHRSZXNwb25zZS5qc29uKHsKICAgIG9rOiB0cnVlLAogICAgcm91dGU6ICJtZXJjYWRvLXBhZ28tc3Vic2NyaXB0aW9uLXdlYmhvb2siLAogICAgc3VwcG9ydHM6IFsKICAgICAgInBheW1lbnQiLAogICAgICAic3Vic2NyaXB0aW9uX3ByZWFwcHJvdmFsIiwKICAgICAgInN1YnNjcmlwdGlvbl9hdXRob3JpemVkX3BheW1lbnQiLAogICAgXSwKICB9KTsKfQo=")
)

[IO.File]::WriteAllText(
  $Target,
  $RouteCode.TrimEnd() + "`n",
  $Utf8
)

Write-Host "[OK] webhook de assinatura reescrito por completo" -ForegroundColor Green
Write-Host "[OK] objetos remotos normalizados antes do acesso" -ForegroundColor Green
Write-Host "[OK] payment.status tratado com seguranca" -ForegroundColor Green
Write-Host "[OK] IDs e datas convertidos para string ou null" -ForegroundColor Green
Write-Host "[OK] segredo exclusivo MP_SUBSCRIPTION_WEBHOOK_SECRET mantido" -ForegroundColor Green

Write-Host ""
Write-Host "==> Verificando isolamento e referencias" -ForegroundColor Cyan

$RequiredPatterns = @(
  'getSubscriptionWebhookSecret',
  'const payment = record(authorizedPayment.payment);',
  'const subscriptionId =',
  'verifyMercadoPagoWebhookSignature',
  'mercadoPagoPlatformRequest'
)

foreach ($Pattern in $RequiredPatterns) {
  $Match = Select-String `
    -LiteralPath $Target `
    -Pattern $Pattern `
    -SimpleMatch `
    -ErrorAction SilentlyContinue

  if (-not $Match) {
    throw "Verificacao falhou: $Pattern"
  }
}

$ForbiddenPatterns = @(
  'MERCADO_PAGO_PLATFORM_ACCESS_TOKEN',
  'MERCADO_PAGO_ACCESS_TOKEN',
  'MERCADO_PAGO_WEBHOOK_SECRET',
  'NEXT_PUBLIC_MERCADO_PAGO_PUBLIC_KEY',
  'authorizedPayment?.payment?.status'
)

foreach ($Pattern in $ForbiddenPatterns) {
  $Match = Select-String `
    -LiteralPath $Target `
    -Pattern $Pattern `
    -SimpleMatch `
    -ErrorAction SilentlyContinue

  if ($Match) {
    throw "Referencia proibida encontrada: $Pattern"
  }
}

Write-Host "[OK] webhook usa somente o dominio de assinatura" -ForegroundColor Green
Write-Host "[OK] nenhuma leitura insegura de objeto remoto permaneceu" -ForegroundColor Green

if (Test-Path -LiteralPath (Join-Path $Root "scripts\auditar-isolamento-pagamentos.cjs")) {
  Write-Host ""
  Write-Host "==> Auditando os tres fluxos" -ForegroundColor Cyan

  & node (Join-Path $Root "scripts\auditar-isolamento-pagamentos.cjs")
  $AuditCode = $LASTEXITCODE

  if ($AuditCode -ne 0) {
    throw "A auditoria das variaveis isoladas falhou."
  }
}

if (-not $SkipBuild) {
  Write-Host ""
  Write-Host "==> Limpando cache do Next" -ForegroundColor Cyan
  Remove-Item -Recurse -Force (Join-Path $Root ".next") -ErrorAction SilentlyContinue

  Write-Host ""
  Write-Host "==> Executando build completo" -ForegroundColor Cyan

  & npm.cmd run build
  $BuildCode = $LASTEXITCODE

  Write-Host "BUILD_EXIT_CODE=$BuildCode"

  if ($BuildCode -ne 0) {
    Write-Host ""
    Write-Host "O webhook reescrito passou pelas verificacoes, mas o projeto possui outro erro fora deste arquivo." -ForegroundColor Red
    Write-Host "Nenhum commit foi criado." -ForegroundColor Red
    Write-Host "Backup: $Backup" -ForegroundColor Yellow
    exit $BuildCode
  }
}

Write-Host ""
Write-Host "==================================================" -ForegroundColor Magenta
Write-Host "WEBHOOK REVISADO E BUILD APROVADO" -ForegroundColor Magenta
Write-Host "==================================================" -ForegroundColor Magenta
Write-Host "Assinatura: MP_SUBSCRIPTION_*"
Write-Host "Cadastro: MP_SIGNUP_*"
Write-Host "Marketplace: MP_MARKETPLACE_* e OAuth por empresa"
Write-Host "Nenhum commit ou deploy foi criado."
Write-Host "Backup: $Backup"
