'use client'
import {useActionState} from 'react'
import {manageFamily} from '@/app/apps/wealth/familia/actions'
import {familyScopes,type FamilyConnection,type FamilyOption} from '@/lib/wealth/family'
import styles from './calendar.module.css'
type Props={operation:'invite'|'join'|'share'|'accept'|'revoke'|'disconnect';id:string;token:string;version?:number;code?:string;connections?:FamilyConnection[];options?:FamilyOption[]}
const buttons={invite:'Criar convite',join:'Aceitar conexão',share:'Propor compartilhamento',accept:'Aceitar acesso',revoke:'Encerrar acesso',disconnect:'Encerrar conexão'}
const confirms={invite:'Confirmo o destinatário. O convite vale por sete dias e não compartilha dados.',join:'Quero estabelecer esta conexão, sem liberar meus dados financeiros.',share:'Autorizo a leitura contínua dos campos descritos deste registro, inclusive futuras atualizações, até o vencimento ou a revogação. Para documentos, isso inclui todo o conteúdo do arquivo.',accept:'Aceito acessar somente o registro e a finalidade indicados, durante o prazo exibido.',revoke:'Quero encerrar este acesso. Novas leituras serão bloqueadas.',disconnect:'Quero encerrar a conexão e todos os seus compartilhamentos.'}
export function WealthFamilyForm({operation,id,token,version,code,connections=[],options=[]}:Props){
 const [state,action,pending]=useActionState(manageFamily,{ok:false,message:''})
 return <form action={action} data-family-operation={operation}><fieldset key={version} disabled={pending}>
 <input type="hidden" name="operation" value={operation}/><input type="hidden" name="id" value={id}/><input type="hidden" name="idempotency_key" value={token}/>{version!==undefined&&<input type="hidden" name="version" value={version}/>}
 {operation==='invite'&&<><input type="hidden" name="code" value={code}/><div className={styles.fields}><label>Nome desta conexão<input name="label" required maxLength={80} placeholder="Ex.: Planejamento com Ana"/></label><label>Email confirmado da pessoa<input name="email" type="email" required maxLength={254} autoComplete="off"/></label></div><p className={styles.muted}>O nome será visível aos dois. Só a conta com este email confirmado poderá aceitar. Você entrega o código por um canal de sua escolha.</p></>}
 {operation==='join'&&<label>Código de convite<input name="invitation" required maxLength={101} autoComplete="off" spellCheck={false}/></label>}
 {operation==='share'&&<><div className={styles.fields}><label>Conexão destinatária<select name="connection_id" required defaultValue=""><option value="" disabled>Escolha uma conexão</option>{connections.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label>Registro e escopo<select name="resource" required defaultValue=""><option value="" disabled>Escolha um registro</option>{options.map(o=><option key={`${o.scope}:${o.id}`} value={`${o.scope}:${o.id}`}>{familyScopes[o.scope]} · {o.title}</option>)}</select></label><label>Validade em dias<input name="days" type="number" min={1} max={366} defaultValue={30} required/></label></div><label>Finalidade do acesso<input name="purpose" required maxLength={160} placeholder="Ex.: Planejar nossa reserva de viagem"/></label><p className={styles.muted}>Meta: título, valores declarados, prazo e estado. Lançamento: título, tipo, valor e data declarada. Documento: título, categoria, data e arquivo completo. Notas e vínculos privados ficam de fora. Seleção limitada aos primeiros 100 registros de cada tipo.</p></>}
 <label className={styles.confirm}><input type="checkbox" name="confirmed" value="yes" required/>{confirms[operation]}</label><button className={styles.button}>{pending?'Processando…':buttons[operation]}</button></fieldset>
 <p className={styles.status} role="status">{state.message}</p>{state.invitation&&<label>Código para entregar à pessoa<textarea readOnly value={state.invitation} onFocus={e=>e.currentTarget.select()}/></label>}</form>
}
