$ErrorActionPreference = "Stop"

$project = "C:\Users\arauj\grafica-flash"

if (!(Test-Path -LiteralPath $project)) {
  Write-Host "Projeto nao encontrado em $project" -ForegroundColor Red
  exit 1
}

Set-Location -LiteralPath $project

$scriptsDir = Join-Path $project "scripts"
New-Item -ItemType Directory -Force -Path $scriptsDir | Out-Null

$nodeFile = Join-Path $scriptsDir "fix-mojibake-orcaly.cjs"

$base64 = @"
Y29uc3QgZnMgPSByZXF1aXJlKCdmcycpCmNvbnN0IHBhdGggPSByZXF1aXJlKCdwYXRoJykKCmNvbnN0IHByb2plY3QgPSBwcm9jZXNzLmN3ZCgpCmNvbnN0IGZvbGRlcnMgPSBbJ2FwcCcsICdjb21wb25lbnRzJywgJ2xpYiddCmNvbnN0IGV4dHJhRmlsZXMgPSBbJ1JFQURNRS5tZCcsICdSRUxBVE9SSU8tTElNUEVaQS1PUkNBTFkubWQnXQoKY29uc3QgdmFsaWRFeHQgPSBuZXcgU2V0KFsnLnRzJywgJy50c3gnLCAnLmpzJywgJy5qc3gnLCAnLm1kJ10pCgpmdW5jdGlvbiB3YWxrKGRpciwgb3V0ID0gW10pIHsKICBpZiAoIWZzLmV4aXN0c1N5bmMoZGlyKSkgcmV0dXJuIG91dAoKICBmb3IgKGNvbnN0IGl0ZW0gb2YgZnMucmVhZGRpclN5bmMoZGlyLCB7IHdpdGhGaWxlVHlwZXM6IHRydWUgfSkpIHsKICAgIGlmIChpdGVtLm5hbWUgPT09ICdub2RlX21vZHVsZXMnIHx8IGl0ZW0ubmFtZSA9PT0gJy5uZXh0JyB8fCBpdGVtLm5hbWUgPT09ICcuZ2l0JykgY29udGludWUKCiAgICBjb25zdCBmdWxsID0gcGF0aC5qb2luKGRpciwgaXRlbS5uYW1lKQoKICAgIGlmIChpdGVtLmlzRGlyZWN0b3J5KCkpIHsKICAgICAgd2FsayhmdWxsLCBvdXQpCiAgICB9IGVsc2UgaWYgKHZhbGlkRXh0LmhhcyhwYXRoLmV4dG5hbWUoaXRlbS5uYW1lKSkpIHsKICAgICAgb3V0LnB1c2goZnVsbCkKICAgIH0KICB9CgogIHJldHVybiBvdXQKfQoKZnVuY3Rpb24gbW9qaWJha2VPbmNlKHZhbHVlKSB7CiAgcmV0dXJuIEJ1ZmZlci5mcm9tKHZhbHVlLCAndXRmOCcpLnRvU3RyaW5nKCdsYXRpbjEnKQp9CgpmdW5jdGlvbiBtb2ppYmFrZVR3aWNlKHZhbHVlKSB7CiAgcmV0dXJuIEJ1ZmZlci5mcm9tKG1vamliYWtlT25jZSh2YWx1ZSksICd1dGY4JykudG9TdHJpbmcoJ2xhdGluMScpCn0KCmNvbnN0IGNoYXJzID0gWwogICdcdTAwZTEnLCAnXHUwMGUwJywgJ1x1MDBlMycsICdcdTAwZTInLCAnXHUwMGU0JywKICAnXHUwMGU5JywgJ1x1MDBlOCcsICdcdTAwZWEnLCAnXHUwMGViJywKICAnXHUwMGVkJywgJ1x1MDBlYycsICdcdTAwZWUnLCAnXHUwMGVmJywKICAnXHUwMGYzJywgJ1x1MDBmMicsICdcdTAwZjUnLCAnXHUwMGY0JywgJ1x1MDBmNicsCiAgJ1x1MDBmYScsICdcdTAwZjknLCAnXHUwMGZiJywgJ1x1MDBmYycsCiAgJ1x1MDBlNycsICdcdTAwZjEnLAogICdcdTAwYzEnLCAnXHUwMGMwJywgJ1x1MDBjMycsICdcdTAwYzInLCAnXHUwMGM0JywKICAnXHUwMGM5JywgJ1x1MDBjOCcsICdcdTAwY2EnLCAnXHUwMGNiJywKICAnXHUwMGNkJywgJ1x1MDBjYycsICdcdTAwY2UnLCAnXHUwMGNmJywKICAnXHUwMGQzJywgJ1x1MDBkMicsICdcdTAwZDUnLCAnXHUwMGQ0JywgJ1x1MDBkNicsCiAgJ1x1MDBkYScsICdcdTAwZDknLCAnXHUwMGRiJywgJ1x1MDBkYycsCiAgJ1x1MDBjNycsICdcdTAwZDEnLAogICdcdTAwYmEnLCAnXHUwMGFhJywgJ1x1MDBiMCcsICdcdTAwYjcnCl0KCmNvbnN0IHJlcGxhY2VtZW50cyA9IG5ldyBNYXAoKQoKZm9yIChjb25zdCBjaCBvZiBjaGFycykgewogIHJlcGxhY2VtZW50cy5zZXQobW9qaWJha2VUd2ljZShjaCksIGNoKQogIHJlcGxhY2VtZW50cy5zZXQobW9qaWJha2VPbmNlKGNoKSwgY2gpCn0KCmNvbnN0IG1hbnVhbCA9IFsKICBbJ1x1MDBlMlx1MjBhY1x1MjAxYycsICdcdTIwMTMnXSwKICBbJ1x1MDBlMlx1MjBhY1x1MjAxZCcsICdcdTIwMTQnXSwKICBbJ1x1MDBlMlx1MjBhY1x1MDJkYycsICdcdTIwMTgnXSwKICBbJ1x1MDBlMlx1MjBhY1x1MjEyMicsICdcdTIwMTknXSwKICBbJ1x1MDBlMlx1MjBhY1x1MDE1MycsICdcdTIwMWMnXSwKICBbJ1x1MDBlMlx1MjBhY1x1ZmZmZCcsICdcdTIwMWQnXSwKICBbJ1x1MDBlMlx1MjBhY1x1MDBhNicsICdcdTIwMjYnXSwKICBbJ1x1MDBjMlx1MDBhMCcsICcgJ10sCiAgWydcdTAwYzJcdTAwYmEnLCAnXHUwMGJhJ10sCiAgWydcdTAwYzJcdTAwYWEnLCAnXHUwMGFhJ10sCiAgWydcdTAwYzJcdTAwYjAnLCAnXHUwMGIwJ10sCiAgWydcdTAwYzJcdTAwYjcnLCAnXHUwMGI3J10sCl0KCmZvciAoY29uc3QgW2JhZCwgZ29vZF0gb2YgbWFudWFsKSB7CiAgcmVwbGFjZW1lbnRzLnNldChiYWQsIGdvb2QpCn0KCmNvbnN0IG9yZGVyZWRSZXBsYWNlbWVudHMgPSBbLi4ucmVwbGFjZW1lbnRzLmVudHJpZXMoKV0KICAuZmlsdGVyKChbYmFkXSkgPT4gYmFkKQogIC5zb3J0KChhLCBiKSA9PiBiWzBdLmxlbmd0aCAtIGFbMF0ubGVuZ3RoKQoKZnVuY3Rpb24gZml4VGV4dChpbnB1dCkgewogIGxldCBvdXRwdXQgPSBpbnB1dAoKICBmb3IgKGxldCBwYXNzID0gMDsgcGFzcyA8IDM7IHBhc3MgKz0gMSkgewogICAgbGV0IG5leHQgPSBvdXRwdXQKCiAgICBmb3IgKGNvbnN0IFtiYWQsIGdvb2RdIG9mIG9yZGVyZWRSZXBsYWNlbWVudHMpIHsKICAgICAgbmV4dCA9IG5leHQuc3BsaXQoYmFkKS5qb2luKGdvb2QpCiAgICB9CgogICAgaWYgKG5leHQgPT09IG91dHB1dCkgYnJlYWsKICAgIG91dHB1dCA9IG5leHQKICB9CgogIHJldHVybiBvdXRwdXQKfQoKY29uc3QgZmlsZXMgPSBbXQpmb3IgKGNvbnN0IGZvbGRlciBvZiBmb2xkZXJzKSB7CiAgd2FsayhwYXRoLmpvaW4ocHJvamVjdCwgZm9sZGVyKSwgZmlsZXMpCn0KCmZvciAoY29uc3QgZXh0cmEgb2YgZXh0cmFGaWxlcykgewogIGNvbnN0IGZ1bGwgPSBwYXRoLmpvaW4ocHJvamVjdCwgZXh0cmEpCiAgaWYgKGZzLmV4aXN0c1N5bmMoZnVsbCkpIGZpbGVzLnB1c2goZnVsbCkKfQoKbGV0IGNoYW5nZWQgPSAwCmxldCBzY2FubmVkID0gMAoKZm9yIChjb25zdCBmaWxlIG9mIFsuLi5uZXcgU2V0KGZpbGVzKV0pIHsKICBzY2FubmVkICs9IDEKCiAgY29uc3Qgb3JpZ2luYWwgPSBmcy5yZWFkRmlsZVN5bmMoZmlsZSwgJ3V0ZjgnKQogIGNvbnN0IGZpeGVkID0gZml4VGV4dChvcmlnaW5hbCkKCiAgaWYgKGZpeGVkICE9PSBvcmlnaW5hbCkgewogICAgY29uc3Qgc3RhbXAgPSBuZXcgRGF0ZSgpCiAgICAgIC50b0lTT1N0cmluZygpCiAgICAgIC5yZXBsYWNlKC9bLTpULlpdL2csICcnKQogICAgICAuc2xpY2UoMCwgMTQpCgogICAgY29uc3QgYmFja3VwID0gYCR7ZmlsZX0uYmFja3VwLWFjZW50b3Mtbm9kZS0ke3N0YW1wfWAKICAgIGZzLmNvcHlGaWxlU3luYyhmaWxlLCBiYWNrdXApCiAgICBmcy53cml0ZUZpbGVTeW5jKGZpbGUsIGZpeGVkLCAndXRmOCcpCgogICAgY2hhbmdlZCArPSAxCiAgICBjb25zb2xlLmxvZyhgQWNlbnRvcyBjb3JyaWdpZG9zOiAke3BhdGgucmVsYXRpdmUocHJvamVjdCwgZmlsZSl9YCkKICB9Cn0KCmNvbnN0IG5leHREaXIgPSBwYXRoLmpvaW4ocHJvamVjdCwgJy5uZXh0JykKaWYgKGZzLmV4aXN0c1N5bmMobmV4dERpcikpIHsKICBmcy5ybVN5bmMobmV4dERpciwgeyByZWN1cnNpdmU6IHRydWUsIGZvcmNlOiB0cnVlIH0pCn0KCmNvbnNvbGUubG9nKCcnKQpjb25zb2xlLmxvZyhgQXJxdWl2b3MgdmVyaWZpY2Fkb3M6ICR7c2Nhbm5lZH1gKQpjb25zb2xlLmxvZyhgQXJxdWl2b3MgY29ycmlnaWRvczogJHtjaGFuZ2VkfWApCmNvbnNvbGUubG9nKCcnKQpjb25zb2xlLmxvZygnQWdvcmEgcm9kZTogbnBtIHJ1biBidWlsZCcpCg==
"@

$bytes = [System.Convert]::FromBase64String($base64.Trim())
$content = [System.Text.Encoding]::UTF8.GetString($bytes)
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($nodeFile, $content, $utf8NoBom)

Write-Host "Corretor Node criado em scripts\fix-mojibake-orcaly.cjs" -ForegroundColor Green
Write-Host "Rodando correcao de acentos..." -ForegroundColor Cyan

node $nodeFile

if ($LASTEXITCODE -ne 0) {
  Write-Host "Falha ao rodar o corretor Node." -ForegroundColor Red
  exit $LASTEXITCODE
}

Write-Host ""
Write-Host "Correcao finalizada. Rode npm run build." -ForegroundColor Yellow
