// Wave 1 pack — graphic.print_shop. Content source: lib/orcaly-nichos.ts#grafica (copied and
// frozen at v1.0.0; changes require a version bump). "Comunicação visual" is a subsegment here,
// not a separate pack.

import type { IndustryPackDefinition } from '../core/types'
import {
  categories,
  dashboards,
  integration,
  moduleItem,
  onboarding,
  permission,
  proposalTemplate,
  readyMessages,
  recipe,
  setting,
  statusFlow,
} from './builders'

export const graphicPrintShopPack: IndustryPackDefinition = {
  schemaVersion: 1,
  key: 'graphic.print_shop',
  version: '1.0.0',
  status: 'published',
  businessType: 'graphic',
  subsegments: ['Gráfica', 'Gráfica rápida', 'Comunicação visual', 'Impressos', 'Sinalização'],
  name: 'Gráfica',
  description: 'Orçamentos de impressos e comunicação visual, aprovação de arte, produção, retirada e entrega.',
  capabilities: [
    'cap.quotes',
    'cap.custom_production',
    'cap.art_approval',
    'cap.production_tracking',
    'cap.deposit',
    'cap.pickup',
    'cap.delivery',
    'cap.crm_followup',
    'cap.team_tasks',
  ],
  items: [
    moduleItem('pedidos_orcamentos', 'required', 1),
    moduleItem('orcamentos', 'required', 2),
    moduleItem('produtos_graficos', 'required', 3),
    moduleItem('propostas', 'default', 4, ['propostas']),
    moduleItem('producao', 'default', 5, ['producao']),
    moduleItem('clientes_crm', 'default', 6, ['crm']),
    moduleItem('tarefas', 'default', 7),
    moduleItem('aprovacao_arte', 'optional', 8),
    ...statusFlow('order', [
      { label: 'Recebido', semantic: 'new' },
      { label: 'Aguardando arte', semantic: 'waiting_customer' },
      { label: 'Aguardando pagamento', semantic: 'waiting_payment' },
      { label: 'Em produção', semantic: 'in_progress' },
      { label: 'Aguardando retirada', semantic: 'ready' },
      { label: 'Saiu para entrega', semantic: 'in_progress' },
      { label: 'Entregue', semantic: 'delivered', terminal: true },
    ]),
    ...categories(['Cartões de visita', 'Panfletos', 'Banners', 'Adesivos', 'Lonas', 'Placas', 'Convites']),
    ...dashboards(['pedidosTotal', 'aguardandoArte', 'propostasEnviadas', 'emProducao', 'prontos', 'faturamentoEstimado']),
    recipe('proposal_accepted_production_task@1.0.0', 'recommended'),
    recipe('order_delayed_internal_task@1.0.0', 'recommended'),
    recipe('proposal_followup_task@1.0.0', 'recommended'),
    integration('google_drive', ['files.read', 'files.write']),
    permission('atendente', ['orders.read', 'orders.update', 'proposals.manage']),
    permission('producao', ['orders.read', 'orders.update', 'production.manage', 'products.manage']),
    proposalTemplate(
      {
        titulo: 'Proposta gráfica personalizada',
        introducao: 'Segue proposta com materiais, quantidades e condições para produção gráfica.',
        condicoes: 'Produção iniciada após aprovação da arte e confirmação do sinal.',
        prazoPadrao: '2 a 5 dias úteis após aprovação da arte.',
        validadeHoras: 48,
      },
      ['propostas'],
    ),
    ...readyMessages([
      'Recebemos seu orçamento e vamos analisar.',
      'Sua arte está em aprovação.',
      'Seu pedido entrou em produção.',
      'Seu pedido está pronto para retirada.',
    ]),
    ...onboarding([
      { stepKey: 'add_products', label: 'Cadastre seus produtos gráficos', signal: 'products.count_gte_1' },
      { stepKey: 'review_statuses', label: 'Revise as etapas do pedido', signal: 'statuses.reviewed' },
      { stepKey: 'publish_site', label: 'Publique sua página de orçamentos', signal: 'site.published' },
    ]),
    setting('orders.questions', [
      'Qual material deseja?',
      'Já possui a arte?',
      'Qual tamanho?',
      'Qual quantidade?',
      'Qual prazo desejado?',
      'Vai retirar ou precisa de entrega?',
    ]),
    setting('orders.recommendedFields', ['material', 'quantidade', 'largura', 'altura', 'arte', 'acabamento', 'prazo', 'entrega']),
    setting('proposals.defaultValidityHours', 48),
    setting('payments.depositEnabled', true, 'recommended'),
  ],
  minimumRequirements: { plan: 'basic', features: ['pedidos', 'produtos'], modules: ['pedidos_orcamentos'] },
  legacy: { nichoIds: ['grafica'] },
  changelog: [
    {
      version: '1.0.0',
      date: '2026-09-28',
      kind: 'major',
      summary: 'Versão inicial a partir do nicho legado grafica; comunicação visual como subsegmento.',
      changes: [],
    },
  ],
}
