import Link from 'next/link'
import {randomUUID,randomBytes} from 'node:crypto'
import {getEcosystemIdentity,getPersonalProductAccess} from '@/lib/ecosystem/server'
import {familyScopes,familyStates,type FamilyOverview,type FamilyOption} from '@/lib/wealth/family'
import {formatMoney,formatFinancialDate,integer} from '@/lib/wealth/core'
import {WealthFamilyForm} from '@/components/wealth/WealthFamilyForm'
import styles from '@/components/wealth/calendar.module.css'
export default async function FamilyPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const identity=await getEcosystemIdentity();if(!identity||identity.mfaRequired)return <><h1>Wealth Family</h1><p>Entre na sua conta para gerenciar conexões e acessos.</p><Link href="/login?next=%2Fapps%2Fwealth%2Ffamilia">Entrar</Link></>
 let page:number;try{page=integer((await searchParams).page??1,1,100000)}catch{return <><h1>Página inválida</h1><Link href="/apps/wealth/familia">Voltar à Family</Link></>}
 const {db,user}=identity,result=await db.rpc('wealth_family_overview',{p_page:page})
 if(result.error)throw Error('Não foi possível consultar seus compartilhamentos.')
 const view=result.data as FamilyOverview,read=(await getPersonalProductAccess('wealth','wealth.read')).allowed,write=read&&(await getPersonalProductAccess('wealth','wealth.write')).allowed
 if(!read)view.shares=view.shares.map(share=>({...share,resource:null}))
 const options:FamilyOption[]=[]
 if(write){for(const [table,scope] of [['wealth_goals','goal.summary'],['wealth_entries','entry.summary'],['wealth_documents','document.download']] as const){
  let query=db.from(table).select('id,title').eq('user_id',user.id);query=table==='wealth_documents'?query.eq('status','active'):query.is('archived_at',null)
  const rows=await query.order('created_at',{ascending:false}).order('id').limit(100);if(rows.error)throw Error('Não foi possível consultar os registros disponíveis.');for(const row of rows.data??[])options.push({...row,scope})
 }}
 const active=view.connections.filter(c=>c.state==='active'),total=BigInt(view.total)>BigInt(view.connectionTotal)?BigInt(view.total):BigInt(view.connectionTotal),pages=(total+BigInt(24))/BigInt(25),date=(v:string)=>new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'medium',timeStyle:'short'}).format(new Date(v))
 return <div className={styles.page}><nav className={styles.nav} aria-label="Family Wealth"><Link href="/apps/wealth">Visão geral</Link><Link href="/apps/wealth/familia" aria-current="page">Family</Link><Link href="/apps/wealth/documentos">Documentos</Link><Link href="/apps/privacidade">Privacidade</Link></nav>
 <header className={styles.hero}><div><span className={styles.kicker}>Planejar juntos, escolher o que compartilhar</span><h1>Wealth Family</h1><p>Convide alguém e escolha, registro por registro, o que essa pessoa poderá acompanhar.</p></div><aside>Uma conexão não dá acesso ao patrimônio. Cada permissão exige sua autorização e o aceite de quem recebe. One e vínculos empresariais não liberam dados pessoais.</aside></header>
 <p className={styles.notice}>Valores são declarações do titular, sem confirmação de pagamento bancário. Não somamos registros compartilhados ao seu saldo. A revogação bloqueia novas leituras, mas não recupera arquivos já baixados. Horários em São Paulo.</p>
 {!read&&<p role="status">Seu acesso ao Wealth não está ativo. Você ainda pode encerrar conexões e permissões existentes.</p>}
 <section className={styles.section}><h2>Suas conexões</h2><p>{view.connectionTotal} conexão(ões). Até 30 convites ou conexões não encerrados por quem convida; limite operacional desta versão.</p>
 {view.connections.length?<ul className={styles.agenda}>{view.connections.map(c=><li key={c.id} className={styles.bill} data-connection-id={c.id}><h3>{c.label}</h3><p>{familyStates[c.state]} · {c.owned?'Convite criado por você':'Convite aceito por você'}{c.state==='pending'&&` · válido até ${date(c.invite_expires_at)}`}</p>{c.state!=='revoked'&&<details className={styles.details}><summary>Gerenciar conexão</summary><WealthFamilyForm operation="disconnect" id={c.id} version={c.version} token={randomUUID()}/></details>}</li>)}</ul>:<p className={styles.empty}>Nenhuma conexão nesta página. Comece por um convite; nenhum registro será compartilhado automaticamente.</p>}
 {write&&<details className={styles.details}><summary>Convidar uma pessoa</summary><WealthFamilyForm operation="invite" id={randomUUID()} token={randomUUID()} code={randomBytes(32).toString('hex')}/></details>}
 {read&&<details className={styles.details}><summary>Tenho um convite</summary><WealthFamilyForm operation="join" id={randomUUID()} token={randomUUID()}/></details>}</section>
 <section className={styles.section}><h2>Permissões e registros</h2><p>{view.total} permissão(ões) · página {page}. Até 25 conexões e 25 permissões por página. Até 200 permissões vigentes criadas por pessoa.</p>
 {write&&active.length>0&&<details className={styles.details}><summary>Compartilhar um registro</summary><WealthFamilyForm operation="share" id={randomUUID()} token={randomUUID()} connections={active} options={options}/></details>}
 {view.shares.length?<ul className={styles.agenda}>{view.shares.map(s=><li key={s.id} className={styles.bill} data-share-id={s.id}><div className={styles.billHeader}><div><h3>{s.resource?.title??familyScopes[s.scope]}</h3><p>{s.owned?'Compartilhado por você':'Compartilhado com você'} · {familyScopes[s.scope]}</p></div><span className={styles.tag}>{familyStates[s.state]}</span></div><p>Finalidade: {s.purpose}</p><p>Válido até {date(s.expires_at)}. Conexão: {view.connections.find(c=>c.id===s.connection_id)?.label??'Conexão em outra página'}.</p>
 {s.resource?<><p>{s.resource.amount_cents!==undefined&&`${({income:'Receita',expense:'Despesa',asset:'Ativo',liability:'Passivo'} as Record<string,string>)[s.resource.kind??'']??'Registro'}: ${formatMoney(s.resource.amount_cents)}. `}{s.resource.target_cents!==undefined&&`Meta: ${formatMoney(s.resource.saved_cents??'0')} declarado de ${formatMoney(s.resource.target_cents)}. `}{s.resource.date&&`Data: ${formatFinancialDate(s.resource.date)}.`}</p>{!s.owned&&s.scope==='document.download'&&s.state==='active'&&<a href={`/api/wealth/family/${s.id}/document`} className={styles.button}>Baixar arquivo compartilhado</a>}</>:<p className={styles.muted}>Conteúdo indisponível até o aceite, ou por encerramento, expiração, remoção do registro ou ausência de acesso ao Wealth de uma das pessoas.</p>}
 {s.state==='pending'&&!s.owned&&read&&<WealthFamilyForm operation="accept" id={s.id} version={s.version} token={randomUUID()}/>}
 {s.state!=='revoked'&&<details className={styles.details}><summary>Recusar ou encerrar acesso</summary><WealthFamilyForm operation="revoke" id={s.id} version={s.version} token={randomUUID()}/></details>}</li>)}</ul>:<p className={styles.empty}>Nenhuma permissão nesta página. Uma conexão aceita permite propor um registro específico.</p>}
 <nav className={styles.nav} aria-label="Paginação Family">{page>1&&<Link href={`?page=${page-1}`}>Página anterior</Link>}{BigInt(page)<pages&&<Link href={`?page=${page+1}`}>Próxima página</Link>}</nav></section>
 <section className={styles.section}><h2>Compartilhar com clareza</h2><p>Metas e lançamentos expõem apenas os campos descritos na autorização. Um documento compartilha o arquivo inteiro; revise seu conteúdo antes de autorizar. Notas, referências, outros registros e a Timeline continuam privados. Permissões acompanham as atualizações do mesmo registro. Para mudar o escopo, encerre e crie uma nova permissão.</p><p>Convites são entregues manualmente. Envio automático de email: NOT_CONFIGURED. Family não envia conteúdos para IA ou integrações.</p></section></div>
}
