export const DEPRECATED_COMPANY_SECRET_FIELDS = [
  'whatsapp_access_token',
  'whatsapp_verify_token',
] as const

// Explicit allowlist: new database columns do not become client/server-access
// fields automatically. In particular, provider secrets must never be added here.
export const COMPANY_ACCESS_COLUMNS: string = 'id,nome,slug,logo_url,whatsapp,cor_principal,plano,ativo,created_at,owner_id,email,segmento,telefone,cidade,estado,pix_key,pix_nome,pix_cidade,aceita_pix,aceita_cartao,cobrar_sinal,percentual_sinal,assinatura_status,assinatura_plano,assinatura_inicio,assinatura_expira_em,assinatura_ultimo_pagamento,mercado_pago_customer_email,tester_id,modelo_negocio,modelo_nome,modelo_perguntas,subdomain_slug,site_template,site_status,site_primary_color,site_accent_color,site_config,site_updated_at,pix_tipo,atendimento_horario,atendimento_observacao,instagram,marketplace_ativo,marketplace_titulo,marketplace_subtitulo,marketplace_banner_url,marketplace_texto_botao,marketplace_sobre,marketplace_endereco,marketplace_mapa_url,marketplace_termos,marketplace_config,site_publico_ativo,site_background_color,site_headline,site_subheadline,site_cta_text,site_banner_url,site_about_title,site_about_text,site_services_title,site_contact_title,site_show_store,site_show_about,site_show_contact,site_show_featured,site_features,site_faq,site_testimonials,site_custom_sections,updated_at,assinatura_auto_recorrente,assinatura_cancelada_em,assinatura_checkout_url,assinatura_mp_payload,assinatura_proxima_cobranca,mercado_pago_subscription_id,mercado_pago_subscription_status,modelo_status,modelo_mensagens,modelo_proposta,modelo_campos_recomendados,site_layout,site_art_style,site_font_style,site_button_style,site_hero_alignment,site_text_color,site_card_color,site_badge_text,site_secondary_cta_text,site_whatsapp_message,site_show_faq,site_show_testimonials,site_show_gallery,site_show_benefits,site_gallery,site_benefits,site_seo_title,site_seo_description,site_keywords,site_promo_title,site_promo_text,site_promo_active,site_promo_button_text,site_business_hours,site_payment_methods,site_delivery_options,site_hero_style,site_art_variant,site_section_style,site_product_card_style,site_nav_variant,site_corner_style,site_density,site_show_marketplace,site_enable_cart,site_enable_coupons,site_show_prices,site_checkout_mode,site_marketplace_title,site_marketplace_subtitle,site_cart_button_text,site_checkout_button_text,site_empty_catalog_text,site_trust_title,site_hero_highlights,site_brand_words,site_footer_text,whatsapp_enabled,whatsapp_phone_number_id,whatsapp_business_account_id,whatsapp_auto_reply_enabled,whatsapp_order_notifications,whatsapp_status_notifications,whatsapp_ai_enabled,whatsapp_ai_prompt,banner_url,onboarding_current_step,onboarding_completed,onboarding_completed_at,onboarding_dismissed,onboarding_updated_at,business_type,onboarding_goal,site_theme,site_cta_label,site_sections,assinatura_forma_pagamento_preferida,assinatura_pix_avulso_status,assinatura_pix_avulso_ultimo_pagamento,trial_started_at,trial_ends_at,trial_used_at,cancel_at_period_end,access_until,subscription_provider,provider_customer_id,provider_subscription_id,next_billing_at,is_founder,founder_number,founder_price_cents,founder_started_at,founder_trial_ends_at,founder_price_ends_at,founder_welcome_seen_at,founder_price_converted_at,founder_billing_claim_id,founder_billing_claimed_at,founder_billing_attempts,founder_billing_last_error,founder_billing_setup_at,founder_billing_authorized_at,founder_billing_last_sync_at,founder_price_conversion_claim_id,founder_price_conversion_claimed_at,founder_price_conversion_attempts,founder_price_conversion_last_error,timezone'

const COMPANY_CLIENT_FIELDS = COMPANY_ACCESS_COLUMNS.split(',')

export function toClientCompany(company: Record<string, unknown> | null) {
  if (!company) return null
  const output: Record<string, unknown> = {}
  for (const field of COMPANY_CLIENT_FIELDS) {
    if (Object.prototype.hasOwnProperty.call(company, field)) output[field] = company[field]
  }
  return output
}

export function hasDeprecatedCompanySecretWrite(value: unknown) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return false
  return DEPRECATED_COMPANY_SECRET_FIELDS.some((field) =>
    Object.prototype.hasOwnProperty.call(value, field),
  )
}
