'use client'

import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'next/navigation'
import { supabase } from '@/lib/supabase'

type Json = Record<string, unknown>
type Payload = { company: Json; health: { score: number; label: string; reasons: string[] }; usage: { orders: number; products: number; customers: number; lastOrderAt?: string | null; recentOrders: Json[] }; members: Json[]; billing: { payments: Json[]; events: Json[] }; integration: Json | null; referral: Json | null; security: Json[]; audit: Json[]; capabilities: { canWriteCompany: boolean; canBlockCompany: boolean; canManageBilling: boolean; supportReadonly: boolean; supportWrite: boolean } }

function money(value: unknown) { return Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }) }
function dt(value: unknown) { if (!value) return '—'; const d = new Date(String(value)); return Number.isNaN(d.getTime()) ? '—' : new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(d) }
function healthTone(label: string) { return label === 'HEALTHY' ? 'bg-emerald-50 text-emerald-700' : label === 'ATTENTION' ? 'bg-amber-50 text-amber-700' : 'bg-red-50 text-red-700' }

export default function AdminCompany360({ companyId }: { companyId: string }) {
  const search = useSearchParams()
  const supportMode = search.get('support') === '1'
  const [data, setData] = useState<Payload | null>(null)
  const [error, setError] = useState('')
  const [tab, setTab] = useState('overview')
  const [version, setVersion] = useState(0)
  const [action, setAction] = useState('')
  const [reason, setReason] = useState('')
  const [days, setDays] = useState(7)
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState('')

  useEffect(() => {
    let active = true
    void supabase.auth.getSession().then(async ({ data: auth }) => {
      const response = await fetch(`/api/admin/company-360/${companyId}`, { headers: { Authorization: `Bearer ${auth.session?.access_token || ''}` }, cache: 'no-store' })
      const payload = await response.json().catch(() => ({}))
      if (!active) return
      if (!response.ok) { setError(payload.error || 'Empresa não encontrada.'); return }
      setData(payload as Payload); setError('')
    })
    return () => { active = false }
  }, [companyId, version])

  const tabs = useMemo(() => ['overview','subscription','usage','users','payments','integrations','security','audit'], [])

  async function runAction() {
    if (!data || supportMode || reason.trim().length < 8) return
    setBusy(true); setMessage(''); setError('')
    const auth = await supabase.auth.getSession()
    const response = await fetch(`/api/admin/company/${companyId}`, { method: 'PATCH', headers: { Authorization: `Bearer ${auth.data.session?.access_token || ''}`, 'Content-Type': 'application/json', 'Idempotency-Key': crypto.randomUUID() }, body: JSON.stringify({ action, reason, days }) })
    const payload = await response.json().catch(() => ({}))
    setBusy(false)
    if (!response.ok) { setError(payload.error || 'Ação não concluída.'); return }
    setAction(''); setReason(''); setMessage('Ação concluída e registrada na auditoria.'); setVersion((value) => value + 1)
  }

  if (!data && !error) return <div className="h-96 animate-pulse rounded-3xl bg-white motion-reduce:animate-none"/>
  if (!data) return <div className="rounded-2xl border border-red-100 bg-red-50 p-6 text-red-700">{error}</div>
  const c = data.company
  const plan = String(c.assinatura_plano || c.plano || 'Sem plano')

  return <div className="space-y-4">
    {supportMode ? <div className="sticky top-[4.4rem] z-30 rounded-xl border border-amber-200 bg-amber-50 p-3 shadow-sm"><strong className="text-sm text-amber-800">MODO SUPORTE · Visualizando: {String(c.nome || 'Empresa')} · Somente leitura</strong><p className="mt-1 text-xs text-amber-700">Nenhuma sessão do cliente foi assumida. Ações administrativas estão desativadas nesta visualização.</p></div> : null}
    <section className="rounded-3xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div className="flex min-w-0 gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-[#0b2e63] text-lg font-semibold text-white">{String(c.nome || 'O').slice(0,1).toUpperCase()}</div><div className="min-w-0"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-slate-400">Empresa 360</p><h1 className="mt-1 truncate text-3xl font-semibold tracking-[-.04em] text-[#0b2e63]">{String(c.nome || c.email || companyId)}</h1><p className="mt-1 truncate text-xs text-slate-400">{String(c.id)} · /{String(c.slug || 'sem-slug')} · {String(c.segmento || c.business_type || 'segmento não informado')}</p></div></div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-xl px-3 py-2 text-xs font-semibold ${healthTone(data.health.label)}`}>{data.health.score}/100 · {data.health.label}</span><span className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-600">{plan}</span><span className="rounded-xl bg-blue-50 px-3 py-2 text-xs font-semibold text-blue-700">{String(c.state || c.assinatura_status || 'sem status')}</span></div></div><div className="mt-5 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{data.health.reasons.map((item) => <div key={item} className="rounded-xl bg-slate-50 px-3 py-2.5 text-xs text-slate-500">{item}</div>)}{!data.health.reasons.length ? <div className="rounded-xl bg-emerald-50 px-3 py-2.5 text-xs text-emerald-700">Sem fatores negativos nas fontes avaliadas.</div> : null}</div></section>
    {message ? <div className="rounded-xl border border-emerald-100 bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{message}</div> : null}{error ? <div className="rounded-xl border border-red-100 bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div> : null}
    <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white p-2"><div className="flex min-w-max gap-1">{tabs.map((item) => <button type="button" key={item} onClick={() => setTab(item)} className={`rounded-xl px-3.5 py-2.5 text-xs font-semibold ${tab === item ? 'bg-[#0b2e63] text-white' : 'text-slate-500 hover:bg-slate-50'}`}>{({ overview:'Visão geral',subscription:'Assinatura',usage:'Uso',users:'Usuários',payments:'Pagamentos',integrations:'Integrações',security:'Segurança',audit:'Auditoria' } as Record<string,string>)[item]}</button>)}</div></div>

    {tab === 'overview' ? <section className="grid gap-4 xl:grid-cols-[1fr_360px]"><div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold">Contexto operacional</h2><dl className="mt-4 grid gap-3 sm:grid-cols-2">{[['Owner e-mail',c.email],['Último login',dt(c.lastLoginAt)],['Cadastro',dt(c.created_at)],['Atualização',dt(c.updated_at)],['Onboarding',c.onboarding_completed ? 'Concluído' : `Etapa ${String(c.onboarding_current_step || '—')}`],['Próxima cobrança',dt(c.next_billing_at || c.assinatura_proxima_cobranca)],['Origem parceiro',data.referral ? 'Parceiro atribuído' : 'Sem atribuição observada'],['Site',c.site_publico_ativo ? 'Publicado' : 'Não publicado']].map(([key,value]) => <div key={String(key)} className="rounded-xl bg-slate-50 p-3"><dt className="text-[9px] font-semibold uppercase tracking-[.1em] text-slate-400">{String(key)}</dt><dd className="mt-1 truncate text-sm font-semibold">{String(value || '—')}</dd></div>)}</dl></div><aside className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold">Ações administrativas</h2>{supportMode ? <p className="mt-3 text-sm text-amber-700">Desativadas no Modo Suporte read-only.</p> : <div className="mt-4 grid gap-2">{data.capabilities.canBlockCompany ? <><button onClick={() => setAction(c.ativo === false ? 'unblock' : 'block')} className="rounded-xl border border-slate-200 px-3 py-2.5 text-left text-xs font-semibold">{c.ativo === false ? 'Desbloquear acesso' : 'Bloquear acesso'}</button></> : null}{data.capabilities.canManageBilling ? <><button onClick={() => setAction('extend_trial')} className="rounded-xl border border-slate-200 px-3 py-2.5 text-left text-xs font-semibold">Prorrogar trial</button><button onClick={() => setAction('courtesy')} className="rounded-xl border border-slate-200 px-3 py-2.5 text-left text-xs font-semibold">Adicionar cortesia</button></> : null}{!data.capabilities.canBlockCompany && !data.capabilities.canManageBilling ? <p className="text-sm text-slate-400">Seu papel é somente leitura para ações sensíveis.</p> : null}</div>}<p className="mt-4 text-[11px] leading-5 text-slate-400">Alterar plano, refund e sincronização manual não aparecem porque ainda não existe contrato administrativo seguro para essas ações.</p></aside></section> : null}
    {tab === 'subscription' ? <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold">Assinatura</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Plano',plan],['Status',c.assinatura_status],['Início',dt(c.assinatura_inicio)],['Trial termina',dt(c.trial_ends_at)],['Acesso até',dt(c.access_until || c.assinatura_expira_em)],['Último pagamento',dt(c.assinatura_ultimo_pagamento)],['Próxima cobrança',dt(c.next_billing_at || c.assinatura_proxima_cobranca)],['Provider',c.subscription_provider]].map(([key,value]) => <div key={String(key)} className="rounded-xl bg-slate-50 p-3"><span className="text-[9px] font-semibold uppercase text-slate-400">{String(key)}</span><strong className="mt-1 block text-sm">{String(value || '—')}</strong></div>)}</div><h3 className="mt-6 text-sm font-semibold">Timeline</h3><div className="mt-3 space-y-2">{data.billing.events.map((event) => <div key={String(event.id)} className="flex gap-3 rounded-xl border border-slate-100 p-3"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-[#0b2e63]"/><div><strong className="text-xs">{String(event.event_type || 'Evento')}</strong><p className="mt-1 text-[11px] text-slate-400">{String(event.old_status || '—')} → {String(event.new_status || '—')} · {dt(event.created_at)}</p>{event.error_message ? <p className="mt-1 text-[11px] text-red-600">{String(event.error_message)}</p> : null}</div></div>)}{!data.billing.events.length ? <p className="text-sm text-slate-400">Nenhum evento de assinatura disponível para seu papel.</p> : null}</div></section> : null}
    {tab === 'usage' ? <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold">Uso observado</h2><div className="mt-4 grid grid-cols-3 gap-3"><div className="rounded-xl bg-slate-50 p-4"><span className="text-xs text-slate-400">Pedidos</span><strong className="mt-2 block text-2xl text-[#0b2e63]">{data.usage.orders}</strong></div><div className="rounded-xl bg-slate-50 p-4"><span className="text-xs text-slate-400">Produtos</span><strong className="mt-2 block text-2xl text-[#0b2e63]">{data.usage.products}</strong></div><div className="rounded-xl bg-slate-50 p-4"><span className="text-xs text-slate-400">Clientes</span><strong className="mt-2 block text-2xl text-[#0b2e63]">{data.usage.customers}</strong></div></div><p className="mt-4 text-xs text-slate-400">Último pedido observado: {dt(data.usage.lastOrderAt)}</p></section> : null}
    {tab === 'users' ? <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold">Usuários / memberships</h2><div className="mt-4 space-y-2">{data.members.map((member) => <div key={String(member.id)} className="flex flex-col justify-between gap-2 rounded-xl border border-slate-100 p-3 sm:flex-row sm:items-center"><div><strong className="text-sm">{String(member.nome || member.email || 'Usuário')}</strong><p className="text-xs text-slate-400">{String(member.email || '')}</p></div><span className="text-xs font-semibold text-slate-500">{String(member.cargo || 'membro')} · {String(member.status || '')}</span></div>)}{!data.members.length ? <p className="text-sm text-slate-400">Nenhum membership visível.</p> : null}</div></section> : null}
    {tab === 'payments' ? <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold">Pagamentos</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="text-[9px] uppercase tracking-[.1em] text-slate-400"><tr><th className="pb-3">Data</th><th>Plano</th><th>Status</th><th>Provider</th><th>Método</th><th className="text-right">Valor</th></tr></thead><tbody>{data.billing.payments.map((payment) => <tr key={String(payment.id)} className="border-t border-slate-100"><td className="py-3">{dt(payment.paid_at || payment.created_at)}</td><td>{String(payment.plano || '—')}</td><td>{String(payment.status || '—')}</td><td>{String(payment.provider || '—')}</td><td>{String(payment.payment_method || '—')}</td><td className="text-right font-semibold">{money(payment.valor)}</td></tr>)}</tbody></table>{!data.billing.payments.length ? <p className="py-8 text-center text-sm text-slate-400">Sem pagamentos visíveis para este papel.</p> : null}</div></section> : null}
    {tab === 'integrations' ? <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold">Integrações</h2>{data.integration ? <div className="mt-4 rounded-xl bg-slate-50 p-4"><strong className="text-sm">{String(data.integration.provider || 'Provider')}</strong><p className="mt-1 text-xs text-slate-500">Status: {String(data.integration.onboarding_status || '—')} · ativo: {data.integration.is_active ? 'sim' : 'não'}</p>{data.integration.last_error ? <p className="mt-2 text-xs text-red-600">{String(data.integration.last_error)}</p> : null}</div> : <p className="mt-4 text-sm text-slate-400">Nenhuma configuração de integração encontrada.</p>}</section> : null}
    {tab === 'security' ? <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold">Eventos de segurança</h2><div className="mt-4 space-y-2">{data.security.map((event) => <div key={String(event.id)} className="rounded-xl border border-slate-100 p-3"><strong className="text-xs">{String(event.event_type || 'Evento')}</strong><p className="mt-1 text-[11px] text-slate-400">{String(event.severity || '—')} · {dt(event.created_at)} · {String(event.path || event.source || '')}</p></div>)}{!data.security.length ? <p className="text-sm text-slate-400">Nenhum evento disponível ou seu papel não possui security.read.</p> : null}</div></section> : null}
    {tab === 'audit' ? <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold">Auditoria administrativa</h2><div className="mt-4 space-y-2">{data.audit.map((event) => <div key={String(event.id)} className="rounded-xl border border-slate-100 p-3"><strong className="text-xs">{String(event.action || 'Ação')}</strong><p className="mt-1 text-[11px] text-slate-400">{String(event.admin_email || 'admin')} · {dt(event.created_at)}</p></div>)}{!data.audit.length ? <p className="text-sm text-slate-400">Nenhuma ação visível ou seu papel não possui audit.read.</p> : null}</div></section> : null}

    {action ? <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/35 p-4 backdrop-blur-sm"><section className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl" role="dialog" aria-modal="true"><h2 className="text-xl font-semibold">Confirmar ação administrativa</h2><p className="mt-2 text-sm leading-6 text-slate-500">Ação: <strong>{action}</strong>. O motivo será salvo em audit log. Operações de billing usam idempotência.</p>{['extend_trial','courtesy'].includes(action) ? <label className="mt-4 block text-xs font-semibold">Dias<input type="number" min={1} max={30} value={days} onChange={(event) => setDays(Number(event.target.value))} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3"/></label> : null}<label className="mt-4 block text-xs font-semibold">Motivo<textarea value={reason} onChange={(event) => setReason(event.target.value)} rows={3} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3" placeholder="Explique por que esta ação é necessária"/></label><div className="mt-5 flex justify-end gap-2"><button onClick={() => { setAction(''); setReason('') }} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">Cancelar</button><button disabled={busy || reason.trim().length < 8} onClick={() => void runAction()} className="rounded-xl bg-[#0b2e63] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">{busy ? 'Processando…' : 'Confirmar'}</button></div></section></div> : null}
  </div>
}
