'use client'

import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'

type Payload = { generatedAt: string; quality: { mrrCoverage: number; churn: { value: null; reason: string } }; metrics: Record<string, number> }
function money(value: unknown) { return Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }) }

export default function AdminMetricsV2() {
  const [data, setData] = useState<Payload | null>(null)
  const [error, setError] = useState('')
  useEffect(() => { let active = true; void supabase.auth.getSession().then(async ({ data: auth }) => { const response = await fetch('/api/admin/control-center-v2', { headers: { Authorization: `Bearer ${auth.session?.access_token || ''}` }, cache: 'no-store' }); const payload = await response.json().catch(() => ({})); if (!active) return; if (!response.ok) setError(payload.error || 'Métricas indisponíveis.'); else setData(payload as Payload) }); return () => { active = false } }, [])
  if (!data) return <div className={`rounded-2xl border bg-white p-8 ${error ? 'border-red-100 text-red-700' : 'border-slate-200 text-slate-400'}`}>{error || 'Carregando métricas…'}</div>
  const m = data.metrics
  return <div className="space-y-5"><section className="rounded-3xl border border-slate-200 bg-white p-6"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-slate-400">SaaS Metrics</p><h1 className="mt-1 text-3xl font-semibold tracking-[-.04em] text-[#0b2e63]">Receita sem misturar caixa do cliente com receita da plataforma.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">MRR usa o último pagamento aprovado observado de empresas ativas. Quando uma métrica não possui base histórica suficiente, ela fica explicitamente indisponível.</p></section><section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><div className="rounded-2xl border border-slate-200 bg-white p-5"><span className="text-xs text-slate-400">MRR observado</span><strong className="mt-2 block text-2xl text-[#0b2e63]">{money(m.mrr)}</strong><small className="text-[11px] text-slate-400">cobertura {data.quality.mrrCoverage}%</small></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><span className="text-xs text-slate-400">ARR</span><strong className="mt-2 block text-2xl text-[#0b2e63]">{money(m.arr)}</strong><small className="text-[11px] text-slate-400">MRR × 12</small></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><span className="text-xs text-slate-400">Receita mês</span><strong className="mt-2 block text-2xl text-[#0b2e63]">{money(m.revenueMonth)}</strong><small className="text-[11px] text-slate-400">pagamentos aprovados</small></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><span className="text-xs text-slate-400">ARPU observado</span><strong className="mt-2 block text-2xl text-[#0b2e63]">{money(m.payingCompanies ? m.mrr / m.payingCompanies : 0)}</strong><small className="text-[11px] text-slate-400">MRR / pagantes</small></div></section><section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold">Crescimento mensal</h2><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-4"><span className="text-xs text-slate-400">Atual</span><strong className="mt-1 block text-xl">{money(m.revenueMonth)}</strong></div><div className="rounded-xl bg-slate-50 p-4"><span className="text-xs text-slate-400">Anterior</span><strong className="mt-1 block text-xl">{money(m.revenuePrevious)}</strong></div></div></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold">Churn / Retention / LTV</h2><p className="mt-3 rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-500">{data.quality.churn.reason} Retention, cohorts e LTV não são exibidos como números até a base temporal necessária estar materializada de forma confiável.</p></div></section></div>
}
