
WITH ns AS (SELECT oid,nspname,nspowner,nspacl FROM pg_namespace WHERE nspname IN ('public','api','orcaly_private')),
rels AS (SELECT c.*,n.nspname FROM pg_class c JOIN ns n ON n.oid=c.relnamespace WHERE c.relkind IN ('r','p','v','m','f','S') AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.classid='pg_class'::regclass AND d.objid=c.oid AND d.deptype='e')),
fns AS (SELECT p.*,n.nspname FROM pg_proc p JOIN ns n ON n.oid=p.pronamespace WHERE p.prokind IN ('f','p') AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.classid='pg_proc'::regclass AND d.objid=p.oid AND d.deptype='e')),
roles AS (SELECT oid,rolname FROM pg_roles WHERE rolname IN ('anon','authenticated','service_role','postgres','pg_database_owner')),
signature AS (
SELECT jsonb_build_object(
'scope',jsonb_build_object('application_schemas',ARRAY['api','orcaly_private','public'],'exclude_extension_owned_objects',true,'platform_managed_schemas_excluded',ARRAY['auth','storage','vault','cron','extensions','realtime','graphql','graphql_public','supabase_migrations'],'storage_exception','bucket config plus policy definitions only','effective_privilege_roles',ARRAY['anon','authenticated','service_role','postgres','pg_database_owner']),
'schemas',(SELECT coalesce(jsonb_agg(jsonb_build_object('name',nspname,'owner',pg_get_userbyid(nspowner),'acl',nspacl::text) ORDER BY nspname),'[]'::jsonb) FROM ns),
'relations',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',nspname,'name',relname,'kind',relkind,'owner',pg_get_userbyid(relowner),'rls_enabled',relrowsecurity,'rls_forced',relforcerowsecurity,'persistence',relpersistence,'replica_identity',relreplident,'options',reloptions,'acl',relacl::text,'comment',obj_description(oid,'pg_class'),'partition_key',CASE WHEN relkind='p' THEN pg_get_partkeydef(oid) END,'partition_bound',CASE WHEN relispartition THEN pg_get_expr(relpartbound,oid) END) ORDER BY nspname,relname),'[]'::jsonb) FROM rels),
'columns',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',c.nspname,'relation',c.relname,'position',a.attnum,'name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'type_schema',tn.nspname,'type_name',t.typname,'not_null',a.attnotnull,'default_or_generation_expression',pg_get_expr(ad.adbin,ad.adrelid),'generated',a.attgenerated,'identity',a.attidentity,'collation',CASE WHEN a.attcollation<>0 THEN a.attcollation::regcollation::text END,'storage',a.attstorage,'acl',a.attacl::text,'comment',col_description(a.attrelid,a.attnum)) ORDER BY c.nspname,c.relname,a.attnum),'[]'::jsonb) FROM rels c JOIN pg_attribute a ON a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped JOIN pg_type t ON t.oid=a.atttypid JOIN pg_namespace tn ON tn.oid=t.typnamespace LEFT JOIN pg_attrdef ad ON ad.adrelid=a.attrelid AND ad.adnum=a.attnum WHERE c.relkind<>'S'),
'types',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'name',t.typname,'kind',t.typtype,'category',t.typcategory,'owner',pg_get_userbyid(t.typowner),'base_type',CASE WHEN t.typbasetype<>0 THEN format_type(t.typbasetype,t.typtypmod) END,'not_null',t.typnotnull,'default',t.typdefault,'acl',t.typacl::text,'enum_labels',(SELECT jsonb_agg(e.enumlabel ORDER BY e.enumsortorder) FROM pg_enum e WHERE e.enumtypid=t.oid),'composite_relation',CASE WHEN t.typrelid<>0 THEN t.typrelid::regclass::text END,'range',(SELECT jsonb_build_object('subtype',format_type(r.rngsubtype,NULL),'collation',r.rngcollation::regcollation::text,'canonical',r.rngcanonical::regproc::text,'subdiff',r.rngsubdiff::regproc::text) FROM pg_range r WHERE r.rngtypid=t.oid)) ORDER BY n.nspname,t.typname),'[]'::jsonb) FROM pg_type t JOIN ns n ON n.oid=t.typnamespace WHERE t.typelem=0 AND NOT EXISTS(SELECT 1 FROM pg_depend d WHERE d.classid='pg_type'::regclass AND d.objid=t.oid AND d.deptype='e')),
'sequences',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',c.nspname,'name',c.relname,'type',format_type(s.seqtypid,NULL),'start',s.seqstart,'increment',s.seqincrement,'min',s.seqmin,'max',s.seqmax,'cache',s.seqcache,'cycle',s.seqcycle,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'owned_by',(SELECT jsonb_agg(jsonb_build_object('table',d.refobjid::regclass::text,'column_position',d.refobjsubid,'dependency_type',d.deptype) ORDER BY d.refobjid,d.refobjsubid) FROM pg_depend d WHERE d.classid='pg_class'::regclass AND d.objid=c.oid AND d.deptype IN ('a','i'))) ORDER BY c.nspname,c.relname),'[]'::jsonb) FROM rels c JOIN pg_sequence s ON s.seqrelid=c.oid),
'constraints',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'relation',CASE WHEN x.conrelid<>0 THEN x.conrelid::regclass::text END,'domain',CASE WHEN x.contypid<>0 THEN x.contypid::regtype::text END,'name',x.conname,'kind',x.contype,'definition',pg_get_constraintdef(x.oid,false),'validated',x.convalidated,'deferrable',x.condeferrable,'initially_deferred',x.condeferred,'no_inherit',x.connoinherit) ORDER BY n.nspname,x.conrelid::regclass::text,x.conname),'[]'::jsonb) FROM pg_constraint x JOIN ns n ON n.oid=x.connamespace),
'indexes',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',c.nspname,'table',c.relname,'name',ic.relname,'definition',pg_get_indexdef(i.indexrelid),'valid',i.indisvalid,'ready',i.indisready,'unique',i.indisunique,'primary',i.indisprimary,'exclusion',i.indisexclusion,'replica_identity',i.indisreplident,'owner',pg_get_userbyid(ic.relowner),'options',ic.reloptions) ORDER BY c.nspname,c.relname,ic.relname),'[]'::jsonb) FROM pg_index i JOIN rels c ON c.oid=i.indrelid JOIN pg_class ic ON ic.oid=i.indexrelid),
'views',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',nspname,'name',relname,'kind',relkind,'definition',pg_get_viewdef(oid,false),'options',reloptions,'owner',pg_get_userbyid(relowner),'acl',relacl::text,'populated',CASE WHEN relkind='m' THEN relispopulated END) ORDER BY nspname,relname),'[]'::jsonb) FROM rels WHERE relkind IN ('v','m')),
'functions',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',p.nspname,'name',p.proname,'identity_args',pg_get_function_identity_arguments(p.oid),'arguments',pg_get_function_arguments(p.oid),'return_type',pg_get_function_result(p.oid),'kind',p.prokind,'language',l.lanname,'security_definer',p.prosecdef,'owner',pg_get_userbyid(p.proowner),'proconfig',p.proconfig,'acl',p.proacl::text,'volatility',p.provolatile,'strict',p.proisstrict,'leakproof',p.proleakproof,'parallel',p.proparallel,'cost',p.procost,'rows',p.prorows,'definition',pg_get_functiondef(p.oid),'comment',obj_description(p.oid,'pg_proc')) ORDER BY p.nspname,p.proname,pg_get_function_identity_arguments(p.oid)),'[]'::jsonb) FROM fns p JOIN pg_language l ON l.oid=p.prolang),
'triggers',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',c.nspname,'table',c.relname,'name',t.tgname,'definition',pg_get_triggerdef(t.oid,false),'enabled',t.tgenabled,'function',t.tgfoid::regprocedure::text,'constraint',CASE WHEN t.tgconstraint<>0 THEN (SELECT conname FROM pg_constraint WHERE oid=t.tgconstraint) END) ORDER BY c.nspname,c.relname,t.tgname),'[]'::jsonb) FROM pg_trigger t JOIN rels c ON c.oid=t.tgrelid WHERE NOT t.tgisinternal),
'policies',(SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY schemaname,tablename,policyname),'[]'::jsonb) FROM pg_policies p WHERE schemaname IN ('public','api','orcaly_private')),
'storage_policies',(SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY schemaname,tablename,policyname),'[]'::jsonb) FROM pg_policies p WHERE schemaname='storage'),
'bucket_configuration',(SELECT coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'public',public,'file_size_limit',file_size_limit,'allowed_mime_types',allowed_mime_types) ORDER BY id),'[]'::jsonb) FROM storage.buckets),
'effective_schema_privileges',(SELECT coalesce(jsonb_agg(jsonb_build_object('role',r.rolname,'schema',n.nspname,'USAGE',has_schema_privilege(r.oid,n.oid,'USAGE'),'CREATE',has_schema_privilege(r.oid,n.oid,'CREATE')) ORDER BY r.rolname,n.nspname),'[]'::jsonb) FROM roles r CROSS JOIN ns n),
'effective_relation_privileges',(SELECT coalesce(jsonb_agg(jsonb_build_object('role',r.rolname,'schema',c.nspname,'relation',c.relname,'privilege',v.p,'effective',CASE WHEN c.relkind='S' THEN has_sequence_privilege(r.oid,c.oid,v.p) ELSE has_table_privilege(r.oid,c.oid,v.p) END) ORDER BY r.rolname,c.nspname,c.relname,v.p),'[]'::jsonb) FROM roles r CROSS JOIN rels c CROSS JOIN LATERAL (SELECT p FROM unnest(CASE WHEN c.relkind='S' THEN ARRAY['USAGE','SELECT','UPDATE'] ELSE ARRAY['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'] END) p) v),
'effective_column_privileges',(SELECT coalesce(jsonb_agg(jsonb_build_object('role',r.rolname,'schema',c.nspname,'relation',c.relname,'column',a.attname,'SELECT',has_column_privilege(r.oid,c.oid,a.attnum,'SELECT'),'INSERT',has_column_privilege(r.oid,c.oid,a.attnum,'INSERT'),'UPDATE',has_column_privilege(r.oid,c.oid,a.attnum,'UPDATE'),'REFERENCES',has_column_privilege(r.oid,c.oid,a.attnum,'REFERENCES')) ORDER BY r.rolname,c.nspname,c.relname,a.attnum),'[]'::jsonb) FROM roles r CROSS JOIN rels c JOIN pg_attribute a ON a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped WHERE c.relkind<>'S'),
'effective_function_privileges',(SELECT coalesce(jsonb_agg(jsonb_build_object('role',r.rolname,'schema',p.nspname,'function',p.proname,'identity_args',pg_get_function_identity_arguments(p.oid),'EXECUTE',has_function_privilege(r.oid,p.oid,'EXECUTE')) ORDER BY r.rolname,p.nspname,p.proname,pg_get_function_identity_arguments(p.oid)),'[]'::jsonb) FROM roles r CROSS JOIN fns p),
'default_privileges',(SELECT coalesce(jsonb_agg(jsonb_build_object('owner',pg_get_userbyid(a.defaclrole),'schema',n.nspname,'object_type',a.defaclobjtype,'acl',a.defaclacl::text) ORDER BY pg_get_userbyid(a.defaclrole),n.nspname,a.defaclobjtype),'[]'::jsonb) FROM pg_default_acl a LEFT JOIN pg_namespace n ON n.oid=a.defaclnamespace WHERE a.defaclnamespace=0 OR n.nspname IN ('public','api','orcaly_private')),
'extension_assertions',(SELECT coalesce(jsonb_agg(jsonb_build_object('name',e.extname,'version',e.extversion,'schema',n.nspname,'owner',pg_get_userbyid(e.extowner)) ORDER BY e.extname),'[]'::jsonb) FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace),
'role_security_attributes',(SELECT coalesce(jsonb_agg(jsonb_build_object('role',r.rolname,'superuser',a.rolsuper,'inherit',a.rolinherit,'bypassrls',a.rolbypassrls,'can_login',a.rolcanlogin) ORDER BY r.rolname),'[]'::jsonb) FROM roles r JOIN pg_roles a ON a.oid=r.oid),
'platform_prerequisite_references',(SELECT coalesce(jsonb_agg(jsonb_build_object('source',pg_describe_object(d.classid,d.objid,d.objsubid),'target',pg_describe_object(d.refclassid,d.refobjid,d.refobjsubid),'dependency_type',d.deptype) ORDER BY pg_describe_object(d.classid,d.objid,d.objsubid),pg_describe_object(d.refclassid,d.refobjid,d.refobjsubid),d.deptype),'[]'::jsonb) FROM pg_depend d WHERE ((d.classid='pg_class'::regclass AND d.objid IN (SELECT oid FROM rels)) OR (d.classid='pg_proc'::regclass AND d.objid IN (SELECT oid FROM fns)) OR (d.classid='pg_constraint'::regclass AND d.objid IN (SELECT c.oid FROM pg_constraint c JOIN ns n ON n.oid=c.connamespace)) OR (d.classid='pg_rewrite'::regclass AND d.objid IN (SELECT w.oid FROM pg_rewrite w JOIN rels c ON c.oid=w.ev_class))) AND ((d.refclassid='pg_class'::regclass AND d.refobjid IN (SELECT c.oid FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname IN ('auth','storage','extensions','vault','cron'))) OR (d.refclassid='pg_proc'::regclass AND d.refobjid IN (SELECT p.oid FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname IN ('auth','storage','extensions','vault','cron'))) OR (d.refclassid='pg_type'::regclass AND d.refobjid IN (SELECT t.oid FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace WHERE n.nspname IN ('auth','storage','extensions','vault','cron'))))),
'platform_prerequisite_object_assertions',jsonb_build_object('auth_users_present',to_regclass('auth.users') IS NOT NULL,'storage_buckets_present',to_regclass('storage.buckets') IS NOT NULL,'storage_objects_present',to_regclass('storage.objects') IS NOT NULL,'auth_uid_function_present',to_regprocedure('auth.uid()') IS NOT NULL,'auth_jwt_function_present',to_regprocedure('auth.jwt()') IS NOT NULL,'auth_role_function_present',to_regprocedure('auth.role()') IS NOT NULL,'vault_schema_present',to_regnamespace('vault') IS NOT NULL),
'inheritance',(SELECT coalesce(jsonb_agg(jsonb_build_object('child_schema',c.nspname,'child',c.relname,'parent',i.inhparent::regclass::text,'position',i.inhseqno) ORDER BY c.nspname,c.relname,i.inhseqno),'[]'::jsonb) FROM pg_inherits i JOIN rels c ON c.oid=i.inhrelid)

) AS payload
)
SELECT payload, encode(sha256(convert_to(payload::text,'UTF8')),'hex') AS signature_sha256, payload::text AS signature_digest_representation, statement_timestamp() AS captured_at_utc FROM signature
