import Link from 'next/link'
import {randomUUID} from 'node:crypto'
import {getPersonalProductAccess} from '@/lib/ecosystem/server'
import {automationOperations,automationJobStates,type AutomationOverview} from '@/lib/wealth/automation'
import {recurrenceStatuses} from '@/lib/wealth/recurrence'
import {integer,formatFinancialDate} from '@/lib/wealth/core'
import {WealthAutomationForm} from '@/components/wealth/WealthAutomationForm'
import s from '@/components/wealth/calendar.module.css'
export default async function AutomationPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const access=await getPersonalProductAccess('wealth','wealth.read');if(!access.allowed||!access.identity)return <><h1>Automation Center</h1><p>Seu acesso ao Wealth não está liberado.</p><Link href="/apps">Voltar ao Hub</Link></>
 const raw=await searchParams;let page:number,days:number|null,status:string|null
 try{page=integer(raw.page??1,1,100000);days=raw.days?integer(raw.days,7,365):null;if(days!==null&&![7,30,90,365].includes(days))throw Error();status=raw.status===undefined||raw.status===''?null:String(raw.status);if(Array.isArray(raw.status)||(status&&!Object.hasOwn(recurrenceStatuses,status)))throw Error()}
 catch{return <><h1>Revise os filtros</h1><Link href="/apps/wealth/automacoes">Limpar filtros</Link></>}
 const r=await access.identity.db.rpc('wealth_automation_overview',{p_page:page,p_days:days,p_status:status});if(r.error)throw Error('Não foi possível consultar as automações.')
 const view=r.data as AutomationOverview,write=(await getPersonalProductAccess('wealth','wealth.write')).allowed,total=[view.schedule_count,view.command_count,view.occurrence_count].map(BigInt).reduce((a,b)=>a>b?a:b,BigInt(0)),pages=(total+BigInt(24))/BigInt(25),date=(v:string)=>new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'}).format(new Date(v)),href=(n:number)=>`?${new URLSearchParams({page:String(n),days:String(view.days),...(status?{status}:{})})}`
 return <div className={s.page}><nav className={s.nav} aria-label="Automações Wealth"><Link href="/apps/wealth">Visão geral</Link><Link href="/apps/wealth/automacoes" aria-current="page">Automações</Link><Link href="/apps/wealth/recorrencias">Contas e recorrências</Link><Link href="/apps/wealth/timeline">Timeline</Link></nav>
 <header className={s.hero}><div><span className={s.kicker}>Rotinas sob seu controle</span><h1>Automation Center</h1><p>Acompanhe seus agendamentos, entenda o que está pendente e autorize a próxima ação.</p></div><aside>Executor periódico no banco: <strong>{view.clock==='ACTIVE'?'Ativo':view.clock==='PAUSED'?'Pausado':'NOT_CONFIGURED'}</strong>. Esta leitura não confirma a disponibilidade de workers externos. Um agendamento ativo pode aguardar execução.</aside></header>
 <p className={s.notice}>Recorrências criam lançamentos declarados. Não pagam contas, compram ativos nem enviam mensagens. O controle usa o mesmo motor e os mesmos agendamentos da Central de Recorrências.</p>
 <dl className={s.stats}><div><dt>Agendamentos ativos</dt><dd>{view.summary.active}<small>{view.summary.paused} pausados · {view.summary.closed} encerrados</small></dd></div><div><dt>Trabalhos vencidos na fila</dt><dd>{view.summary.due}<small>Até 10 por execução manual; uma próxima ocorrência pode entrar na fila depois.</small></dd></div><div><dt>Precisam de revisão</dt><dd>{view.summary.attention}<small>Confira o agendamento antes de autorizar uma nova tentativa.</small></dd></div></dl>
 {write&&<details className={s.details}><summary>Executar pendências agora</summary><WealthAutomationForm operation="run" token={randomUUID()}/><p className={s.muted}>Repetir o mesmo envio recupera o mesmo resultado. Para outro lote, atualize a página e confirme uma nova execução. Não há ativação de cron por este botão.</p></details>}
 <form className={s.filters}><label>Histórico registrado nos últimos<select name="days" defaultValue={view.days}>{[7,30,90,365].map(d=><option key={d} value={d}>{d} dias</option>)}</select></label><label>Estado do agendamento<select name="status" defaultValue={status??''}><option value="">Usar preferências</option>{Object.entries(recurrenceStatuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><button className={s.button}>Consultar central</button></form>
 {write&&<details className={s.details}><summary>Preferências da central</summary><p className={s.muted}>Estas preferências alteram a consulta. Para suspender a geração de uma conta, pause o agendamento abaixo.</p><WealthAutomationForm operation="configure" token={randomUUID()} version={view.preferences.version} preferences={view.preferences}/></details>}
 <section className={s.section}><h2>Agendamentos e fila</h2><p>{view.schedule_count} agendamento(s) no filtro · página {page} · até 25 por página.</p>{view.schedules.length?<ul className={s.agenda}>{view.schedules.map(schedule=><li key={schedule.id} data-automation-schedule={schedule.id} className={s.bill}><div className={s.billHeader}><h3>{schedule.title}</h3><span className={s.tag}>{recurrenceStatuses[schedule.status]}</span></div><p>Próxima data registrada: {formatFinancialDate(schedule.next_date)} · {schedule.timezone}. {schedule.pause_reason==='access_unavailable'?'Pausado por falta de permissão; a retomada precisa de confirmação.':''}</p>
 {schedule.job?<p>Trabalho: {automationJobStates[schedule.job.status]} · {schedule.job.attempts}/{schedule.job.max_attempts} tentativa(s) · elegível após {date(schedule.job.run_after)} (São Paulo).</p>:<p className={s.muted}>Sem trabalho para a próxima ocorrência nesta consulta. Um agendamento pausado ou encerrado não gera novas declarações.</p>}
 <Link href={`/apps/wealth/recorrencias?schedule=${schedule.id}`}>Revisar conta e condições</Link>
 {write&&['active','paused'].includes(schedule.status)&&<details className={s.details}><summary>Controlar este agendamento</summary><WealthAutomationForm operation={schedule.status==='active'?'pause':'resume'} id={schedule.id} version={schedule.version} token={randomUUID()}/><WealthAutomationForm operation="cancel" id={schedule.id} version={schedule.version} token={randomUUID()}/></details>}
 {write&&schedule.job?.can_retry&&<details className={s.details}><summary>Revisar tentativa interrompida</summary><p>Uma falha interrompeu este trabalho. A central não mostra mensagens internas do servidor. Confira as condições na conta; se o problema persistir, pause o agendamento e procure suporte.</p><WealthAutomationForm operation="retry" id={schedule.job.id} attempts={schedule.job.attempts} token={randomUUID()}/></details>}</li>)}</ul>:<p className={s.empty}>Nenhum agendamento neste filtro. Crie uma conta recorrente ou ajuste a consulta.</p>}</section>
 <section className={s.section}><h2>Solicitações concluídas na central</h2><p>{view.command_count} solicitação(ões) nos últimos {view.days} dias. Falhas que impediram a transação não entram como sucesso.</p>{view.commands.length?<ol className={s.agenda}>{view.commands.map(c=><li key={c.id} className={s.bill}><h3>{automationOperations[c.operation]}</h3><p><time dateTime={c.recorded_at}>{date(c.recorded_at)}</time> · São Paulo</p>{c.operation==='run'&&<p>{c.result.generated??0} declaração(ões) gerada(s), {c.result.skipped??0} sem geração, {c.result.retrying??0} em nova tentativa, {c.result.needs_attention??0} para revisão.</p>}</li>)}</ol>:<p className={s.empty}>Nenhuma solicitação concluída neste período.</p>}</section>
 <section className={s.section}><h2>Ocorrências registradas pelo motor</h2><p>{view.occurrence_count} ocorrência(s) nos últimos {view.days} dias. Inclui execução manual ou por worker; o ledger não identifica qual delas gerou cada registro.</p>{view.occurrences.length?<ol className={s.agenda}>{view.occurrences.map(o=><li key={`${o.schedule_id}:${o.occurrence_index}`} className={s.bill}><h3>{o.title}</h3><p>Data declarada: {formatFinancialDate(o.financial_date)} · registro: {date(o.created_at)} (São Paulo).</p>{o.entry_id?<Link href={`/apps/wealth/lancamentos/${o.entry_id}`}>Abrir lançamento declarado</Link>:<p>O lançamento relacionado não está mais disponível.</p>}</li>)}</ol>:<p className={s.empty}>Nenhuma ocorrência registrada neste período.</p>}</section>
 <nav className={s.nav} aria-label="Paginação Automation Center">{page>1&&<Link href={href(page-1)}>Página anterior</Link>}{BigInt(page)<pages&&<Link href={href(page+1)}>Próxima página</Link>}</nav>
 <section className={s.section}><h2>Escopo desta central</h2><p>Geração de recorrências, pausas, retomadas, cancelamentos e revisão de trabalhos próprios. O executor periódico é administrado separadamente por ambiente. Email, ações bancárias e automações externas: NOT_CONFIGURED. Nenhuma integração ou compartilhamento Family autoriza execução por outra pessoa.</p></section></div>
}
