import Link from 'next/link'
import {getPersonalProductAccess} from '@/lib/ecosystem/server'
import {feeFilters,readFeeAnalysis} from '@/lib/wealth/fees'
import {formatMoney,formatFinancialDate} from '@/lib/wealth/core'
import s from '@/components/wealth/calendar.module.css'

export default async function FeePage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const access=await getPersonalProductAccess('wealth','wealth.read')
 if(!access.allowed||!access.identity)return <><h1>Fee Analyzer</h1><p>Seu acesso ao Wealth não está liberado.</p><Link href="/apps">Voltar ao Hub</Link></>
 const {db,user}=access.identity,profile=await db.from('wealth_profiles').select('timezone').eq('user_id',user.id).maybeSingle()
 if(profile.error)throw Error('Não foi possível confirmar o período local.')
 const zone=profile.data?.timezone??'America/Sao_Paulo',today=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
 let filters
 try{filters=feeFilters(await searchParams,today)}catch{return <><h1>Revise os filtros</h1><p>Use datas válidas em um intervalo de até 366 dias.</p><Link href="/apps/wealth/tarifas">Limpar filtros</Link></>}
 const {from,to,page,portfolio}=filters,r=await db.rpc('wealth_fee_analysis',{p_from:from,p_to:to,p_page:page,p_portfolio:portfolio})
 if(r.error?.code==='42501')return <><h1>Análise indisponível</h1><p>A carteira não está disponível para esta conta.</p><Link href="/apps/wealth/tarifas">Consultar suas carteiras</Link></>
 if(r.error)throw Error('Não foi possível consultar as tarifas.')
 const v=readFeeAnalysis(r.data),total=BigInt(v.record_count)>BigInt(v.portfolio_count)?BigInt(v.record_count):BigInt(v.portfolio_count),pages=(total+BigInt(24))/BigInt(25)
 const href=(n=1,id=portfolio)=>`?${new URLSearchParams({from,to,page:String(n),...(id?{portfolio:id}:{})})}`
 return <div className={s.page}>
 <nav className={s.nav} aria-label="Custos Wealth"><Link href="/apps/wealth">Visão geral</Link><Link href="/apps/wealth/tarifas" aria-current="page">Tarifas e impostos</Link><Link href="/apps/wealth/carteiras">Carteiras</Link></nav>
 <header className={s.hero}><div><span className={s.kicker}>Entenda os custos registrados</span><h1>Fee Analyzer</h1><p>Observe suas tarifas, compare períodos e confira a origem de cada valor antes de decidir o que revisar.</p></div><aside>Fonte: movimentos declarados nas carteiras reais, em BRL. Inclui posições arquivadas. Nenhum registro comprova pagamento bancário.</aside></header>
 <p className={s.notice}>Cobertura parcial: ausência de registro não significa custo zero. Taxas embutidas de fundos, custos de provedores e cobranças bancárias: NOT_CONFIGURED. Não calculamos rentabilidade líquida nem imposto devido a partir destes registros.</p>
 <form className={s.filters} aria-label="Período da análise"><label>Data inicial<input name="from" type="date" min="1900-01-01" max="2200-12-31" required defaultValue={from}/></label><label>Data final<input name="to" type="date" min="1900-01-01" max="2200-12-31" required defaultValue={to}/></label>{portfolio&&<input type="hidden" name="portfolio" value={portfolio}/>}<button className={s.button}>Analisar período</button></form>
 <p className={s.muted}>Datas financeiras inclusivas, sem conversão de fuso. O período inicial usa seu fuso: {zone}. {formatFinancialDate(from)} a {formatFinancialDate(to)} · {v.days} dia(s). Filtro: {v.selected?.name??'Todas as carteiras reais'}. {portfolio&&<Link href={href(1,null)}>Remover filtro de carteira</Link>}</p>
 {v.selected?.kind==='lab'&&<p className={s.notice}>Esta carteira é um cenário do Portfolio Lab. Suas hipóteses não geram custos realizados e ficam fora desta análise.</p>}
 <dl className={s.stats}><div><dt>Tarifas declaradas</dt><dd data-fee-total>{formatMoney(v.fees)}<small>Somente movimentos do tipo tarifa.</small></dd></div><div><dt>Impostos declarados</dt><dd data-tax-total>{formatMoney(v.taxes)}<small>Separados das tarifas; não representam apuração fiscal.</small></dd></div><div><dt>Cobertura de registros</dt><dd>{v.covered_portfolios} / {v.portfolio_count}<small>Carteiras reais com registro neste período · {v.record_count} evento(s) em {v.holding_count} posição(ões). {v.lab_count} cenário(s) Lab fora dos totais.</small></dd></div></dl>
 <section className={s.section}><h2>Comparação com o período anterior</h2>{v.previous?<><p>{formatFinancialDate(v.previous.from)} a {formatFinancialDate(v.previous.to)} · mesmos {v.days} dias · {v.previous.records} registro(s). A diferença descreve o histórico informado; não comprova aumento de preço, economia ou mudança de cobrança.</p><dl className={s.stats}>{(['fees','taxes'] as const).map(k=><div key={k}><dt>{k==='fees'?'Tarifas':'Impostos'} no período anterior</dt><dd>{formatMoney(v.previous![k])}<small>Diferença nos registros: {formatMoney((BigInt(v[k])-BigInt(v.previous![k])).toString())}</small></dd></div>)}</dl></>:<p>A comparação completa ultrapassa o início do intervalo suportado (01/01/1900) e não está disponível.</p>}</section>
 <section className={s.section}><h2>Custos por mês</h2><p>Somente os dias selecionados de cada mês. Meses sem registro não comprovam ausência de custo.</p>{v.months.length?<ul className={s.agenda}>{v.months.map(m=><li className={s.bill} key={m.month}><h3>{m.month.slice(5)}/{m.month.slice(0,4)}</h3><p>Tarifas: {formatMoney(m.fees)} · impostos: {formatMoney(m.taxes)} · {m.records} registro(s).</p></li>)}</ul>:<p className={s.empty}>Nenhum custo registrado neste período. Confira os extratos e registre apenas valores conhecidos na carteira de origem.</p>}</section>
 <section className={s.section}><h2>Carteiras no escopo</h2><p>{v.portfolio_count} carteira(s) real(is). Até 25 por página; os totais acima incluem todas as páginas.</p>{v.portfolios.length?<ul className={s.agenda}>{v.portfolios.map(p=><li className={s.bill} key={p.id}><h3>{p.name}</h3><p>{p.records} registro(s) · tarifas: {formatMoney(p.fees)} · impostos: {formatMoney(p.taxes)}.</p><nav className={s.nav} aria-label={`Ações de ${p.name}`}><Link href={href(1,p.id)}>Analisar somente esta carteira</Link><Link href={`/apps/wealth/carteiras/${p.id}#movimentos`}>Revisar movimentos na origem</Link></nav></li>)}</ul>:<p className={s.empty}>Nenhuma carteira real neste filtro.</p>}</section>
 <section className={s.section}><h2>Registros que compõem a análise</h2><p>{v.record_count} evento(s) · página {page} · até 25 registros, por data financeira e identificador. Os títulos de posição e carteira refletem seus nomes atuais.</p>{v.records.length?<ol className={s.agenda}>{v.records.map(t=><li className={s.bill} key={t.id} data-fee-record={t.id}><div className={s.billHeader}><h3>{t.type==='fee'?'Tarifa':'Imposto'} · {t.title}</h3><strong>{formatMoney(t.amount_cents)}</strong></div><p><time dateTime={t.financial_date}>{formatFinancialDate(t.financial_date)}</time> · {t.portfolio_name}{t.archived?' · posição arquivada':''}</p><p>Referência declarada: {t.reference}</p><Link href={`/apps/wealth/carteiras/${t.portfolio_id}#movimentos`}>Revisar carteira de origem</Link></li>)}</ol>:<p className={s.empty}>Nenhum registro nesta página.</p>}</section>
 <nav className={s.nav} aria-label="Paginação de tarifas">{page>1&&<Link href={href(page-1)}>Página anterior</Link>}{BigInt(page)<pages&&<Link href={href(page+1)}>Próxima página</Link>}</nav>
 <section className={s.section}><h2>Próxima revisão</h2><p>Compare as referências registradas com os documentos que você possui. Para registrar uma tarifa ou imposto conhecido, abra a carteira, selecione a posição e use “Registrar movimento”. Quantidade zero; esse evento não cria outra despesa de caixa. O histórico permanece imutável.</p><Link href="/apps/wealth/carteiras">Abrir suas carteiras</Link><p className={s.muted}>Relações Family, produtos empresariais e assinaturas One não concedem acesso a esta análise pessoal. Nenhum dado é enviado a um provedor externo.</p></section>
 </div>
}
