import Link from 'next/link'
import { randomUUID } from 'node:crypto'
import { getPersonalProductAccess } from '@/lib/ecosystem/server'
import { formatMoney, formatFinancialDate, moneyInputValue, type WealthEntry, type WealthGoal } from '@/lib/wealth/core'
import { readWealthSummary } from '@/lib/wealth/summary'
import { progressPercent } from '@/lib/wealth/lifecycle'
import WealthForm from '@/components/wealth/WealthForm'
import GoalSimulator from '@/components/wealth/GoalSimulator'
import styles from '@/components/ecosystem/ecosystem.module.css'

const kinds = { income: 'Receita', expense: 'Despesa', asset: 'Ativo', liability: 'Passivo' }
const categories = { salary: 'Renda', housing: 'Moradia', food: 'Alimentação', transport: 'Transporte', education: 'Educação', health: 'Saúde', leisure: 'Lazer', investment: 'Investimento', property: 'Bem', loan: 'Dívida', other: 'Outros' }

export default async function WealthPage() {
  const access = await getPersonalProductAccess('wealth', 'wealth.read')
  if (!access.allowed || !access.identity) return <><p className={styles.eyebrow}>Orçaly Wealth · Espaço pessoal</p><h1>Seu futuro começa<br />com clareza.</h1><div className={styles.notice}>O acesso ao Wealth ainda não está liberado para esta conta neste ambiente. Seus produtos atuais continuam disponíveis no App Hub.</div><Link className={styles.textButton} href="/apps">← Voltar ao App Hub</Link><GoalSimulator /></>
  const { db, user } = access.identity
  const [entryResult, goalResult, profileResult] = await Promise.all([
    db.from('wealth_entries').select('id,title,kind,category,amount_cents,financial_date,currency,recurrence,valuation_status').eq('user_id', user.id).is('archived_at',null).order('financial_date', { ascending: false }).order('id').limit(15),
    db.from('wealth_goals').select('id,title,target_cents,saved_cents,monthly_contribution_cents,target_date').eq('user_id', user.id).is('archived_at',null).order('target_date').order('id').limit(15),
    db.from('wealth_profiles').select('monthly_income_cents,monthly_budget_cents,dependents,emergency_months,timezone').eq('user_id', user.id).maybeSingle(),
  ])
  if (entryResult.error || goalResult.error || profileResult.error) return <><h1>Orçaly Wealth</h1><div className={styles.notice}>Não foi possível consultar seu espaço financeiro. Nenhum saldo foi estimado. Tente novamente em alguns instantes.</div><Link href="/apps">Voltar ao App Hub</Link></>
  const entries = (entryResult.data ?? []) as WealthEntry[]
  const goals = (goalResult.data ?? []) as WealthGoal[]
  const profile = profileResult.data
  const today = new Intl.DateTimeFormat('en-CA', { timeZone: profile?.timezone || 'America/Sao_Paulo', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date())
  const summaryResult = await db.rpc('wealth_summary',{p_month:`${today.slice(0,7)}-01`})
  let totals
  try { if(summaryResult.error)throw Error('summary_unavailable');totals=readWealthSummary(summaryResult.data) }
  catch { return <><h1>Orçaly Wealth</h1><div className={styles.notice}>Não foi possível confirmar os totais integrais. Nenhum saldo foi estimado. Tente novamente.</div></> }
  const moneyValue = (cents?: number) => moneyInputValue(cents || 0)
  const write = await getPersonalProductAccess('wealth', 'wealth.write')
  return <><Link className={styles.textButton} href="/apps">← App Hub</Link><p className={styles.eyebrow}>Orçaly Wealth · Contexto pessoal</p><h1>Seu dinheiro.<br />Suas possibilidades.</h1><p className={styles.lead}>Informações que você registrou, separadas dos dados empresariais. Moeda: BRL. Período do fluxo de caixa: {today.slice(0, 7)}.</p>
    <Link className={styles.textButton} href="/apps/wealth/lancamentos">Consultar histórico e exportar lançamentos →</Link>
    <Link className={styles.textButton} href="/apps/wealth/saude">Saúde financeira e indicadores explicados →</Link>
    <Link className={styles.textButton} href="/apps/wealth/carteiras">Carteiras, movimentos e cenários →</Link><Link className={styles.textButton} href="/apps/wealth/patrimonio">Patrimônio, composição e evolução →</Link>
    <Link className={styles.textButton} href="/apps/wealth/dividas">Central de dívidas e estratégias de quitação →</Link>
    <Link className={styles.textButton} href="/apps/wealth/documentos">Cofre de documentos pessoais →</Link>
    <Link className={styles.textButton} href="/apps/wealth/timeline">Timeline das suas atividades →</Link>
    <Link className={styles.textButton} href="/apps/wealth/familia">Family: conexões e compartilhamentos →</Link>
    <Link className={styles.textButton} href="/apps/wealth/shield">Shield: proteção patrimonial e seguros declarados →</Link>
    <Link className={styles.textButton} href="/apps/wealth/tarifas">Fee Analyzer: tarifas e impostos declarados →</Link>
    <Link className={styles.textButton} href="/apps/wealth/automacoes">Automation Center: rotinas sob seu controle →</Link>
    <p className={styles.notice}>Totais calculados com todos os {totals.entryCount} lançamentos ativos. A lista abaixo mostra até 15 registros recentes. Arquivados não entram nos totais.</p>
    {totals.unknownValuations&&totals.unknownValuations!=='0'&&<p className={styles.notice}>Patrimônio parcial: {totals.unknownValuations} posições sem avaliação. Valores desconhecidos ficam fora dos totais.</p>}<dl className={styles.metricGrid}><div className={styles.metric}><dt>Patrimônio líquido registrado</dt><dd>{formatMoney(totals.netWorth)}</dd></div><div className={styles.metric}><dt>Fluxo de caixa do mês</dt><dd>{formatMoney(totals.cashFlow)}</dd></div><div className={styles.metric}><dt>Ativos / passivos registrados</dt><dd>{formatMoney(totals.assets)}<small> / {formatMoney(totals.liabilities)}</small></dd></div></dl>
    <div className={styles.notice}>Dados de mercado não configurados. Os valores de ativos e passivos são declarados por você; não são cotações. A recorrência declarada no lançamento é uma anotação. Para gerar registros nas próximas datas, <Link href="/apps/wealth/recorrencias">gerencie seus agendamentos</Link>. Consulte datas e compromissos no <Link href="/apps/wealth/calendario">Calendário financeiro</Link>.</div>
    {write.allowed && <section className={styles.panel}><h2>Seu perfil e orçamento</h2><p>Defina sua renda, limite mensal e horizonte da reserva. Estes dados não definem um perfil regulado de investidor.</p><WealthForm kind="profile" idempotencyKey={randomUUID()}><label>Renda mensal declarada (R$)<input name="monthly_income" inputMode="decimal" defaultValue={moneyValue(profile?.monthly_income_cents)} required /></label><label>Orçamento mensal (R$)<input name="monthly_budget" inputMode="decimal" defaultValue={moneyValue(profile?.monthly_budget_cents)} required /></label><label>Dependentes<input name="dependents" type="number" min="0" max="50" defaultValue={profile?.dependents || 0} required /></label><label>Reserva em meses de orçamento<input name="emergency_months" type="number" min="1" max="36" defaultValue={profile?.emergency_months || 6} required /></label><label>Seu fuso horário<select name="timezone" defaultValue={profile?.timezone || 'America/Sao_Paulo'}><option value="America/Sao_Paulo">Brasília</option><option value="America/Manaus">Manaus</option><option value="America/Rio_Branco">Rio Branco</option><option value="America/Noronha">Fernando de Noronha</option><option value="Europe/Lisbon">Lisboa</option><option value="UTC">UTC</option></select></label></WealthForm></section>}
    {profile && <section className={styles.panel}><h2>Como está seu orçamento?</h2><p>Receitas registradas no mês: {formatMoney(totals.income)}. Despesas: {formatMoney(totals.expenses)} de {formatMoney(profile.monthly_budget_cents)} planejados.</p><p>Reserva desejada: {formatMoney(totals.reserveTarget)}. Capacidade de aporte planejada: {formatMoney(totals.contributionCapacity)} (renda declarada menos orçamento, com mínimo zero).</p></section>}
    <section className={styles.panel}><h2>Receitas, despesas e patrimônio</h2>{entries.length ? <div className={styles.tableWrap}><table className={styles.table}><caption>Lançamentos financeiros pessoais registrados</caption><thead><tr><th>Registro</th><th>Tipo</th><th>Data</th><th>Valor</th></tr></thead><tbody>{entries.map((entry) => <tr key={entry.id}><td>{entry.title}</td><td>{kinds[entry.kind]}</td><td>{formatFinancialDate(entry.financial_date)}</td><td>{entry.valuation_status==='NOT_AVAILABLE'?'Avaliação indisponível':formatMoney(entry.amount_cents)}</td></tr>)}</tbody></table></div> : <p>Seu espaço está pronto para o primeiro registro. Nenhum lançamento foi criado automaticamente.</p>}
      {write.allowed && <WealthForm kind="entry" idempotencyKey={randomUUID()}><label>Nome do lançamento<input name="title" maxLength={160} required /></label><label>Tipo<select name="kind">{Object.entries(kinds).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Valor (R$)<input name="amount" inputMode="decimal" required /></label><label>Data financeira<input name="financial_date" type="date" defaultValue={today} required /></label><label>Categoria<select name="category">{Object.entries(categories).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Recorrência declarada<select name="recurrence"><option value="none">Sem recorrência</option><option value="monthly">Mensal (referência)</option><option value="yearly">Anual (referência)</option></select></label></WealthForm>}
    </section>
    <section className={styles.panel}><h2>Suas metas</h2><Link className={styles.textButton} href="/apps/wealth/metas">Consultar e gerenciar todas as metas →</Link><p>{totals.goalCount} meta(s) não arquivada(s), {totals.completedGoals} concluída(s). Cobertura: {progressPercent(totals.goalSaved,totals.goalTarget)}%. Reservado (limitado ao objetivo de cada meta): {formatMoney(totals.goalSaved)} de {formatMoney(totals.goalTarget)}. Aportes planejados das metas em andamento: {formatMoney(totals.goalContributions)}.</p>{goals.length ? <div className={styles.tableWrap}><table className={styles.table}><caption>Até 15 metas e valores declarados</caption><thead><tr><th>Meta</th><th>Reservado / objetivo</th><th>Aporte mensal</th><th>Data</th></tr></thead><tbody>{goals.map((goal) => <tr key={goal.id}><td><Link href={`/apps/wealth/metas/${goal.id}`}>{goal.title}</Link></td><td>{formatMoney(goal.saved_cents)} / {formatMoney(goal.target_cents)}</td><td>{formatMoney(goal.monthly_contribution_cents)}</td><td>{formatFinancialDate(goal.target_date)}</td></tr>)}</tbody></table></div> : <p>Crie uma meta para conectar o que você faz hoje ao que quer construir.</p>}
      {write.allowed && <WealthForm kind="goal" idempotencyKey={randomUUID()}><label>Nome da meta<input name="title" required maxLength={160} /></label><label>Objetivo (R$)<input name="target" inputMode="decimal" required /></label><label>Já reservado (R$)<input name="saved" inputMode="decimal" defaultValue="0" required /></label><label>Aporte mensal planejado (R$)<input name="monthly_contribution" inputMode="decimal" defaultValue="0" required /></label><label>Data desejada<input name="target_date" type="date" required /></label></WealthForm>}
    </section>
    <section className={styles.panel}><h2>Evolução mensal</h2><div className={styles.tableWrap}><table className={styles.table}><caption>Últimos 12 meses · todos os lançamentos ativos em BRL</caption><thead><tr><th scope="col">Mês</th><th scope="col">Receitas</th><th scope="col">Despesas</th><th scope="col">Fluxo</th></tr></thead><tbody>{totals.months.map(month=><tr key={month.month}><td>{month.month}</td><td>{formatMoney(month.income)}</td><td>{formatMoney(month.expenses)}</td><td>{formatMoney(month.cashFlow)}</td></tr>)}</tbody></table></div></section>
    <section className={styles.panel}><h2>Categorias do mês</h2>{totals.categories.length?<ul>{totals.categories.map(row=><li key={`${row.kind}-${row.category}`}>{kinds[row.kind]} · {categories[row.category as keyof typeof categories]??row.category}: {formatMoney(row.amount)}</li>)}</ul>:<p>Nenhum movimento ativo neste mês.</p>}</section>
    <GoalSimulator /><section className={styles.panel}><h2>Privacidade e controle</h2><p>O Wealth usa seu espaço pessoal. Nenhuma conexão com Business ou outro produto é ativada automaticamente.</p><Link href="/apps/privacidade">Ver consentimentos →</Link></section>
  </>
}
