import Link from 'next/link'
import { randomUUID } from 'node:crypto'
import { getPersonalProductAccess } from '@/lib/ecosystem/server'
import { formatMoney, formatFinancialDate, summarizeEntries, type WealthEntry, type WealthGoal } from '@/lib/wealth/core'
import WealthForm from '@/components/wealth/WealthForm'
import GoalSimulator from '@/components/wealth/GoalSimulator'
import styles from '@/components/ecosystem/ecosystem.module.css'

const kinds = { income: 'Receita', expense: 'Despesa', asset: 'Ativo', liability: 'Passivo' }
const categories = { salary: 'Renda', housing: 'Moradia', food: 'Alimentação', transport: 'Transporte', education: 'Educação', health: 'Saúde', leisure: 'Lazer', investment: 'Investimento', property: 'Bem', loan: 'Dívida', other: 'Outros' }

export default async function WealthPage() {
  const access = await getPersonalProductAccess('wealth', 'wealth.read')
  if (!access.allowed || !access.identity) return <><p className={styles.eyebrow}>Orçaly Wealth · Espaço pessoal</p><h1>Seu futuro começa<br />com clareza.</h1><div className={styles.notice}>O acesso ao Wealth ainda não está liberado para esta conta neste ambiente. Seus produtos atuais continuam disponíveis no App Hub.</div><Link className={styles.textButton} href="/apps">← Voltar ao App Hub</Link><GoalSimulator /></>
  const { db, user } = access.identity
  const [entryResult, goalResult, profileResult] = await Promise.all([
    db.from('wealth_entries').select('id,title,kind,category,amount_cents,financial_date,currency,recurrence', { count: 'exact' }).eq('user_id', user.id).order('financial_date', { ascending: false }).limit(500),
    db.from('wealth_goals').select('id,title,target_cents,saved_cents,monthly_contribution_cents,target_date').eq('user_id', user.id).order('target_date').limit(100),
    db.from('wealth_profiles').select('monthly_income_cents,monthly_budget_cents,dependents,emergency_months,timezone').eq('user_id', user.id).maybeSingle(),
  ])
  if (entryResult.error || goalResult.error || profileResult.error) return <><h1>Orçaly Wealth</h1><div className={styles.notice}>Não foi possível consultar seu espaço financeiro. Nenhum saldo foi estimado. Tente novamente em alguns instantes.</div><Link href="/apps">Voltar ao App Hub</Link></>
  const entries = (entryResult.data ?? []) as WealthEntry[]
  const goals = (goalResult.data ?? []) as WealthGoal[]
  const profile = profileResult.data
  const today = new Intl.DateTimeFormat('en-CA', { timeZone: profile?.timezone || 'America/Sao_Paulo', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date())
  const totals = summarizeEntries(entries, today.slice(0, 7))
  const moneyValue = (cents?: number) => ((cents || 0) / 100).toFixed(2)
  const write = await getPersonalProductAccess('wealth', 'wealth.write')
  return <><Link className={styles.textButton} href="/apps">← App Hub</Link><p className={styles.eyebrow}>Orçaly Wealth · Contexto pessoal</p><h1>Seu dinheiro.<br />Suas possibilidades.</h1><p className={styles.lead}>Informações que você registrou, separadas dos dados empresariais. Moeda: BRL. Período do fluxo de caixa: {today.slice(0, 7)}.</p>
    <Link className={styles.textButton} href="/apps/wealth/lancamentos">Consultar histórico e exportar lançamentos →</Link>
    {(entryResult.count || 0) > 500 && <p className={styles.notice}>Os totais abaixo consideram apenas os 500 lançamentos mais recentes exibidos nesta visão. O histórico permite consultar as demais páginas.</p>}
    <dl className={styles.metricGrid}><div className={styles.metric}><dt>Patrimônio líquido registrado</dt><dd>{formatMoney(totals.netWorth)}</dd></div><div className={styles.metric}><dt>Fluxo de caixa do mês</dt><dd>{formatMoney(totals.cashFlow)}</dd></div><div className={styles.metric}><dt>Ativos / passivos registrados</dt><dd>{formatMoney(totals.assets)}<small> / {formatMoney(totals.liabilities)}</small></dd></div></dl>
    <div className={styles.notice}>Dados de mercado não configurados. Os valores de ativos e passivos são declarados por você; não são cotações. Recorrências ficam registradas como referência e ainda não geram lançamentos automaticamente.</div>
    {write.allowed && <section className={styles.panel}><h2>Seu perfil e orçamento</h2><p>Defina sua renda, limite mensal e horizonte da reserva. Estes dados não definem um perfil regulado de investidor.</p><WealthForm kind="profile" idempotencyKey={randomUUID()}><label>Renda mensal declarada (R$)<input name="monthly_income" inputMode="decimal" defaultValue={moneyValue(profile?.monthly_income_cents)} required /></label><label>Orçamento mensal (R$)<input name="monthly_budget" inputMode="decimal" defaultValue={moneyValue(profile?.monthly_budget_cents)} required /></label><label>Dependentes<input name="dependents" type="number" min="0" max="50" defaultValue={profile?.dependents || 0} required /></label><label>Reserva em meses de orçamento<input name="emergency_months" type="number" min="1" max="36" defaultValue={profile?.emergency_months || 6} required /></label><label>Seu fuso horário<select name="timezone" defaultValue={profile?.timezone || 'America/Sao_Paulo'}><option value="America/Sao_Paulo">Brasília</option><option value="America/Manaus">Manaus</option><option value="America/Rio_Branco">Rio Branco</option><option value="America/Noronha">Fernando de Noronha</option><option value="Europe/Lisbon">Lisboa</option><option value="UTC">UTC</option></select></label></WealthForm></section>}
    {profile && <section className={styles.panel}><h2>Como está seu orçamento?</h2><p>Despesas registradas no mês: {formatMoney(totals.expenses)} de {formatMoney(profile.monthly_budget_cents)} planejados.</p><p>Reserva desejada: {formatMoney(profile.monthly_budget_cents * profile.emergency_months)}. Renda declarada menos orçamento: {formatMoney(profile.monthly_income_cents - profile.monthly_budget_cents)}.</p></section>}
    <section className={styles.panel}><h2>Receitas, despesas e patrimônio</h2>{entries.length ? <div className={styles.tableWrap}><table className={styles.table}><caption>Lançamentos financeiros pessoais registrados</caption><thead><tr><th>Registro</th><th>Tipo</th><th>Data</th><th>Valor</th></tr></thead><tbody>{entries.map((entry) => <tr key={entry.id}><td>{entry.title}</td><td>{kinds[entry.kind]}</td><td>{formatFinancialDate(entry.financial_date)}</td><td>{formatMoney(entry.amount_cents)}</td></tr>)}</tbody></table></div> : <p>Seu espaço está pronto para o primeiro registro. Nenhum lançamento foi criado automaticamente.</p>}
      {write.allowed && <WealthForm kind="entry" idempotencyKey={randomUUID()}><label>Nome do lançamento<input name="title" maxLength={160} required /></label><label>Tipo<select name="kind">{Object.entries(kinds).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Valor (R$)<input name="amount" inputMode="decimal" required /></label><label>Data financeira<input name="financial_date" type="date" defaultValue={today} required /></label><label>Categoria<select name="category">{Object.entries(categories).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Recorrência declarada<select name="recurrence"><option value="none">Sem recorrência</option><option value="monthly">Mensal (referência)</option><option value="yearly">Anual (referência)</option></select></label></WealthForm>}
    </section>
    <section className={styles.panel}><h2>Suas metas</h2>{goals.length ? <div className={styles.tableWrap}><table className={styles.table}><caption>Metas e valores declarados</caption><thead><tr><th>Meta</th><th>Reservado / objetivo</th><th>Aporte mensal</th><th>Data</th></tr></thead><tbody>{goals.map((goal) => <tr key={goal.id}><td>{goal.title}</td><td>{formatMoney(goal.saved_cents)} / {formatMoney(goal.target_cents)}</td><td>{formatMoney(goal.monthly_contribution_cents)}</td><td>{formatFinancialDate(goal.target_date)}</td></tr>)}</tbody></table></div> : <p>Crie uma meta para conectar o que você faz hoje ao que quer construir.</p>}
      {write.allowed && <WealthForm kind="goal" idempotencyKey={randomUUID()}><label>Nome da meta<input name="title" required maxLength={160} /></label><label>Objetivo (R$)<input name="target" inputMode="decimal" required /></label><label>Já reservado (R$)<input name="saved" inputMode="decimal" defaultValue="0" required /></label><label>Aporte mensal planejado (R$)<input name="monthly_contribution" inputMode="decimal" defaultValue="0" required /></label><label>Data desejada<input name="target_date" type="date" required /></label></WealthForm>}
    </section><GoalSimulator /><section className={styles.panel}><h2>Privacidade e controle</h2><p>O Wealth usa seu espaço pessoal. Nenhuma conexão com Business ou outro produto é ativada automaticamente.</p><Link href="/apps/privacidade">Ver consentimentos →</Link></section>
  </>
}
