-- Recovery R3 schema-only snapshot. Contains definitions, never production rows.
set lock_timeout = '5s';
set statement_timeout = '60s';

create table orcaly_private.affiliate_payout_accounts (
  id uuid default gen_random_uuid() not null,
  affiliate_id uuid not null,
  pix_key_type text not null,
  pix_key_encrypted text not null,
  pix_key_masked text not null,
  holder_name text not null,
  holder_document_hash text not null,
  holder_document_last4 text not null,
  bank_name text,
  provider_validation jsonb default '{}'::jsonb not null,
  is_verified boolean default false not null,
  verified_at timestamp with time zone,
  verified_by text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table orcaly_private.api_rate_limits (
  key text not null,
  window_started_at timestamp with time zone default clock_timestamp() not null,
  request_count integer default 0 not null,
  updated_at timestamp with time zone default clock_timestamp() not null
);

create table public.admin_audit_logs (
  id uuid default gen_random_uuid() not null,
  admin_email text not null,
  action text not null,
  metadata jsonb default '{}'::jsonb,
  created_at timestamp with time zone default now(),
  target_type text,
  target_id text,
  target_label text,
  payload jsonb default '{}'::jsonb not null
);

create table public.admin_bug_reports (
  id uuid default gen_random_uuid() not null,
  severity text not null,
  category text not null,
  title text not null,
  description text,
  table_name text,
  record_id text,
  fingerprint text not null,
  status text default 'aberto'::text not null,
  metadata jsonb default '{}'::jsonb not null,
  first_seen_at timestamp with time zone default now(),
  last_seen_at timestamp with time zone default now(),
  resolved_at timestamp with time zone,
  resolved_by text,
  resolution_note text,
  code text not null,
  area text default 'sistema'::text not null,
  entity_type text,
  entity_id text,
  entity_label text,
  suggested_action text,
  occurrences integer default 1 not null,
  fix_steps jsonb default '[]'::jsonb not null,
  fix_sql text,
  fix_route text,
  auto_fixable boolean default false not null,
  affected_table text,
  affected_field text
);

create table public.admin_scan_runs (
  id uuid default gen_random_uuid() not null,
  started_at timestamp with time zone default now(),
  finished_at timestamp with time zone,
  status text default 'rodando'::text not null,
  total_issues integer default 0 not null,
  critical_count integer default 0 not null,
  high_count integer default 0 not null,
  medium_count integer default 0 not null,
  low_count integer default 0 not null,
  created_by text,
  summary jsonb default '{}'::jsonb not null
);

create table public.admin_system_snapshots (
  id uuid default gen_random_uuid() not null,
  companies_total integer default 0,
  companies_active integer default 0,
  companies_overdue integer default 0,
  bugs_green integer default 0,
  bugs_yellow integer default 0,
  bugs_red integer default 0,
  metadata jsonb default '{}'::jsonb,
  created_at timestamp with time zone default now()
);

create table public.admin_users (
  id uuid default gen_random_uuid() not null,
  email text not null,
  nome text,
  role text default 'admin'::text not null,
  ativo boolean default true not null,
  created_at timestamp with time zone default now(),
  permissions jsonb default '{}'::jsonb not null,
  area text,
  observacoes text,
  created_by text,
  updated_at timestamp with time zone default now()
);

create table public.affiliate_achievements (
  id uuid default gen_random_uuid() not null,
  affiliate_id uuid not null,
  achievement_id text not null,
  title text not null,
  metadata jsonb default '{}'::jsonb not null,
  unlocked_at timestamp with time zone default now() not null
);

create table public.affiliate_activity_events (
  id uuid default gen_random_uuid() not null,
  affiliate_id uuid not null,
  lead_id uuid,
  kind text not null,
  xp integer default 0 not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null
);

create table public.affiliate_announcements (
  id uuid default gen_random_uuid() not null,
  title text not null,
  body text not null,
  kind text default 'news'::text not null,
  cta_label text,
  cta_href text,
  is_active boolean default true not null,
  published_at timestamp with time zone default now() not null,
  created_at timestamp with time zone default now() not null
);

create table public.affiliate_audit_logs (
  id uuid default gen_random_uuid() not null,
  affiliate_id uuid,
  actor_user_id uuid,
  actor_email text,
  action text not null,
  target_type text,
  target_id text,
  ip_hash text,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null
);

create table public.affiliate_certifications (
  id uuid default gen_random_uuid() not null,
  affiliate_id uuid not null,
  certification_id text not null,
  title text not null,
  score numeric(5,2) not null,
  status text default 'issued'::text not null,
  issued_at timestamp with time zone default now() not null,
  expires_at timestamp with time zone,
  metadata jsonb default '{}'::jsonb not null
);

create table public.affiliate_clicks (
  id uuid default gen_random_uuid() not null,
  affiliate_id uuid not null,
  code_snapshot text not null,
  session_hash text,
  ip_hash text,
  user_agent_hash text,
  landing_path text,
  referrer_host text,
  created_at timestamp with time zone default now() not null
);

create table public.affiliate_commissions (
  id uuid default gen_random_uuid() not null,
  affiliate_id uuid not null,
  referral_id uuid not null,
  company_id uuid not null,
  plan_payment_id uuid,
  provider_payment_id text not null,
  plan text not null,
  gross_amount numeric(14,2) not null,
  eligible_amount numeric(14,2) not null,
  commission_rate numeric(5,4) not null,
  commission_amount numeric(14,2) not null,
  status text default 'hold'::text not null,
  hold_until timestamp with time zone,
  available_at timestamp with time zone,
  payout_id uuid,
  reversed_at timestamp with time zone,
  reversal_reason text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.affiliate_course_progress (
  id uuid default gen_random_uuid() not null,
  affiliate_id uuid not null,
  course_id text not null,
  lesson_id text not null,
  score numeric(5,2),
  completed_at timestamp with time zone default now() not null,
  created_at timestamp with time zone default now() not null
);

create table public.affiliate_goals (
  id uuid default gen_random_uuid() not null,
  affiliate_id uuid not null,
  period_start date not null,
  contacts_target integer default 30 not null,
  demos_target integer default 10 not null,
  trials_target integer default 5 not null,
  customers_target integer default 3 not null,
  content_target integer default 4 not null,
  study_target integer default 4 not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.affiliate_leads (
  id uuid default gen_random_uuid() not null,
  affiliate_id uuid not null,
  name text not null,
  company_name text,
  whatsapp text,
  email text,
  segment text default 'services'::text not null,
  status text default 'new'::text not null,
  source text default 'manual'::text not null,
  notes text,
  next_follow_up_at timestamp with time zone,
  estimated_plan text,
  estimated_value numeric(12,2) default 0 not null,
  lost_reason text,
  converted_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.affiliate_payout_items (
  payout_id uuid not null,
  commission_id uuid not null,
  amount numeric(14,2) not null,
  created_at timestamp with time zone default now() not null
);

create table public.affiliate_payouts (
  id uuid default gen_random_uuid() not null,
  affiliate_id uuid not null,
  gross_commissions numeric(14,2) default 0 not null,
  debt_offset numeric(14,2) default 0 not null,
  amount numeric(14,2) not null,
  status text default 'requested'::text not null,
  provider text default 'manual'::text not null,
  provider_transfer_id text,
  external_reference text not null,
  pix_key_type text not null,
  pix_key_masked text not null,
  holder_name text not null,
  requested_at timestamp with time zone default now() not null,
  approved_at timestamp with time zone,
  processing_at timestamp with time zone,
  paid_at timestamp with time zone,
  failed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  failure_reason text,
  proof_url text,
  admin_note text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.affiliate_profiles (
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  name text not null,
  email text not null,
  whatsapp text not null,
  document_type text not null,
  document_hash text not null,
  document_last4 text not null,
  code text not null,
  status text default 'active'::text not null,
  payout_status text default 'pending_verification'::text not null,
  commission_rate numeric(5,4) default 0.6000 not null,
  debt_balance numeric(14,2) default 0 not null,
  terms_version text not null,
  terms_accepted_at timestamp with time zone not null,
  marketing_opt_in boolean default false not null,
  approved_at timestamp with time zone,
  suspended_at timestamp with time zone,
  suspension_reason text,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.affiliate_program_settings (
  id smallint default 1 not null,
  commission_rate numeric(5,4) default 0.6000 not null,
  hold_days integer default 14 not null,
  minimum_payout_amount numeric(14,2) default 50.00 not null,
  attribution_days integer default 60 not null,
  payouts_enabled boolean default true not null,
  automatic_payout_enabled boolean default false not null,
  terms_version text default '2026-07-29'::text not null,
  updated_at timestamp with time zone default now() not null
);

create table public.affiliate_referrals (
  id uuid default gen_random_uuid() not null,
  affiliate_id uuid not null,
  referral_code text not null,
  signup_lead_id uuid,
  company_id uuid,
  status text default 'registered'::text not null,
  plan text,
  customer_name_masked text,
  customer_email_masked text,
  customer_document_hash text,
  customer_whatsapp_hash text,
  source text default 'link'::text not null,
  registered_at timestamp with time zone default now() not null,
  trial_ends_at timestamp with time zone,
  qualified_at timestamp with time zone,
  rejected_at timestamp with time zone,
  rejection_reason text,
  first_payment_reference text,
  first_payment_amount numeric(14,2),
  commission_expected numeric(14,2) default 0 not null,
  ip_hash text,
  device_hash text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  review_status text default 'pending'::text not null,
  reviewed_at timestamp with time zone,
  reviewed_by text,
  review_note text
);

create table public.affiliate_tasks (
  id uuid default gen_random_uuid() not null,
  affiliate_id uuid not null,
  lead_id uuid,
  title text not null,
  task_type text default 'follow_up'::text not null,
  priority text default 'normal'::text not null,
  due_at timestamp with time zone,
  notes text,
  completed_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.affiliate_training_sessions (
  id uuid default gen_random_uuid() not null,
  affiliate_id uuid not null,
  mode text not null,
  scenario_id text not null,
  answer text,
  total_score numeric(5,2) default 0 not null,
  score_json jsonb default '{}'::jsonb not null,
  feedback text,
  completed_at timestamp with time zone default now() not null,
  created_at timestamp with time zone default now() not null
);

create table public.app_notifications (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  user_id uuid,
  tipo text default 'info'::text not null,
  titulo text not null,
  mensagem text,
  link_url text,
  status text default 'unread'::text not null,
  payload jsonb default '{}'::jsonb not null,
  read_at timestamp with time zone,
  created_at timestamp with time zone default now() not null
);

create table public.art_approval_requests (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  order_id uuid,
  proposal_id uuid,
  token text default encode(gen_random_bytes(18), 'hex'::text) not null,
  title text,
  produto_nome text,
  cliente_nome text,
  cliente_whatsapp text,
  artwork_url text,
  preview_url text,
  instructions text,
  status text default 'Aguardando aprovação da arte'::text not null,
  comentario_cliente text,
  internal_notes text,
  approved_at timestamp with time zone,
  requested_changes_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  expires_at timestamp with time zone default (clock_timestamp() + '7 days'::interval),
  responded_at timestamp with time zone,
  revoked_at timestamp with time zone
);

create table public.business_hours (
  id uuid default gen_random_uuid() not null,
  company_id uuid,
  weekday integer not null,
  opens_at time without time zone,
  closes_at time without time zone,
  active boolean default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  is_active boolean default true not null,
  is_open boolean default true,
  open_time time without time zone,
  close_time time without time zone,
  break_start time without time zone,
  break_end time without time zone,
  closed_message text
);

create table public.companies (
  id uuid default gen_random_uuid() not null,
  nome text not null,
  slug text not null,
  logo_url text,
  whatsapp text,
  cor_principal text default '#fb923c'::text,
  plano text default 'basico'::text,
  ativo boolean default true,
  created_at timestamp with time zone default now(),
  owner_id uuid,
  email text,
  segmento text,
  telefone text,
  cidade text,
  estado text,
  pix_key text,
  pix_nome text,
  pix_cidade text,
  aceita_pix boolean default true,
  aceita_cartao boolean default false,
  cobrar_sinal boolean default false,
  percentual_sinal numeric default 0,
  assinatura_status text default 'pendente'::text,
  assinatura_plano text,
  assinatura_inicio timestamp with time zone,
  assinatura_expira_em timestamp with time zone,
  assinatura_ultimo_pagamento timestamp with time zone,
  mercado_pago_customer_email text,
  tester_id uuid,
  modelo_negocio text,
  modelo_nome text,
  modelo_perguntas jsonb default '[]'::jsonb,
  subdomain_slug text,
  site_template text default 'auto'::text,
  site_status text default 'publicado'::text,
  site_primary_color text default '#05245c'::text,
  site_accent_color text default '#22c55e'::text,
  site_config jsonb default '{}'::jsonb,
  site_updated_at timestamp with time zone default now(),
  pix_tipo text default 'telefone'::text,
  atendimento_horario text,
  atendimento_observacao text,
  instagram text,
  marketplace_ativo boolean default true,
  marketplace_titulo text,
  marketplace_subtitulo text,
  marketplace_banner_url text,
  marketplace_texto_botao text default 'Comprar agora'::text,
  marketplace_sobre text,
  marketplace_endereco text,
  marketplace_mapa_url text,
  marketplace_termos text,
  marketplace_config jsonb default '{}'::jsonb,
  site_publico_ativo boolean default true,
  site_background_color text default '#f5f8ff'::text,
  site_headline text,
  site_subheadline text,
  site_cta_text text default 'Ver loja'::text,
  site_banner_url text,
  site_about_title text,
  site_about_text text,
  site_services_title text,
  site_contact_title text,
  site_show_store boolean default true,
  site_show_about boolean default true,
  site_show_contact boolean default true,
  site_show_featured boolean default true,
  site_features jsonb default '[]'::jsonb,
  site_faq jsonb default '[]'::jsonb,
  site_testimonials jsonb default '[]'::jsonb,
  site_custom_sections jsonb default '[]'::jsonb,
  updated_at timestamp with time zone default now(),
  assinatura_auto_recorrente boolean default false,
  assinatura_cancelada_em timestamp with time zone,
  assinatura_checkout_url text,
  assinatura_mp_payload jsonb,
  assinatura_proxima_cobranca timestamp with time zone,
  mercado_pago_subscription_id text,
  mercado_pago_subscription_status text,
  modelo_status text[],
  modelo_mensagens jsonb default '[]'::jsonb,
  modelo_proposta jsonb default '{}'::jsonb,
  modelo_campos_recomendados text[],
  site_layout text default 'moderno'::text,
  site_art_style text default 'profissional'::text,
  site_font_style text default 'inter'::text,
  site_button_style text default 'arredondado'::text,
  site_hero_alignment text default 'esquerda'::text,
  site_text_color text default '#071b3a'::text,
  site_card_color text default '#ffffff'::text,
  site_badge_text text,
  site_secondary_cta_text text default 'Ver catálogo'::text,
  site_whatsapp_message text,
  site_show_faq boolean default true,
  site_show_testimonials boolean default true,
  site_show_gallery boolean default true,
  site_show_benefits boolean default true,
  site_gallery jsonb default '[]'::jsonb,
  site_benefits jsonb default '[]'::jsonb,
  site_seo_title text,
  site_seo_description text,
  site_keywords text[],
  site_promo_title text,
  site_promo_text text,
  site_promo_active boolean default false,
  site_promo_button_text text default 'Aproveitar oferta'::text,
  site_business_hours jsonb default '{}'::jsonb,
  site_payment_methods text[],
  site_delivery_options text[],
  site_hero_style text default 'premium-showcase'::text,
  site_art_variant text default 'auto'::text,
  site_section_style text default 'soft-premium'::text,
  site_product_card_style text default 'premium'::text,
  site_nav_variant text default 'clean'::text,
  site_corner_style text default 'rounded'::text,
  site_density text default 'comfortable'::text,
  site_show_marketplace boolean default true,
  site_enable_cart boolean default true,
  site_enable_coupons boolean default true,
  site_show_prices boolean default true,
  site_checkout_mode text default 'cart'::text,
  site_marketplace_title text default 'Catálogo online'::text,
  site_marketplace_subtitle text default 'Escolha produtos, monte seu pedido e envie tudo organizado para atendimento.'::text,
  site_cart_button_text text default 'Adicionar'::text,
  site_checkout_button_text text default 'Finalizar pedido'::text,
  site_empty_catalog_text text default 'A empresa ainda está preparando o catálogo.'::text,
  site_trust_title text default 'Por que escolher a gente?'::text,
  site_hero_highlights jsonb default '[]'::jsonb,
  site_brand_words text[],
  site_footer_text text,
  whatsapp_enabled boolean default false,
  whatsapp_phone_number_id text,
  whatsapp_access_token text,
  whatsapp_verify_token text,
  whatsapp_business_account_id text,
  whatsapp_auto_reply_enabled boolean default false,
  whatsapp_order_notifications boolean default false,
  whatsapp_status_notifications boolean default false,
  whatsapp_ai_enabled boolean default false,
  whatsapp_ai_prompt text,
  banner_url text,
  onboarding_current_step integer default 1,
  onboarding_completed boolean default false,
  onboarding_completed_at timestamp with time zone,
  onboarding_dismissed boolean default false,
  onboarding_updated_at timestamp with time zone default now(),
  business_type text default 'services'::text,
  onboarding_goal text,
  site_theme text,
  site_cta_label text,
  site_sections jsonb default '[]'::jsonb,
  assinatura_forma_pagamento_preferida text,
  assinatura_pix_avulso_status text,
  assinatura_pix_avulso_ultimo_pagamento timestamp with time zone,
  trial_started_at timestamp with time zone,
  trial_ends_at timestamp with time zone,
  trial_used_at timestamp with time zone,
  cancel_at_period_end boolean default false not null,
  access_until timestamp with time zone,
  subscription_provider text,
  provider_customer_id text,
  provider_subscription_id text,
  next_billing_at timestamp with time zone,
  is_founder boolean default false not null,
  founder_number integer,
  founder_price_cents integer,
  founder_started_at timestamp with time zone,
  founder_trial_ends_at timestamp with time zone,
  founder_price_ends_at timestamp with time zone,
  founder_welcome_seen_at timestamp with time zone,
  founder_price_converted_at timestamp with time zone,
  founder_billing_claim_id uuid,
  founder_billing_claimed_at timestamp with time zone,
  founder_billing_attempts integer default 0 not null,
  founder_billing_last_error text,
  founder_billing_setup_at timestamp with time zone,
  founder_billing_authorized_at timestamp with time zone,
  founder_billing_last_sync_at timestamp with time zone,
  founder_price_conversion_claim_id uuid,
  founder_price_conversion_claimed_at timestamp with time zone,
  founder_price_conversion_attempts integer default 0 not null,
  founder_price_conversion_last_error text
);

create table public.company_members (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  user_id uuid not null,
  nome text not null,
  email text not null,
  cargo text default 'atendente'::text not null,
  status text default 'ativo'::text not null,
  permissions jsonb default '{}'::jsonb not null,
  created_by uuid,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table public.company_niche_templates (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  niche_id text not null,
  niche_name text not null,
  categories text[] default '{}'::text[] not null,
  questions text[] default '{}'::text[] not null,
  statuses text[] default '{}'::text[] not null,
  ready_messages jsonb default '[]'::jsonb not null,
  proposal_model jsonb default '{}'::jsonb not null,
  recommended_fields text[] default '{}'::text[] not null,
  applied_by uuid,
  applied_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.company_proposal_settings (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  default_validity_days integer default 7,
  default_terms text,
  default_intro text,
  default_approval_message text,
  default_rejection_message text,
  require_document boolean default false,
  require_signature_name boolean default true,
  auto_generate_pix boolean default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table public.company_whatsapp_settings (
  company_id uuid not null,
  enabled boolean default false not null,
  ai_enabled boolean default false not null,
  notify_owner_new_order boolean default true not null,
  notify_client_new_order boolean default true not null,
  notify_client_order_status boolean default true not null,
  notify_client_proposal boolean default true not null,
  notify_owner_proposal boolean default true not null,
  owner_phone text,
  phone_number_id text,
  business_account_id text,
  ai_prompt text,
  fallback_message text default 'No momento não consegui responder automaticamente. Nossa equipe vai continuar seu atendimento.'::text,
  template_order_created text,
  template_order_status text,
  template_proposal_update text,
  template_payment_update text,
  template_language text default 'pt_BR'::text not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.crm_leads (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  nome text not null,
  telefone text,
  email text,
  origem text default 'manual'::text,
  etapa text default 'novo_lead'::text not null,
  status text default 'ativo'::text not null,
  valor_estimado numeric default 0,
  proximo_contato_em timestamp with time zone,
  observacoes text,
  tags text[],
  order_id uuid,
  proposal_id uuid,
  created_by uuid,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.customer_followups (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  cliente_nome text,
  cliente_telefone text not null,
  titulo text not null,
  descricao text,
  status text default 'pendente'::text not null,
  prioridade text default 'media'::text not null,
  due_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone default now()
);

create table public.customer_internal_notes (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  customer_phone text,
  customer_name text,
  note text not null,
  created_by uuid,
  created_at timestamp with time zone default now() not null
);

create table public.customer_magic_links (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  customer_name text,
  customer_phone text not null,
  token text default encode(gen_random_bytes(18), 'hex'::text) not null,
  status text default 'ativo'::text not null,
  last_access_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone default now() not null
);

create table public.customer_notes (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  cliente_nome text,
  cliente_telefone text not null,
  tipo text default 'nota'::text not null,
  conteudo text not null,
  created_by uuid,
  created_at timestamp with time zone default now()
);

create table public.customer_portal_events (
  id uuid default gen_random_uuid() not null,
  company_id uuid,
  customer_magic_link_id uuid,
  event_type text not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null
);

create table public.deliveries (
  id uuid default gen_random_uuid() not null,
  company_id uuid,
  order_id uuid,
  customer_name text,
  customer_phone text,
  address text,
  neighborhood text,
  delivery_zone_id uuid,
  delivery_fee numeric(12,2) default 0,
  payment_method_id uuid,
  status text default 'waiting_preparation'::text,
  notes text,
  estimated_delivery_at timestamp with time zone,
  delivered_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  assigned_driver_id uuid,
  assigned_at timestamp with time zone,
  dispatched_at timestamp with time zone
);

create table public.delivery_assignments (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  delivery_id uuid,
  order_id uuid,
  driver_id uuid,
  driver_name text not null,
  driver_whatsapp text,
  vehicle_plate text,
  delivery_code text,
  customer_name text,
  customer_phone text,
  address text,
  neighborhood text,
  map_url text,
  payment_method text,
  payment_status text,
  order_total numeric(14,2) default 0 not null,
  delivery_fee numeric(14,2) default 0 not null,
  status text default 'assigned'::text not null,
  assigned_at timestamp with time zone default now() not null,
  out_for_delivery_at timestamp with time zone,
  delivered_at timestamp with time zone,
  settlement_status text default 'pending'::text not null,
  settled_at timestamp with time zone,
  settlement_note text,
  created_by uuid,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.delivery_drivers (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  name text not null,
  whatsapp text not null,
  vehicle_plate text,
  notes text,
  is_active boolean default true not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.delivery_zones (
  id uuid default gen_random_uuid() not null,
  company_id uuid,
  name text not null,
  fee numeric(10,2) default 0,
  min_order numeric(10,2),
  active boolean default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  is_active boolean default true not null,
  minimum_order numeric(12,2) default 0,
  estimated_time_min integer,
  estimated_time_max integer,
  notes text
);

create table public.finance_accounts (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  nome text not null,
  tipo text default 'caixa'::text not null,
  saldo_inicial numeric default 0 not null,
  ativo boolean default true not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now() not null
);

create table public.financial_categories (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  name text not null,
  type text,
  created_at timestamp with time zone default now() not null
);

create table public.financial_material_entries (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  transaction_id uuid,
  nome text not null,
  quantidade numeric default 1 not null,
  unidade text default 'un'::text,
  valor_unitario numeric default 0,
  valor_total numeric default 0,
  codigo text,
  categoria text,
  fornecedor text,
  created_at timestamp with time zone default now()
);

create table public.financial_transactions (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  tipo text default 'saida'::text not null,
  categoria text default 'outros'::text not null,
  descricao text not null,
  valor numeric default 0 not null,
  data_competencia date default CURRENT_DATE not null,
  status text default 'pago'::text not null,
  forma_pagamento text,
  fornecedor_cliente text,
  documento_url text,
  documento_nome text,
  documento_tipo text,
  codigo_barras text,
  nota_chave text,
  nota_numero text,
  nota_serie text,
  nota_emitente text,
  nota_cnpj_emitente text,
  nota_data_emissao text,
  origem text default 'manual'::text not null,
  raw_data jsonb default '{}'::jsonb not null,
  created_by uuid,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  vencimento date,
  observacoes text,
  centro_custo text,
  tags text[] default '{}'::text[],
  recorrente boolean default false,
  recorrencia_grupo uuid,
  parcela_atual integer,
  parcelas_total integer,
  account_id uuid,
  type text,
  description text,
  amount numeric(12,2),
  category_id uuid,
  customer_id uuid,
  order_id uuid,
  proposal_id uuid,
  invoice_id uuid,
  payment_method text,
  due_date date,
  paid_at timestamp with time zone,
  notes text
);

create table public.founder_invites (
  id uuid default gen_random_uuid() not null,
  email text not null,
  email_normalized text generated always as (lower(btrim(email))) stored,
  founder_number integer not null,
  plan_key text not null,
  founder_price_cents integer not null,
  status text default 'pending'::text not null,
  token_hash text not null,
  token_expires_at timestamp with time zone,
  invited_at timestamp with time zone default now() not null,
  activated_at timestamp with time zone,
  revoked_at timestamp with time zone,
  user_id uuid,
  company_id uuid,
  created_by_admin_id uuid,
  created_by_email text not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  sales_lead_id uuid,
  token_rotated_at timestamp with time zone,
  revoked_by_admin_id uuid,
  revocation_reason text,
  activation_claim_id uuid,
  activation_claimed_at timestamp with time zone,
  activation_attempts integer default 0 not null,
  activation_last_error text
);

create table public.internal_tasks (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  titulo text not null,
  descricao text,
  status text default 'pendente'::text not null,
  prioridade text default 'media'::text not null,
  due_at timestamp with time zone,
  responsavel_id uuid,
  created_by uuid,
  crm_lead_id uuid,
  order_id uuid,
  proposal_id uuid,
  completed_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.marketplace_commission_rules (
  id uuid default gen_random_uuid() not null,
  company_id uuid,
  plan_key text,
  commission_percentage numeric(5,2) default 5.00 not null,
  commission_fixed numeric(12,2) default 0 not null,
  is_active boolean default true not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table public.marketplace_commissions (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  order_id uuid,
  marketplace_payment_id uuid,
  provider text default 'mercado_pago'::text not null,
  gross_amount numeric(12,2) default 0 not null,
  commission_percentage numeric(5,2) default 0 not null,
  commission_fixed numeric(12,2) default 0 not null,
  commission_amount numeric(12,2) default 0 not null,
  status text default 'pending'::text not null,
  confirmed_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  provider_split_id text,
  calculation_base text,
  fee_percent numeric(8,4),
  estimated_amount numeric(14,2),
  confirmed_amount numeric(14,2),
  refusal_reason text,
  external_reference text
);

create table public.marketplace_coupons (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  codigo text not null,
  codigo_normalizado text not null,
  descricao text,
  tipo text default 'percentual'::text not null,
  valor numeric default 0 not null,
  valor_minimo_pedido numeric default 0 not null,
  valor_maximo_desconto numeric,
  starts_at timestamp with time zone,
  ends_at timestamp with time zone,
  usage_limit integer,
  used_count integer default 0 not null,
  ativo boolean default true not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  coupon_type text,
  free_delivery boolean default false not null,
  allowed_product_ids jsonb default '[]'::jsonb not null,
  allowed_categories jsonb default '[]'::jsonb not null
);

create table public.marketplace_oauth_states (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  user_id uuid,
  provider text default 'mercado_pago'::text not null,
  state_hash text not null,
  expires_at timestamp with time zone not null,
  consumed_at timestamp with time zone,
  created_at timestamp with time zone default now()
);

create table public.marketplace_payment_settings (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  provider text default 'mercado_pago'::text not null,
  provider_user_id text,
  provider_account_id text,
  access_token text,
  refresh_token text,
  public_key text,
  token_expires_at timestamp with time zone,
  onboarding_status text default 'pending'::text not null,
  is_active boolean default false not null,
  last_error text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  provider_wallet_id text,
  encrypted_provider_api_key text,
  encrypted_webhook_auth_token text,
  account_status text,
  charges_enabled boolean default false,
  payouts_enabled boolean default false,
  pix_enabled boolean default false,
  card_enabled boolean default false,
  onboarding_url text,
  last_status_check_at timestamp with time zone,
  provider_metadata_sanitized jsonb default '{}'::jsonb,
  legal_name text,
  document_last4 text,
  bank_name text,
  bank_account_last4 text,
  bank_account_type text,
  payout_pix_key_encrypted text,
  payout_pix_key_type text,
  payout_pix_key_masked text,
  payout_pix_owner_name text,
  payout_pix_owner_document_masked text,
  automatic_payout_enabled boolean default false not null,
  minimum_payout_amount numeric(12,2) default 0 not null,
  last_payout_at timestamp with time zone
);

create table public.marketplace_payments (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  order_id uuid,
  provider text default 'mercado_pago'::text not null,
  provider_preference_id text,
  provider_payment_id text,
  provider_status text,
  status text default 'pending'::text not null,
  checkout_url text,
  sandbox_checkout_url text,
  amount numeric(12,2) default 0 not null,
  subtotal numeric(12,2) default 0 not null,
  delivery_fee numeric(12,2) default 0 not null,
  discount_amount numeric(12,2) default 0 not null,
  commission_amount numeric(12,2) default 0 not null,
  commission_percentage numeric(5,2) default 0 not null,
  currency text default 'BRL'::text not null,
  payer_name text,
  payer_email text,
  payer_phone text,
  last_error text,
  raw_payload jsonb default '{}'::jsonb,
  paid_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  provider_customer_id text,
  payment_method text,
  gross_amount numeric(14,2),
  provider_fee_amount numeric(14,2),
  provider_net_amount numeric(14,2),
  platform_fee_percent numeric(8,4),
  platform_fee_amount numeric(14,2),
  seller_net_amount numeric(14,2),
  split_status text,
  payout_status text,
  idempotency_key text,
  external_reference text,
  expires_at timestamp with time zone,
  card_brand text,
  card_last4 text,
  error_message text,
  stock_reservation_status text,
  stock_reserved_at timestamp with time zone,
  stock_confirmed_at timestamp with time zone,
  stock_released_at timestamp with time zone
);

create table public.marketplace_stock_reservations (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  order_id uuid not null,
  marketplace_payment_id uuid not null,
  product_id uuid not null,
  quantity integer not null,
  status text default 'reserved'::text not null,
  stock_before integer not null,
  stock_after integer not null,
  expires_at timestamp with time zone not null,
  confirmed_at timestamp with time zone,
  released_at timestamp with time zone,
  release_reason text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.notifications (
  id uuid default gen_random_uuid() not null,
  company_id uuid,
  user_id uuid,
  type text not null,
  title text not null,
  message text,
  link text,
  priority text default 'normal'::text,
  read_at timestamp with time zone,
  metadata jsonb default '{}'::jsonb,
  created_at timestamp with time zone default now()
);

create table public.order_internal_comments (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  order_id uuid not null,
  user_id uuid,
  comentario text not null,
  created_at timestamp with time zone default now() not null
);

create table public.order_items (
  id uuid default gen_random_uuid() not null,
  order_id uuid,
  company_id uuid,
  product_id uuid,
  nome text not null,
  tipo text,
  unidade text,
  quantidade numeric default 1,
  preco_unitario numeric default 0,
  subtotal numeric default 0,
  created_at timestamp with time zone default now(),
  largura numeric,
  altura numeric,
  comprimento numeric,
  area_m2 numeric,
  precificacao text,
  detalhes_calculo text,
  respostas jsonb default '{}'::jsonb,
  product_name text,
  quantity integer default 1,
  unit_price numeric(12,2) default 0,
  addons jsonb default '[]'::jsonb,
  variation jsonb default '{}'::jsonb,
  notes text,
  total numeric(14,2) default 0,
  variation_json jsonb,
  addons_json jsonb,
  observation text
);

create table public.order_payments (
  id uuid default gen_random_uuid() not null,
  company_id uuid,
  order_id uuid,
  payment_method_id uuid,
  type text default 'full'::text,
  status text default 'pending'::text,
  amount numeric(12,2) default 0 not null,
  paid_amount numeric(12,2) default 0,
  remaining_amount numeric(12,2) default 0,
  provider text,
  provider_payment_id text,
  proof_url text,
  notes text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  provider_status text,
  idempotency_key text,
  external_reference text,
  paid_at timestamp with time zone
);

create table public.order_status_history (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  order_id uuid not null,
  old_status text,
  new_status text not null,
  changed_by uuid,
  note text,
  created_at timestamp with time zone default now() not null,
  changed_by_email text
);

create table public.orders (
  id uuid default gen_random_uuid() not null,
  nome text not null,
  telefone text not null,
  produto text not null,
  largura numeric,
  altura numeric,
  quantidade integer default 1,
  observacoes text,
  status text default 'Recebido'::text,
  preco_estimado numeric,
  created_at timestamp with time zone default now(),
  arquivo_url text,
  company_id uuid,
  valor_total numeric,
  valor_sinal numeric,
  percentual_sinal numeric,
  forma_pagamento text,
  parcelas integer,
  itens_resumo text,
  cliente_empresa text,
  dados_inteligentes jsonb default '{}'::jsonb,
  marketplace_origem text default 'orcamento'::text,
  prazo text,
  priority text default 'normal'::text,
  internal_notes text,
  files jsonb default '[]'::jsonb,
  source text,
  original_order_id uuid,
  customer_portal_token text,
  cupom_id uuid,
  cupom_codigo text,
  valor_desconto numeric default 0,
  valor_total_original numeric,
  prioridade text default 'normal'::text,
  prazo_entrega timestamp with time zone,
  responsavel_id uuid,
  canal_origem text default 'site'::text,
  endereco_entrega text,
  observacoes_internas text,
  aprovado_em timestamp with time zone,
  entregue_em timestamp with time zone,
  cancelado_em timestamp with time zone,
  updated_at timestamp with time zone default now(),
  responsavel_nome text,
  whatsapp_owner_notified_at timestamp with time zone,
  whatsapp_client_created_notified_at timestamp with time zone,
  whatsapp_last_status_notified text,
  whatsapp_last_status_notified_at timestamp with time zone,
  visualizado_em timestamp with time zone,
  notificado_em timestamp with time zone,
  delivery_type text,
  delivery_fee numeric(12,2) default 0,
  subtotal numeric(12,2) default 0,
  total_amount numeric(12,2) default 0,
  payment_method_id uuid,
  payment_status text default 'pending'::text,
  delivery_zone_id uuid,
  address text,
  neighborhood text,
  complement text,
  reference_point text,
  change_for numeric(12,2),
  items_snapshot jsonb default '[]'::jsonb,
  discount_amount numeric(12,2) default 0,
  coupon_code text,
  payment_provider text,
  marketplace_payment_id uuid,
  paid_at timestamp with time zone,
  customer_name text,
  customer_email text,
  customer_phone text,
  total numeric(14,2) default 0,
  payment_method text,
  coupon_id uuid,
  checkout_idempotency_key text,
  coupon_consumed_at timestamp with time zone
);

create table public.payment_methods (
  id uuid default gen_random_uuid() not null,
  company_id uuid,
  name text not null,
  type text not null,
  is_active boolean default true,
  requires_change boolean default false,
  allow_delivery_payment boolean default true,
  allow_online_payment boolean default false,
  instructions text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table public.payment_payouts (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  marketplace_payment_id uuid,
  provider text not null,
  provider_payout_id text,
  amount numeric(14,2) default 0 not null,
  status text default 'pending'::text not null,
  expected_at timestamp with time zone,
  paid_at timestamp with time zone,
  failure_reason text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  external_reference text,
  pix_key_type text,
  pix_key_masked text,
  attempts integer default 0 not null
);

create table public.payment_webhook_events (
  id uuid default gen_random_uuid() not null,
  provider text not null,
  provider_event_id text not null,
  event_type text not null,
  provider_object_id text,
  company_id uuid,
  payload_hash text not null,
  payload_sanitized jsonb default '{}'::jsonb not null,
  processing_status text default 'received'::text not null,
  attempts integer default 1 not null,
  received_at timestamp with time zone default now() not null,
  processed_at timestamp with time zone,
  error_message text
);

create table public.plan_payments (
  id uuid default gen_random_uuid() not null,
  company_id uuid,
  plano text not null,
  valor numeric not null,
  status text default 'pendente'::text,
  email text,
  nome_empresa text,
  mercado_pago_preference_id text,
  mercado_pago_payment_id text,
  checkout_url text,
  raw_webhook jsonb,
  raw_payment jsonb,
  created_at timestamp with time zone default now(),
  paid_at timestamp with time zone,
  tipo text default 'checkout'::text,
  mercado_pago_preapproval_id text,
  mercado_pago_authorized_payment_id text,
  raw_subscription jsonb,
  raw_authorized_payment jsonb,
  next_payment_date timestamp with time zone,
  cancelled_at timestamp with time zone,
  updated_at timestamp with time zone default now(),
  payment_method text,
  provider text,
  provider_customer_id text,
  provider_payment_id text,
  provider_subscription_id text,
  billing_type text,
  external_reference text,
  idempotency_key text
);

create table public.platform_admin_invites (
  id uuid default gen_random_uuid() not null,
  email text not null,
  email_normalized text generated always as (lower(btrim(email))) stored,
  nome text not null,
  role text default 'prospector'::text not null,
  area text default 'Comercial'::text not null,
  permissions jsonb default '{}'::jsonb not null,
  observacoes text,
  token_hash text not null,
  status text default 'pending'::text not null,
  expires_at timestamp with time zone not null,
  invited_at timestamp with time zone default now() not null,
  claimed_at timestamp with time zone,
  activation_claim_id uuid,
  activated_at timestamp with time zone,
  revoked_at timestamp with time zone,
  user_id uuid,
  platform_admin_id uuid,
  created_by_admin_id uuid,
  created_by_email text not null,
  last_token_rotated_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.platform_admins (
  id uuid default gen_random_uuid() not null,
  user_id uuid,
  email text not null,
  role text default 'admin'::text not null,
  is_active boolean default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  nome text,
  permissions jsonb default '{}'::jsonb not null,
  area text default 'Plataforma'::text not null,
  observacoes text,
  created_by text,
  last_login_at timestamp with time zone,
  must_change_password boolean default false not null
);

create table public.product_stock_movements (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  product_id uuid not null,
  order_id uuid,
  marketplace_payment_id uuid,
  reservation_id uuid,
  movement_type text not null,
  quantity_delta integer not null,
  stock_before integer not null,
  stock_after integer not null,
  reason text,
  metadata jsonb default '{}'::jsonb not null,
  idempotency_key text not null,
  created_at timestamp with time zone default now() not null
);

create table public.production_orders (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  proposal_id uuid,
  order_id uuid,
  title text not null,
  customer_name text,
  customer_whatsapp text,
  total_value numeric default 0,
  signal_value numeric default 0,
  status text default 'aguardando_sinal'::text,
  priority text default 'normal'::text,
  due_date timestamp with time zone,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  metadata jsonb default '{}'::jsonb,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  responsible_user_id uuid,
  responsible_name text,
  files jsonb default '[]'::jsonb,
  internal_notes text,
  created_by uuid
);

create table public.production_steps (
  id uuid default gen_random_uuid() not null,
  production_order_id uuid not null,
  company_id uuid not null,
  title text not null,
  description text,
  status text default 'pendente'::text,
  sort_order integer default 0,
  assigned_to uuid,
  due_date timestamp with time zone,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  completed_by uuid,
  metadata jsonb default '{}'::jsonb,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table public.products (
  id uuid default gen_random_uuid() not null,
  nome text not null,
  preco numeric not null,
  ativo boolean default true,
  created_at timestamp with time zone default now(),
  imagem_url text,
  company_id uuid,
  descricao text,
  categoria text,
  tipo text default 'produto'::text,
  unidade text default 'unidade'::text,
  destaque boolean default false,
  precificacao text default 'unidade'::text,
  unidade_label text default 'unidade'::text,
  permite_largura boolean default false,
  permite_altura boolean default false,
  permite_comprimento boolean default false,
  permite_quantidade boolean default true,
  valor_minimo numeric default 0,
  cobrar_sinal_personalizado boolean default false,
  percentual_sinal_produto numeric,
  configuracoes jsonb default '{}'::jsonb,
  image_urls text[] default '{}'::text[],
  variacoes text,
  prazo_medio text,
  arquivado boolean default false,
  deleted_at timestamp with time zone,
  updated_at timestamp with time zone default now(),
  custo_material numeric default 0,
  custo_mao_obra numeric default 0,
  custo_taxas numeric default 0,
  custo_entrega numeric default 0,
  margem_desejada numeric default 30,
  preco_minimo numeric,
  preco_sugerido numeric,
  margem_estimada numeric,
  archived boolean default false,
  video_url text,
  subcategoria text,
  preco_sob_consulta boolean default false,
  estoque integer,
  promocao_ativa boolean default false,
  preco_promocional numeric,
  campos_orcamento jsonb default '[]'::jsonb,
  descricao_curta text,
  descricao_detalhada text,
  unidade_preco text default 'unidade'::text,
  sku text,
  oculto boolean default false,
  adicionais jsonb default '[]'::jsonb,
  foto_url text,
  business_type text,
  extras jsonb default '{}'::jsonb,
  variations jsonb default '[]'::jsonb,
  addons jsonb default '[]'::jsonb,
  available boolean default true,
  is_active boolean default true not null
);

create table public.proposal_events (
  id uuid default gen_random_uuid() not null,
  proposal_id uuid,
  company_id uuid,
  event_type text not null,
  actor_type text default 'system'::text,
  actor_name text,
  actor_email text,
  note text,
  metadata jsonb default '{}'::jsonb,
  ip text,
  user_agent text,
  created_at timestamp with time zone default now()
);

create table public.proposals (
  id uuid default gen_random_uuid() not null,
  company_id uuid,
  order_id uuid,
  token text default replace((gen_random_uuid())::text, '-'::text, ''::text) not null,
  titulo text,
  cliente_nome text,
  cliente_whatsapp text,
  itens jsonb default '[]'::jsonb not null,
  valor_total numeric default 0,
  valor_sinal numeric default 0,
  prazo text,
  condicoes text,
  status text default 'enviado'::text,
  payment_url text,
  raw_data jsonb default '{}'::jsonb,
  created_at timestamp with time zone default now(),
  approved_at timestamp with time zone,
  cliente_email text,
  valor_desconto numeric default 0,
  percentual_sinal numeric default 0,
  introducao text,
  validade_dias integer default 7,
  valid_until timestamp with time zone,
  pix_payload text,
  pix_txid text,
  pix_valor numeric,
  sent_at timestamp with time zone,
  viewed_at timestamp with time zone,
  rejected_at timestamp with time zone,
  change_requested_at timestamp with time zone,
  expired_at timestamp with time zone,
  approval_name text,
  approval_document text,
  approval_note text,
  rejection_reason text,
  client_ip text,
  user_agent text,
  accepted_terms boolean default false,
  approval_hash text,
  proposta_numero text,
  version integer default 1,
  updated_at timestamp with time zone default now(),
  production_order_id uuid,
  signature_signed_at timestamp with time zone,
  prazo_producao text,
  prazo_entrega text,
  condicao_pagamento text,
  payment_terms text,
  imagem_url text,
  capa_url text,
  preview_url text,
  descricao text,
  resumo text,
  margem_percentual numeric,
  sinal_pago boolean default false,
  view_count integer default 0,
  last_viewed_at timestamp with time zone,
  origem text
);

create table public.provider_customers (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  customer_id text,
  provider text not null,
  provider_customer_id text not null,
  document_hash text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.quote_templates (
  id uuid default gen_random_uuid() not null,
  company_id uuid,
  nome text not null,
  tipo text not null,
  perguntas jsonb default '[]'::jsonb not null,
  ativo boolean default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table public.recurring_orders (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  original_order_id uuid,
  customer_name text,
  customer_phone text,
  title text,
  frequency text,
  next_due_at timestamp with time zone,
  last_repeated_at timestamp with time zone,
  status text default 'ativo'::text not null,
  notes text,
  created_by uuid,
  created_at timestamp with time zone default now() not null
);

create table public.security_blocklist (
  id uuid default gen_random_uuid() not null,
  type text not null,
  value text not null,
  reason text,
  active boolean default true not null,
  created_by text,
  created_at timestamp with time zone default now()
);

create table public.security_events (
  id uuid default gen_random_uuid() not null,
  company_id uuid,
  actor_user_id uuid,
  event_type text default 'security_event'::text not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now(),
  severity text default 'baixa'::text not null,
  source text default 'site'::text not null,
  path text,
  method text,
  ip text,
  user_agent text,
  user_email text,
  description text,
  resolved boolean default false not null,
  resolved_at timestamp with time zone,
  resolved_by text
);

create table public.signup_lead_followups (
  id uuid default gen_random_uuid() not null,
  lead_id uuid not null,
  channel text default 'whatsapp'::text not null,
  status text default 'pendente'::text not null,
  message text,
  scheduled_for timestamp with time zone default now(),
  sent_at timestamp with time zone,
  admin_email text,
  raw_data jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now(),
  created_by_admin_id uuid,
  sales_event_type text default 'contact'::text not null
);

create table public.signup_leads (
  id uuid default gen_random_uuid() not null,
  nome_responsavel text,
  email text not null,
  whatsapp text,
  empresa_nome text not null,
  slug_sugerido text,
  segmento text,
  modelo_negocio text,
  cidade text,
  estado text,
  plano text default 'profissional'::text not null,
  status text default 'lead'::text not null,
  marketing_opt_in boolean default false not null,
  marketing_opt_in_text text,
  lead_source text default 'cadastro'::text not null,
  checkout_url text,
  mercado_pago_preference_id text,
  mercado_pago_payment_id text,
  payment_status text,
  paid_at timestamp with time zone,
  followup_count integer default 0 not null,
  last_followup_at timestamp with time zone,
  next_followup_at timestamp with time zone default (now() + '2 days'::interval),
  converted_user_id uuid,
  converted_company_id uuid,
  raw_data jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  referral_code text,
  affiliate_referral_id uuid,
  sales_stage text default 'novo'::text not null,
  assigned_to_admin_id uuid,
  created_by_admin_id uuid,
  sales_notes text,
  sales_stage_updated_at timestamp with time zone default now() not null,
  sales_last_contact_at timestamp with time zone,
  sales_next_action_at timestamp with time zone,
  sales_lost_reason text
);

create table public.site_sections (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  type text default 'custom'::text not null,
  title text,
  subtitle text,
  content text,
  image_url text,
  button_label text,
  button_url text,
  sort_order integer default 0 not null,
  active boolean default true not null,
  locked boolean default false not null,
  config jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table public.site_template_presets (
  id text not null,
  name text not null,
  segment text not null,
  description text,
  payload jsonb default '{}'::jsonb not null,
  is_active boolean default true not null,
  created_at timestamp with time zone default now() not null
);

create table public.smart_notification_events (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  event_key text not null,
  event_type text not null,
  entity text,
  entity_id text,
  created_at timestamp with time zone default now() not null,
  resolved_at timestamp with time zone
);

create table public.smart_notification_settings (
  company_id uuid not null,
  new_order_enabled boolean default true not null,
  order_stuck_enabled boolean default true not null,
  order_stuck_days integer default 3 not null,
  task_due_today_enabled boolean default true not null,
  lead_idle_enabled boolean default true not null,
  lead_idle_days integer default 3 not null,
  proposal_idle_enabled boolean default true not null,
  proposal_idle_days integer default 3 not null,
  coupon_expiring_enabled boolean default true not null,
  coupon_expiring_days integer default 3 not null,
  product_without_image_enabled boolean default true not null,
  site_without_logo_enabled boolean default true not null,
  subscription_expiring_enabled boolean default true not null,
  subscription_expiring_days integer default 7 not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.subscription_events (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  event_type text not null,
  old_status text,
  new_status text,
  provider text default 'mercado_pago'::text not null,
  provider_reference text,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  provider_event_id text,
  provider_object_id text,
  payload_hash text,
  processing_status text,
  processed_at timestamp with time zone,
  error_message text
);

create table public.system_audit_logs (
  id uuid default gen_random_uuid() not null,
  company_id uuid,
  user_id uuid,
  action text not null,
  entity text,
  entity_id text,
  details jsonb default '{}'::jsonb not null,
  ip text,
  user_agent text,
  created_at timestamp with time zone default now() not null
);

create table public.whatsapp_conversations (
  id uuid default gen_random_uuid() not null,
  company_id uuid,
  phone text not null,
  customer_name text,
  last_inbound_at timestamp with time zone,
  last_outbound_at timestamp with time zone,
  last_message text,
  ai_enabled boolean default true not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.whatsapp_message_logs (
  id uuid default gen_random_uuid() not null,
  company_id uuid,
  order_id uuid,
  proposal_id uuid,
  direction text default 'outbound'::text not null,
  event_type text,
  to_phone text,
  from_phone text,
  message_type text default 'text'::text not null,
  content text,
  status text default 'pending'::text not null,
  meta_message_id text,
  raw_payload jsonb,
  raw_response jsonb,
  error text,
  created_at timestamp with time zone default now() not null
);
