-- Recovery R3 structural integrity. Tables exist before cyclic foreign keys.
set lock_timeout = '5s';
set statement_timeout = '120s';

alter table orcaly_private.affiliate_payout_accounts add constraint affiliate_payout_accounts_affiliate_id_fkey FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles(id) ON DELETE CASCADE;
alter table orcaly_private.affiliate_payout_accounts add constraint affiliate_payout_accounts_affiliate_id_key UNIQUE (affiliate_id);
alter table orcaly_private.affiliate_payout_accounts add constraint affiliate_payout_accounts_pix_key_type_check CHECK (pix_key_type = ANY (ARRAY['CPF'::text, 'CNPJ'::text, 'EMAIL'::text, 'PHONE'::text, 'EVP'::text]));
alter table orcaly_private.affiliate_payout_accounts add constraint affiliate_payout_accounts_pkey PRIMARY KEY (id);
alter table orcaly_private.api_rate_limits add constraint api_rate_limits_pkey PRIMARY KEY (key);
alter table orcaly_private.api_rate_limits add constraint api_rate_limits_request_count_check CHECK (request_count >= 0);
alter table public.admin_audit_logs add constraint admin_audit_logs_pkey PRIMARY KEY (id);
alter table public.admin_bug_reports add constraint admin_bug_reports_fingerprint_key UNIQUE (fingerprint);
alter table public.admin_bug_reports add constraint admin_bug_reports_pkey PRIMARY KEY (id);
alter table public.admin_bug_reports add constraint admin_bug_reports_severity_check CHECK (severity = ANY (ARRAY['verde'::text, 'amarelo'::text, 'vermelho'::text]));
alter table public.admin_bug_reports add constraint admin_bug_severity_check CHECK (severity = ANY (ARRAY['baixa'::text, 'media'::text, 'alta'::text, 'critica'::text]));
alter table public.admin_bug_reports add constraint admin_bug_status_check CHECK (status = ANY (ARRAY['aberto'::text, 'em_analise'::text, 'resolvido'::text, 'ignorado'::text]));
alter table public.admin_scan_runs add constraint admin_scan_runs_pkey PRIMARY KEY (id);
alter table public.admin_scan_runs add constraint admin_scan_status_check CHECK (status = ANY (ARRAY['rodando'::text, 'concluido'::text, 'falhou'::text]));
alter table public.admin_system_snapshots add constraint admin_system_snapshots_pkey PRIMARY KEY (id);
alter table public.admin_users add constraint admin_users_email_key UNIQUE (email);
alter table public.admin_users add constraint admin_users_pkey PRIMARY KEY (id);
alter table public.admin_users add constraint admin_users_role_check CHECK (role = ANY (ARRAY['super_admin'::text, 'admin'::text, 'suporte'::text]));
alter table public.affiliate_achievements add constraint affiliate_achievements_affiliate_id_achievement_id_key UNIQUE (affiliate_id, achievement_id);
alter table public.affiliate_achievements add constraint affiliate_achievements_affiliate_id_fkey FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles(id) ON DELETE CASCADE;
alter table public.affiliate_achievements add constraint affiliate_achievements_pkey PRIMARY KEY (id);
alter table public.affiliate_activity_events add constraint affiliate_activity_events_affiliate_id_fkey FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles(id) ON DELETE CASCADE;
alter table public.affiliate_activity_events add constraint affiliate_activity_events_kind_check CHECK (kind = ANY (ARRAY['contact'::text, 'demo'::text, 'trial'::text, 'converted'::text, 'content'::text, 'lesson'::text, 'quiz'::text, 'practice'::text, 'follow_up'::text, 'task'::text, 'manual'::text]));
alter table public.affiliate_activity_events add constraint affiliate_activity_events_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES affiliate_leads(id) ON DELETE SET NULL;
alter table public.affiliate_activity_events add constraint affiliate_activity_events_pkey PRIMARY KEY (id);
alter table public.affiliate_activity_events add constraint affiliate_activity_events_xp_check CHECK (xp >= 0 AND xp <= 500);
alter table public.affiliate_announcements add constraint affiliate_announcements_kind_check CHECK (kind = ANY (ARRAY['news'::text, 'training'::text, 'product'::text, 'community'::text]));
alter table public.affiliate_announcements add constraint affiliate_announcements_pkey PRIMARY KEY (id);
alter table public.affiliate_audit_logs add constraint affiliate_audit_logs_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.affiliate_audit_logs add constraint affiliate_audit_logs_affiliate_id_fkey FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles(id) ON DELETE SET NULL;
alter table public.affiliate_audit_logs add constraint affiliate_audit_logs_pkey PRIMARY KEY (id);
alter table public.affiliate_certifications add constraint affiliate_certifications_affiliate_id_certification_id_key UNIQUE (affiliate_id, certification_id);
alter table public.affiliate_certifications add constraint affiliate_certifications_affiliate_id_fkey FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles(id) ON DELETE CASCADE;
alter table public.affiliate_certifications add constraint affiliate_certifications_pkey PRIMARY KEY (id);
alter table public.affiliate_certifications add constraint affiliate_certifications_score_check CHECK (score >= 0::numeric AND score <= 100::numeric);
alter table public.affiliate_certifications add constraint affiliate_certifications_status_check CHECK (status = ANY (ARRAY['issued'::text, 'expired'::text, 'revoked'::text]));
alter table public.affiliate_clicks add constraint affiliate_clicks_affiliate_id_fkey FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles(id) ON DELETE CASCADE;
alter table public.affiliate_clicks add constraint affiliate_clicks_pkey PRIMARY KEY (id);
alter table public.affiliate_commissions add constraint affiliate_commissions_affiliate_id_fkey FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles(id) ON DELETE RESTRICT;
alter table public.affiliate_commissions add constraint affiliate_commissions_commission_amount_check CHECK (commission_amount >= 0::numeric);
alter table public.affiliate_commissions add constraint affiliate_commissions_commission_rate_check CHECK (commission_rate >= 0::numeric AND commission_rate <= 0.6000);
alter table public.affiliate_commissions add constraint affiliate_commissions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE RESTRICT;
alter table public.affiliate_commissions add constraint affiliate_commissions_eligible_amount_check CHECK (eligible_amount >= 0::numeric);
alter table public.affiliate_commissions add constraint affiliate_commissions_gross_amount_check CHECK (gross_amount >= 0::numeric);
alter table public.affiliate_commissions add constraint affiliate_commissions_payout_id_fkey FOREIGN KEY (payout_id) REFERENCES affiliate_payouts(id) ON DELETE SET NULL;
alter table public.affiliate_commissions add constraint affiliate_commissions_pkey PRIMARY KEY (id);
alter table public.affiliate_commissions add constraint affiliate_commissions_plan_payment_id_fkey FOREIGN KEY (plan_payment_id) REFERENCES plan_payments(id) ON DELETE SET NULL;
alter table public.affiliate_commissions add constraint affiliate_commissions_provider_payment_id_key UNIQUE (provider_payment_id);
alter table public.affiliate_commissions add constraint affiliate_commissions_referral_id_fkey FOREIGN KEY (referral_id) REFERENCES affiliate_referrals(id) ON DELETE RESTRICT;
alter table public.affiliate_commissions add constraint affiliate_commissions_referral_id_key UNIQUE (referral_id);
alter table public.affiliate_commissions add constraint affiliate_commissions_status_check CHECK (status = ANY (ARRAY['future'::text, 'hold'::text, 'available'::text, 'processing'::text, 'paid'::text, 'reversed'::text, 'rejected'::text]));
alter table public.affiliate_course_progress add constraint affiliate_course_progress_affiliate_id_course_id_lesson_id_key UNIQUE (affiliate_id, course_id, lesson_id);
alter table public.affiliate_course_progress add constraint affiliate_course_progress_affiliate_id_fkey FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles(id) ON DELETE CASCADE;
alter table public.affiliate_course_progress add constraint affiliate_course_progress_pkey PRIMARY KEY (id);
alter table public.affiliate_goals add constraint affiliate_goals_affiliate_id_fkey FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles(id) ON DELETE CASCADE;
alter table public.affiliate_goals add constraint affiliate_goals_affiliate_id_period_start_key UNIQUE (affiliate_id, period_start);
alter table public.affiliate_goals add constraint affiliate_goals_contacts_target_check CHECK (contacts_target >= 0);
alter table public.affiliate_goals add constraint affiliate_goals_content_target_check CHECK (content_target >= 0);
alter table public.affiliate_goals add constraint affiliate_goals_customers_target_check CHECK (customers_target >= 0);
alter table public.affiliate_goals add constraint affiliate_goals_demos_target_check CHECK (demos_target >= 0);
alter table public.affiliate_goals add constraint affiliate_goals_pkey PRIMARY KEY (id);
alter table public.affiliate_goals add constraint affiliate_goals_study_target_check CHECK (study_target >= 0);
alter table public.affiliate_goals add constraint affiliate_goals_trials_target_check CHECK (trials_target >= 0);
alter table public.affiliate_leads add constraint affiliate_leads_affiliate_id_fkey FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles(id) ON DELETE CASCADE;
alter table public.affiliate_leads add constraint affiliate_leads_estimated_value_check CHECK (estimated_value >= 0::numeric);
alter table public.affiliate_leads add constraint affiliate_leads_name_check CHECK (char_length(name) >= 2 AND char_length(name) <= 120);
alter table public.affiliate_leads add constraint affiliate_leads_pkey PRIMARY KEY (id);
alter table public.affiliate_leads add constraint affiliate_leads_status_check CHECK (status = ANY (ARRAY['new'::text, 'contacted'::text, 'demo'::text, 'trial'::text, 'converted'::text, 'lost'::text]));
alter table public.affiliate_payout_items add constraint affiliate_payout_items_amount_check CHECK (amount >= 0::numeric);
alter table public.affiliate_payout_items add constraint affiliate_payout_items_commission_id_fkey FOREIGN KEY (commission_id) REFERENCES affiliate_commissions(id) ON DELETE RESTRICT;
alter table public.affiliate_payout_items add constraint affiliate_payout_items_commission_id_key UNIQUE (commission_id);
alter table public.affiliate_payout_items add constraint affiliate_payout_items_payout_id_fkey FOREIGN KEY (payout_id) REFERENCES affiliate_payouts(id) ON DELETE CASCADE;
alter table public.affiliate_payout_items add constraint affiliate_payout_items_pkey PRIMARY KEY (payout_id, commission_id);
alter table public.affiliate_payouts add constraint affiliate_payouts_affiliate_id_fkey FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles(id) ON DELETE RESTRICT;
alter table public.affiliate_payouts add constraint affiliate_payouts_amount_check CHECK (amount >= 0::numeric);
alter table public.affiliate_payouts add constraint affiliate_payouts_debt_offset_check CHECK (debt_offset >= 0::numeric);
alter table public.affiliate_payouts add constraint affiliate_payouts_external_reference_key UNIQUE (external_reference);
alter table public.affiliate_payouts add constraint affiliate_payouts_gross_commissions_check CHECK (gross_commissions >= 0::numeric);
alter table public.affiliate_payouts add constraint affiliate_payouts_pkey PRIMARY KEY (id);
alter table public.affiliate_payouts add constraint affiliate_payouts_provider_check CHECK (provider = ANY (ARRAY['manual'::text, 'asaas'::text]));
alter table public.affiliate_payouts add constraint affiliate_payouts_status_check CHECK (status = ANY (ARRAY['requested'::text, 'approved'::text, 'processing'::text, 'paid'::text, 'failed'::text, 'cancelled'::text]));
alter table public.affiliate_profiles add constraint affiliate_profiles_code_check CHECK (code ~ '^[A-Z0-9][A-Z0-9_-]{3,31}$'::text);
alter table public.affiliate_profiles add constraint affiliate_profiles_commission_rate_check CHECK (commission_rate >= 0::numeric AND commission_rate <= 0.6000);
alter table public.affiliate_profiles add constraint affiliate_profiles_debt_balance_check CHECK (debt_balance >= 0::numeric);
alter table public.affiliate_profiles add constraint affiliate_profiles_document_type_check CHECK (document_type = ANY (ARRAY['CPF'::text, 'CNPJ'::text]));
alter table public.affiliate_profiles add constraint affiliate_profiles_name_check CHECK (char_length(TRIM(BOTH FROM name)) >= 2 AND char_length(TRIM(BOTH FROM name)) <= 100);
alter table public.affiliate_profiles add constraint affiliate_profiles_payout_status_check CHECK (payout_status = ANY (ARRAY['pending_verification'::text, 'verified'::text, 'blocked'::text]));
alter table public.affiliate_profiles add constraint affiliate_profiles_pkey PRIMARY KEY (id);
alter table public.affiliate_profiles add constraint affiliate_profiles_status_check CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'suspended'::text, 'rejected'::text, 'closed'::text]));
alter table public.affiliate_profiles add constraint affiliate_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.affiliate_profiles add constraint affiliate_profiles_user_id_key UNIQUE (user_id);
alter table public.affiliate_profiles add constraint affiliate_profiles_whatsapp_check CHECK (char_length(regexp_replace(whatsapp, '[^0-9]'::text, ''::text, 'g'::text)) >= 10 AND char_length(regexp_replace(whatsapp, '[^0-9]'::text, ''::text, 'g'::text)) <= 13);
alter table public.affiliate_program_settings add constraint affiliate_program_settings_attribution_days_check CHECK (attribution_days >= 1 AND attribution_days <= 180);
alter table public.affiliate_program_settings add constraint affiliate_program_settings_commission_rate_check CHECK (commission_rate >= 0::numeric AND commission_rate <= 0.6000);
alter table public.affiliate_program_settings add constraint affiliate_program_settings_hold_days_check CHECK (hold_days >= 7 AND hold_days <= 60);
alter table public.affiliate_program_settings add constraint affiliate_program_settings_id_check CHECK (id = 1);
alter table public.affiliate_program_settings add constraint affiliate_program_settings_minimum_payout_amount_check CHECK (minimum_payout_amount >= 1::numeric);
alter table public.affiliate_program_settings add constraint affiliate_program_settings_pkey PRIMARY KEY (id);
alter table public.affiliate_referrals add constraint affiliate_referrals_affiliate_id_fkey FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles(id) ON DELETE RESTRICT;
alter table public.affiliate_referrals add constraint affiliate_referrals_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.affiliate_referrals add constraint affiliate_referrals_company_id_key UNIQUE (company_id);
alter table public.affiliate_referrals add constraint affiliate_referrals_pkey PRIMARY KEY (id);
alter table public.affiliate_referrals add constraint affiliate_referrals_review_status_check CHECK (review_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'flagged'::text]));
alter table public.affiliate_referrals add constraint affiliate_referrals_signup_lead_id_fkey FOREIGN KEY (signup_lead_id) REFERENCES signup_leads(id) ON DELETE SET NULL;
alter table public.affiliate_referrals add constraint affiliate_referrals_signup_lead_id_key UNIQUE (signup_lead_id);
alter table public.affiliate_referrals add constraint affiliate_referrals_status_check CHECK (status = ANY (ARRAY['registered'::text, 'trial'::text, 'payment_pending'::text, 'qualified'::text, 'rejected'::text, 'reversed'::text, 'customer_active'::text, 'customer_cancelled'::text]));
alter table public.affiliate_tasks add constraint affiliate_tasks_affiliate_id_fkey FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles(id) ON DELETE CASCADE;
alter table public.affiliate_tasks add constraint affiliate_tasks_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES affiliate_leads(id) ON DELETE SET NULL;
alter table public.affiliate_tasks add constraint affiliate_tasks_pkey PRIMARY KEY (id);
alter table public.affiliate_tasks add constraint affiliate_tasks_priority_check CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text]));
alter table public.affiliate_tasks add constraint affiliate_tasks_task_type_check CHECK (task_type = ANY (ARRAY['follow_up'::text, 'demo'::text, 'prospecting'::text, 'content'::text, 'study'::text, 'other'::text]));
alter table public.affiliate_tasks add constraint affiliate_tasks_title_check CHECK (char_length(title) >= 2 AND char_length(title) <= 180);
alter table public.affiliate_training_sessions add constraint affiliate_training_sessions_affiliate_id_fkey FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles(id) ON DELETE CASCADE;
alter table public.affiliate_training_sessions add constraint affiliate_training_sessions_mode_check CHECK (mode = ANY (ARRAY['sales'::text, 'objection'::text, 'demo'::text, 'quiz'::text]));
alter table public.affiliate_training_sessions add constraint affiliate_training_sessions_pkey PRIMARY KEY (id);
alter table public.affiliate_training_sessions add constraint affiliate_training_sessions_total_score_check CHECK (total_score >= 0::numeric AND total_score <= 100::numeric);
alter table public.app_notifications add constraint app_notifications_pkey PRIMARY KEY (id);
alter table public.art_approval_requests add constraint art_approval_requests_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.art_approval_requests add constraint art_approval_requests_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL;
alter table public.art_approval_requests add constraint art_approval_requests_pkey PRIMARY KEY (id);
alter table public.art_approval_requests add constraint art_approval_requests_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES proposals(id) ON DELETE SET NULL;
alter table public.art_approval_requests add constraint art_approval_requests_token_key UNIQUE (token);
alter table public.business_hours add constraint business_hours_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.business_hours add constraint business_hours_company_weekday_unique UNIQUE (company_id, weekday);
alter table public.business_hours add constraint business_hours_pkey PRIMARY KEY (id);
alter table public.companies add constraint companies_founder_billing_attempts_check CHECK (founder_billing_attempts >= 0);
alter table public.companies add constraint companies_founder_billing_claim_pair_check CHECK ((founder_billing_claim_id IS NULL) = (founder_billing_claimed_at IS NULL));
alter table public.companies add constraint companies_founder_conversion_attempts_check CHECK (founder_price_conversion_attempts >= 0);
alter table public.companies add constraint companies_founder_conversion_claim_pair_check CHECK ((founder_price_conversion_claim_id IS NULL) = (founder_price_conversion_claimed_at IS NULL));
alter table public.companies add constraint companies_founder_conversion_timeline_check CHECK (founder_price_converted_at IS NULL OR founder_price_ends_at IS NULL OR founder_price_converted_at >= founder_price_ends_at);
alter table public.companies add constraint companies_founder_number_check CHECK (founder_number IS NULL OR founder_number >= 0 AND founder_number <= 10);
alter table public.companies add constraint companies_founder_plan_price_check CHECK (NOT is_founder OR
CASE lower(COALESCE(assinatura_plano, plano, ''::text))
    WHEN 'basico'::text THEN founder_price_cents = 3490
    WHEN 'básico'::text THEN founder_price_cents = 3490
    WHEN 'essencial'::text THEN founder_price_cents = 3490
    WHEN 'profissional'::text THEN founder_price_cents = 6990
    WHEN 'intermediario'::text THEN founder_price_cents = 6990
    WHEN 'intermediário'::text THEN founder_price_cents = 6990
    WHEN 'premium'::text THEN founder_price_cents = 9990
    ELSE false
END);
alter table public.companies add constraint companies_founder_price_check CHECK (founder_price_cents IS NULL OR (founder_price_cents = ANY (ARRAY[3490, 6990, 9990])));
alter table public.companies add constraint companies_founder_required_fields_check CHECK (NOT is_founder OR founder_number IS NOT NULL AND founder_price_cents IS NOT NULL AND founder_started_at IS NOT NULL AND founder_trial_ends_at IS NOT NULL AND founder_price_ends_at IS NOT NULL);
alter table public.companies add constraint companies_founder_timeline_check CHECK (NOT is_founder OR founder_trial_ends_at = (founder_started_at + '30 days'::interval) AND founder_price_ends_at = (founder_trial_ends_at + '6 mons'::interval));
alter table public.companies add constraint companies_nome_security_check CHECK (length(TRIM(BOTH FROM nome)) >= 2 AND length(TRIM(BOTH FROM nome)) <= 80 AND (lower(TRIM(BOTH FROM nome)) <> ALL (ARRAY['admin'::text, 'administrador'::text, 'orcaly'::text, 'orçaly'::text, 'root'::text, 'system'::text, 'sistema'::text])) AND lower(TRIM(BOTH FROM nome)) !~~ '%orcaly%'::text AND lower(TRIM(BOTH FROM nome)) !~~ '%orçaly%'::text);
alter table public.companies add constraint companies_pkey PRIMARY KEY (id);
alter table public.companies add constraint companies_slug_key UNIQUE (slug);
alter table public.companies add constraint companies_slug_security_check CHECK (slug ~ '^[a-z0-9][a-z0-9-]{1,40}[a-z0-9]$'::text AND slug !~~ '%--%'::text AND (lower(slug) <> ALL (ARRAY['admin'::text, 'administrador'::text, 'orcaly'::text, 'suporte'::text, 'support'::text, 'api'::text, 'painel'::text, 'dashboard'::text, 'login'::text, 'cadastro'::text, 'checkout'::text, 'assinatura'::text, 'proposta'::text, 'propostas'::text, 'root'::text, 'system'::text, 'sistema'::text, 'mercado-pago'::text, 'mercadopago'::text, 'www'::text, 'app'::text, 'assets'::text, 'static'::text, 'public'::text, 'private'::text, 'config'::text, 'settings'::text, 'security'::text, 'auth'::text, 'null'::text, 'undefined'::text])));
alter table public.companies add constraint companies_subdomain_slug_security_check CHECK (subdomain_slug IS NULL OR length(subdomain_slug) >= 3 AND length(subdomain_slug) <= 42 AND subdomain_slug ~ '^[a-z0-9]+$'::text AND (lower(subdomain_slug) <> ALL (ARRAY['admin'::text, 'administrador'::text, 'orcaly'::text, 'suporte'::text, 'support'::text, 'api'::text, 'painel'::text, 'dashboard'::text, 'login'::text, 'cadastro'::text, 'checkout'::text, 'assinatura'::text, 'proposta'::text, 'propostas'::text, 'root'::text, 'system'::text, 'sistema'::text, 'mercadopago'::text, 'www'::text, 'app'::text, 'assets'::text, 'static'::text, 'public'::text, 'private'::text, 'config'::text, 'settings'::text, 'security'::text, 'auth'::text, 'null'::text, 'undefined'::text])));
alter table public.companies add constraint companies_tester_id_fkey FOREIGN KEY (tester_id) REFERENCES auth.users(id);
alter table public.company_members add constraint company_members_cargo_check CHECK (cargo = ANY (ARRAY['gerente'::text, 'atendente'::text, 'producao'::text]));
alter table public.company_members add constraint company_members_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.company_members add constraint company_members_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
alter table public.company_members add constraint company_members_pkey PRIMARY KEY (id);
alter table public.company_members add constraint company_members_status_check CHECK (status = ANY (ARRAY['ativo'::text, 'bloqueado'::text, 'removido'::text]));
alter table public.company_members add constraint company_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.company_niche_templates add constraint company_niche_templates_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.company_niche_templates add constraint company_niche_templates_company_id_key UNIQUE (company_id);
alter table public.company_niche_templates add constraint company_niche_templates_pkey PRIMARY KEY (id);
alter table public.company_proposal_settings add constraint company_proposal_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.company_proposal_settings add constraint company_proposal_settings_company_id_key UNIQUE (company_id);
alter table public.company_proposal_settings add constraint company_proposal_settings_pkey PRIMARY KEY (id);
alter table public.company_whatsapp_settings add constraint company_whatsapp_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.company_whatsapp_settings add constraint company_whatsapp_settings_pkey PRIMARY KEY (company_id);
alter table public.crm_leads add constraint crm_leads_pkey PRIMARY KEY (id);
alter table public.customer_followups add constraint customer_followups_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.customer_followups add constraint customer_followups_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
alter table public.customer_followups add constraint customer_followups_pkey PRIMARY KEY (id);
alter table public.customer_followups add constraint customer_followups_prioridade_check CHECK (prioridade = ANY (ARRAY['baixa'::text, 'media'::text, 'alta'::text]));
alter table public.customer_followups add constraint customer_followups_status_check CHECK (status = ANY (ARRAY['pendente'::text, 'concluido'::text, 'cancelado'::text]));
alter table public.customer_internal_notes add constraint customer_internal_notes_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.customer_internal_notes add constraint customer_internal_notes_pkey PRIMARY KEY (id);
alter table public.customer_magic_links add constraint customer_magic_links_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.customer_magic_links add constraint customer_magic_links_pkey PRIMARY KEY (id);
alter table public.customer_magic_links add constraint customer_magic_links_token_key UNIQUE (token);
alter table public.customer_notes add constraint customer_notes_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.customer_notes add constraint customer_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
alter table public.customer_notes add constraint customer_notes_pkey PRIMARY KEY (id);
alter table public.customer_notes add constraint customer_notes_tipo_check CHECK (tipo = ANY (ARRAY['nota'::text, 'whatsapp'::text, 'ligacao'::text, 'feedback'::text, 'financeiro'::text, 'proposta'::text]));
alter table public.customer_portal_events add constraint customer_portal_events_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.customer_portal_events add constraint customer_portal_events_customer_magic_link_id_fkey FOREIGN KEY (customer_magic_link_id) REFERENCES customer_magic_links(id) ON DELETE CASCADE;
alter table public.customer_portal_events add constraint customer_portal_events_pkey PRIMARY KEY (id);
alter table public.deliveries add constraint deliveries_assigned_driver_id_fkey FOREIGN KEY (assigned_driver_id) REFERENCES delivery_drivers(id) ON DELETE SET NULL;
alter table public.deliveries add constraint deliveries_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.deliveries add constraint deliveries_delivery_zone_id_fkey FOREIGN KEY (delivery_zone_id) REFERENCES delivery_zones(id) ON DELETE SET NULL;
alter table public.deliveries add constraint deliveries_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL;
alter table public.deliveries add constraint deliveries_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES payment_methods(id) ON DELETE SET NULL;
alter table public.deliveries add constraint deliveries_pkey PRIMARY KEY (id);
alter table public.delivery_assignments add constraint delivery_assignments_amounts_check CHECK (order_total >= 0::numeric AND delivery_fee >= 0::numeric);
alter table public.delivery_assignments add constraint delivery_assignments_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.delivery_assignments add constraint delivery_assignments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.delivery_assignments add constraint delivery_assignments_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES deliveries(id) ON DELETE SET NULL;
alter table public.delivery_assignments add constraint delivery_assignments_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES delivery_drivers(id) ON DELETE SET NULL;
alter table public.delivery_assignments add constraint delivery_assignments_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL;
alter table public.delivery_assignments add constraint delivery_assignments_pkey PRIMARY KEY (id);
alter table public.delivery_assignments add constraint delivery_assignments_settlement_check CHECK (settlement_status = ANY (ARRAY['pending'::text, 'settled'::text, 'waived'::text]));
alter table public.delivery_assignments add constraint delivery_assignments_status_check CHECK (status = ANY (ARRAY['assigned'::text, 'out_for_delivery'::text, 'delivered'::text, 'canceled'::text, 'reassigned'::text]));
alter table public.delivery_drivers add constraint delivery_drivers_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.delivery_drivers add constraint delivery_drivers_name_check CHECK (char_length(TRIM(BOTH FROM name)) >= 2 AND char_length(TRIM(BOTH FROM name)) <= 80);
alter table public.delivery_drivers add constraint delivery_drivers_pkey PRIMARY KEY (id);
alter table public.delivery_drivers add constraint delivery_drivers_plate_check CHECK (vehicle_plate IS NULL OR char_length(TRIM(BOTH FROM vehicle_plate)) >= 5 AND char_length(TRIM(BOTH FROM vehicle_plate)) <= 10);
alter table public.delivery_drivers add constraint delivery_drivers_whatsapp_check CHECK (char_length(regexp_replace(whatsapp, '[^0-9]'::text, ''::text, 'g'::text)) >= 10 AND char_length(regexp_replace(whatsapp, '[^0-9]'::text, ''::text, 'g'::text)) <= 13);
alter table public.delivery_zones add constraint delivery_zones_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.delivery_zones add constraint delivery_zones_pkey PRIMARY KEY (id);
alter table public.finance_accounts add constraint finance_accounts_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.finance_accounts add constraint finance_accounts_pkey PRIMARY KEY (id);
alter table public.finance_accounts add constraint finance_accounts_tipo_check CHECK (tipo = ANY (ARRAY['caixa'::text, 'banco'::text, 'cartao'::text, 'digital'::text, 'outro'::text]));
alter table public.financial_categories add constraint financial_categories_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.financial_categories add constraint financial_categories_pkey PRIMARY KEY (id);
alter table public.financial_material_entries add constraint financial_material_entries_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.financial_material_entries add constraint financial_material_entries_pkey PRIMARY KEY (id);
alter table public.financial_material_entries add constraint financial_material_entries_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES financial_transactions(id) ON DELETE CASCADE;
alter table public.financial_transactions add constraint financial_transactions_account_id_fkey FOREIGN KEY (account_id) REFERENCES finance_accounts(id) ON DELETE SET NULL;
alter table public.financial_transactions add constraint financial_transactions_category_id_fkey FOREIGN KEY (category_id) REFERENCES financial_categories(id) ON DELETE SET NULL;
alter table public.financial_transactions add constraint financial_transactions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.financial_transactions add constraint financial_transactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
alter table public.financial_transactions add constraint financial_transactions_pkey PRIMARY KEY (id);
alter table public.financial_transactions add constraint financial_transactions_status_check CHECK (status = ANY (ARRAY['pago'::text, 'pendente'::text, 'cancelado'::text]));
alter table public.financial_transactions add constraint financial_transactions_tipo_check CHECK (tipo = ANY (ARRAY['entrada'::text, 'saida'::text]));
alter table public.founder_invites add constraint founder_invites_activation_attempts_check CHECK (activation_attempts >= 0);
alter table public.founder_invites add constraint founder_invites_activation_claim_pair_check CHECK (activation_claim_id IS NULL AND activation_claimed_at IS NULL OR activation_claim_id IS NOT NULL AND activation_claimed_at IS NOT NULL);
alter table public.founder_invites add constraint founder_invites_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.founder_invites add constraint founder_invites_created_by_admin_id_fkey FOREIGN KEY (created_by_admin_id) REFERENCES platform_admins(id) ON DELETE SET NULL;
alter table public.founder_invites add constraint founder_invites_email_check CHECK (length(email_normalized) >= 3 AND POSITION(('@'::text) IN (email_normalized)) > 1);
alter table public.founder_invites add constraint founder_invites_number_check CHECK (founder_number >= 0 AND founder_number <= 10);
alter table public.founder_invites add constraint founder_invites_pkey PRIMARY KEY (id);
alter table public.founder_invites add constraint founder_invites_plan_check CHECK (plan_key = ANY (ARRAY['basico'::text, 'profissional'::text, 'premium'::text]));
alter table public.founder_invites add constraint founder_invites_price_check CHECK (plan_key = 'basico'::text AND founder_price_cents = 3490 OR plan_key = 'profissional'::text AND founder_price_cents = 6990 OR plan_key = 'premium'::text AND founder_price_cents = 9990);
alter table public.founder_invites add constraint founder_invites_revoked_by_admin_id_fkey FOREIGN KEY (revoked_by_admin_id) REFERENCES platform_admins(id) ON DELETE SET NULL;
alter table public.founder_invites add constraint founder_invites_sales_lead_id_fkey FOREIGN KEY (sales_lead_id) REFERENCES signup_leads(id) ON DELETE SET NULL;
alter table public.founder_invites add constraint founder_invites_state_check CHECK (status = 'pending'::text AND activated_at IS NULL AND revoked_at IS NULL AND user_id IS NULL AND company_id IS NULL AND activation_claim_id IS NULL AND activation_claimed_at IS NULL OR status = 'activating'::text AND activated_at IS NULL AND revoked_at IS NULL AND user_id IS NULL AND company_id IS NULL AND activation_claim_id IS NOT NULL AND activation_claimed_at IS NOT NULL OR status = 'activated'::text AND activated_at IS NOT NULL AND revoked_at IS NULL AND user_id IS NOT NULL AND company_id IS NOT NULL AND activation_claim_id IS NULL AND activation_claimed_at IS NULL OR status = 'revoked'::text AND activated_at IS NULL AND revoked_at IS NOT NULL AND user_id IS NULL AND company_id IS NULL AND activation_claim_id IS NULL AND activation_claimed_at IS NULL OR status = 'expired'::text AND activated_at IS NULL AND user_id IS NULL AND company_id IS NULL AND activation_claim_id IS NULL AND activation_claimed_at IS NULL);
alter table public.founder_invites add constraint founder_invites_status_check CHECK (status = ANY (ARRAY['pending'::text, 'activating'::text, 'activated'::text, 'revoked'::text, 'expired'::text]));
alter table public.founder_invites add constraint founder_invites_token_hash_check CHECK (token_hash ~ '^[0-9a-f]{64}$'::text);
alter table public.founder_invites add constraint founder_invites_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.internal_tasks add constraint internal_tasks_pkey PRIMARY KEY (id);
alter table public.marketplace_commission_rules add constraint marketplace_commission_rules_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.marketplace_commission_rules add constraint marketplace_commission_rules_pkey PRIMARY KEY (id);
alter table public.marketplace_commissions add constraint marketplace_commissions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.marketplace_commissions add constraint marketplace_commissions_marketplace_payment_id_fkey FOREIGN KEY (marketplace_payment_id) REFERENCES marketplace_payments(id) ON DELETE SET NULL;
alter table public.marketplace_commissions add constraint marketplace_commissions_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL;
alter table public.marketplace_commissions add constraint marketplace_commissions_pkey PRIMARY KEY (id);
alter table public.marketplace_coupons add constraint marketplace_coupons_pkey PRIMARY KEY (id);
alter table public.marketplace_coupons add constraint marketplace_coupons_tipo_check CHECK (tipo = ANY (ARRAY['percentual'::text, 'fixo'::text]));
alter table public.marketplace_oauth_states add constraint marketplace_oauth_states_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.marketplace_oauth_states add constraint marketplace_oauth_states_pkey PRIMARY KEY (id);
alter table public.marketplace_oauth_states add constraint marketplace_oauth_states_state_hash_key UNIQUE (state_hash);
alter table public.marketplace_oauth_states add constraint marketplace_oauth_states_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.marketplace_payment_settings add constraint marketplace_payment_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.marketplace_payment_settings add constraint marketplace_payment_settings_company_id_provider_key UNIQUE (company_id, provider);
alter table public.marketplace_payment_settings add constraint marketplace_payment_settings_pkey PRIMARY KEY (id);
alter table public.marketplace_payments add constraint marketplace_payments_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.marketplace_payments add constraint marketplace_payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL;
alter table public.marketplace_payments add constraint marketplace_payments_pkey PRIMARY KEY (id);
alter table public.marketplace_payments add constraint marketplace_payments_stock_reservation_status_check CHECK (stock_reservation_status IS NULL OR (stock_reservation_status = ANY (ARRAY['reserved'::text, 'confirmed'::text, 'released'::text, 'expired'::text, 'review_required'::text])));
alter table public.marketplace_stock_reservations add constraint marketplace_stock_reservation_marketplace_payment_id_produc_key UNIQUE (marketplace_payment_id, product_id);
alter table public.marketplace_stock_reservations add constraint marketplace_stock_reservations_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.marketplace_stock_reservations add constraint marketplace_stock_reservations_marketplace_payment_id_fkey FOREIGN KEY (marketplace_payment_id) REFERENCES marketplace_payments(id) ON DELETE CASCADE;
alter table public.marketplace_stock_reservations add constraint marketplace_stock_reservations_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
alter table public.marketplace_stock_reservations add constraint marketplace_stock_reservations_pkey PRIMARY KEY (id);
alter table public.marketplace_stock_reservations add constraint marketplace_stock_reservations_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT;
alter table public.marketplace_stock_reservations add constraint marketplace_stock_reservations_quantity_check CHECK (quantity > 0);
alter table public.marketplace_stock_reservations add constraint marketplace_stock_reservations_status_check CHECK (status = ANY (ARRAY['reserved'::text, 'confirmed'::text, 'released'::text, 'expired'::text, 'review_required'::text]));
alter table public.marketplace_stock_reservations add constraint marketplace_stock_reservations_stock_after_check CHECK (stock_after >= 0);
alter table public.marketplace_stock_reservations add constraint marketplace_stock_reservations_stock_before_check CHECK (stock_before >= 0);
alter table public.notifications add constraint notifications_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.notifications add constraint notifications_pkey PRIMARY KEY (id);
alter table public.notifications add constraint notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.order_internal_comments add constraint order_internal_comments_pkey PRIMARY KEY (id);
alter table public.order_items add constraint order_items_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);
alter table public.order_items add constraint order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
alter table public.order_items add constraint order_items_pkey PRIMARY KEY (id);
alter table public.order_items add constraint order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
alter table public.order_payments add constraint order_payments_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.order_payments add constraint order_payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
alter table public.order_payments add constraint order_payments_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES payment_methods(id) ON DELETE SET NULL;
alter table public.order_payments add constraint order_payments_pkey PRIMARY KEY (id);
alter table public.order_status_history add constraint order_status_history_pkey PRIMARY KEY (id);
alter table public.orders add constraint orders_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);
alter table public.orders add constraint orders_delivery_zone_id_fkey FOREIGN KEY (delivery_zone_id) REFERENCES delivery_zones(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_marketplace_payment_id_fkey FOREIGN KEY (marketplace_payment_id) REFERENCES marketplace_payments(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_original_order_id_fkey FOREIGN KEY (original_order_id) REFERENCES orders(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES payment_methods(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_pkey PRIMARY KEY (id);
alter table public.payment_methods add constraint payment_methods_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.payment_methods add constraint payment_methods_pkey PRIMARY KEY (id);
alter table public.payment_payouts add constraint payment_payouts_pkey PRIMARY KEY (id);
alter table public.payment_webhook_events add constraint payment_webhook_events_pkey PRIMARY KEY (id);
alter table public.payment_webhook_events add constraint payment_webhook_events_provider_provider_event_id_key UNIQUE (provider, provider_event_id);
alter table public.plan_payments add constraint plan_payments_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.plan_payments add constraint plan_payments_pkey PRIMARY KEY (id);
alter table public.platform_admin_invites add constraint platform_admin_invites_area_check CHECK (length(btrim(area)) >= 2 AND length(btrim(area)) <= 80);
alter table public.platform_admin_invites add constraint platform_admin_invites_created_by_admin_id_fkey FOREIGN KEY (created_by_admin_id) REFERENCES platform_admins(id) ON DELETE SET NULL;
alter table public.platform_admin_invites add constraint platform_admin_invites_email_check CHECK (length(btrim(email)) >= 5 AND length(btrim(email)) <= 320 AND POSITION(('@'::text) IN (btrim(email))) > 1);
alter table public.platform_admin_invites add constraint platform_admin_invites_expiry_check CHECK (expires_at > invited_at);
alter table public.platform_admin_invites add constraint platform_admin_invites_nome_check CHECK (length(btrim(nome)) >= 2 AND length(btrim(nome)) <= 160);
alter table public.platform_admin_invites add constraint platform_admin_invites_observacoes_check CHECK (observacoes IS NULL OR length(observacoes) <= 500);
alter table public.platform_admin_invites add constraint platform_admin_invites_permissions_object_check CHECK (jsonb_typeof(permissions) = 'object'::text);
alter table public.platform_admin_invites add constraint platform_admin_invites_pkey PRIMARY KEY (id);
alter table public.platform_admin_invites add constraint platform_admin_invites_platform_admin_id_fkey FOREIGN KEY (platform_admin_id) REFERENCES platform_admins(id) ON DELETE SET NULL;
alter table public.platform_admin_invites add constraint platform_admin_invites_role_check CHECK (lower(role) = 'prospector'::text);
alter table public.platform_admin_invites add constraint platform_admin_invites_state_check CHECK (status = 'pending'::text AND claimed_at IS NULL AND activation_claim_id IS NULL AND activated_at IS NULL AND revoked_at IS NULL AND user_id IS NULL AND platform_admin_id IS NULL OR status = 'activating'::text AND claimed_at IS NOT NULL AND activation_claim_id IS NOT NULL AND activated_at IS NULL AND revoked_at IS NULL AND user_id IS NULL AND platform_admin_id IS NULL OR status = 'activated'::text AND claimed_at IS NULL AND activation_claim_id IS NULL AND activated_at IS NOT NULL AND revoked_at IS NULL AND user_id IS NOT NULL AND platform_admin_id IS NOT NULL OR status = 'revoked'::text AND claimed_at IS NULL AND activation_claim_id IS NULL AND activated_at IS NULL AND revoked_at IS NOT NULL AND user_id IS NULL AND platform_admin_id IS NULL OR status = 'expired'::text AND claimed_at IS NULL AND activation_claim_id IS NULL AND activated_at IS NULL AND revoked_at IS NULL AND user_id IS NULL AND platform_admin_id IS NULL);
alter table public.platform_admin_invites add constraint platform_admin_invites_status_check CHECK (status = ANY (ARRAY['pending'::text, 'activating'::text, 'activated'::text, 'revoked'::text, 'expired'::text]));
alter table public.platform_admin_invites add constraint platform_admin_invites_token_hash_check CHECK (token_hash ~ '^[0-9a-f]{64}$'::text);
alter table public.platform_admin_invites add constraint platform_admin_invites_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.platform_admins add constraint platform_admins_email_key UNIQUE (email);
alter table public.platform_admins add constraint platform_admins_pkey PRIMARY KEY (id);
alter table public.platform_admins add constraint platform_admins_role_check_v2 CHECK (lower(role) = ANY (ARRAY['owner'::text, 'super_admin'::text, 'admin'::text, 'finance'::text, 'support'::text, 'suporte'::text, 'prospector'::text]));
alter table public.platform_admins add constraint platform_admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.product_stock_movements add constraint product_stock_movements_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.product_stock_movements add constraint product_stock_movements_idempotency_key_key UNIQUE (idempotency_key);
alter table public.product_stock_movements add constraint product_stock_movements_marketplace_payment_id_fkey FOREIGN KEY (marketplace_payment_id) REFERENCES marketplace_payments(id) ON DELETE SET NULL;
alter table public.product_stock_movements add constraint product_stock_movements_movement_type_check CHECK (movement_type = ANY (ARRAY['reserve'::text, 'confirm'::text, 'release'::text, 'expire'::text, 'review_required'::text]));
alter table public.product_stock_movements add constraint product_stock_movements_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL;
alter table public.product_stock_movements add constraint product_stock_movements_pkey PRIMARY KEY (id);
alter table public.product_stock_movements add constraint product_stock_movements_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT;
alter table public.product_stock_movements add constraint product_stock_movements_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES marketplace_stock_reservations(id) ON DELETE SET NULL;
alter table public.product_stock_movements add constraint product_stock_movements_stock_after_check CHECK (stock_after >= 0);
alter table public.product_stock_movements add constraint product_stock_movements_stock_before_check CHECK (stock_before >= 0);
alter table public.production_orders add constraint production_orders_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.production_orders add constraint production_orders_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL;
alter table public.production_orders add constraint production_orders_pkey PRIMARY KEY (id);
alter table public.production_orders add constraint production_orders_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES proposals(id) ON DELETE SET NULL;
alter table public.production_orders add constraint production_orders_status_check CHECK (status = ANY (ARRAY['aguardando_sinal'::text, 'aprovado'::text, 'em_producao'::text, 'pronto'::text, 'entregue'::text, 'cancelado'::text]));
alter table public.production_steps add constraint production_steps_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id);
alter table public.production_steps add constraint production_steps_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.production_steps add constraint production_steps_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES auth.users(id);
alter table public.production_steps add constraint production_steps_pkey PRIMARY KEY (id);
alter table public.production_steps add constraint production_steps_production_order_id_fkey FOREIGN KEY (production_order_id) REFERENCES production_orders(id) ON DELETE CASCADE;
alter table public.production_steps add constraint production_steps_status_check CHECK (status = ANY (ARRAY['pendente'::text, 'em_andamento'::text, 'concluido'::text, 'pulada'::text]));
alter table public.products add constraint products_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);
alter table public.products add constraint products_pkey PRIMARY KEY (id);
alter table public.proposal_events add constraint proposal_events_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.proposal_events add constraint proposal_events_pkey PRIMARY KEY (id);
alter table public.proposal_events add constraint proposal_events_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES proposals(id) ON DELETE CASCADE;
alter table public.proposals add constraint proposals_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.proposals add constraint proposals_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL;
alter table public.proposals add constraint proposals_pkey PRIMARY KEY (id);
alter table public.proposals add constraint proposals_status_check CHECK (status = ANY (ARRAY['rascunho'::text, 'enviado'::text, 'visto'::text, 'aprovado'::text, 'alteracao_solicitada'::text, 'recusado'::text, 'expirado'::text, 'cancelado'::text, 'pago_sinal'::text, 'convertido'::text]));
alter table public.proposals add constraint proposals_token_key UNIQUE (token);
alter table public.provider_customers add constraint provider_customers_company_id_provider_customer_id_key UNIQUE (company_id, provider, customer_id);
alter table public.provider_customers add constraint provider_customers_pkey PRIMARY KEY (id);
alter table public.quote_templates add constraint quote_templates_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.quote_templates add constraint quote_templates_pkey PRIMARY KEY (id);
alter table public.recurring_orders add constraint recurring_orders_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.recurring_orders add constraint recurring_orders_original_order_id_fkey FOREIGN KEY (original_order_id) REFERENCES orders(id) ON DELETE SET NULL;
alter table public.recurring_orders add constraint recurring_orders_pkey PRIMARY KEY (id);
alter table public.security_blocklist add constraint security_blocklist_pkey PRIMARY KEY (id);
alter table public.security_blocklist add constraint security_blocklist_type_check CHECK (type = ANY (ARRAY['ip'::text, 'email'::text, 'domain'::text, 'slug'::text, 'subdomain'::text, 'keyword'::text]));
alter table public.security_events add constraint security_events_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.security_events add constraint security_events_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.security_events add constraint security_events_pkey PRIMARY KEY (id);
alter table public.security_events add constraint security_events_severity_check CHECK (severity = ANY (ARRAY['baixa'::text, 'media'::text, 'alta'::text, 'critica'::text]));
alter table public.signup_lead_followups add constraint signup_lead_followups_created_by_admin_id_fkey FOREIGN KEY (created_by_admin_id) REFERENCES platform_admins(id) ON DELETE SET NULL;
alter table public.signup_lead_followups add constraint signup_lead_followups_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES signup_leads(id) ON DELETE CASCADE;
alter table public.signup_lead_followups add constraint signup_lead_followups_pkey PRIMARY KEY (id);
alter table public.signup_lead_followups add constraint signup_lead_followups_sales_event_type_check CHECK (sales_event_type = ANY (ARRAY['legacy'::text, 'contact'::text, 'note'::text, 'stage_change'::text, 'system'::text]));
alter table public.signup_leads add constraint signup_leads_affiliate_referral_id_fkey FOREIGN KEY (affiliate_referral_id) REFERENCES affiliate_referrals(id) ON DELETE SET NULL;
alter table public.signup_leads add constraint signup_leads_assigned_to_admin_id_fkey FOREIGN KEY (assigned_to_admin_id) REFERENCES platform_admins(id) ON DELETE SET NULL;
alter table public.signup_leads add constraint signup_leads_created_by_admin_id_fkey FOREIGN KEY (created_by_admin_id) REFERENCES platform_admins(id) ON DELETE SET NULL;
alter table public.signup_leads add constraint signup_leads_pkey PRIMARY KEY (id);
alter table public.signup_leads add constraint signup_leads_sales_lost_reason_check CHECK (sales_stage <> 'perdido'::text OR NULLIF(btrim(sales_lost_reason), ''::text) IS NOT NULL);
alter table public.signup_leads add constraint signup_leads_sales_stage_check CHECK (sales_stage = ANY (ARRAY['novo'::text, 'contatado'::text, 'interessado'::text, 'demonstracao'::text, 'convite_fundador'::text, 'conta_ativada'::text, 'cliente'::text, 'perdido'::text]));
alter table public.site_sections add constraint site_sections_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.site_sections add constraint site_sections_pkey PRIMARY KEY (id);
alter table public.site_template_presets add constraint site_template_presets_pkey PRIMARY KEY (id);
alter table public.smart_notification_events add constraint smart_notification_events_company_id_event_key_key UNIQUE (company_id, event_key);
alter table public.smart_notification_events add constraint smart_notification_events_pkey PRIMARY KEY (id);
alter table public.smart_notification_settings add constraint smart_notification_settings_pkey PRIMARY KEY (company_id);
alter table public.subscription_events add constraint subscription_events_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.subscription_events add constraint subscription_events_pkey PRIMARY KEY (id);
alter table public.system_audit_logs add constraint system_audit_logs_pkey PRIMARY KEY (id);
alter table public.whatsapp_conversations add constraint whatsapp_conversations_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.whatsapp_conversations add constraint whatsapp_conversations_company_id_phone_key UNIQUE (company_id, phone);
alter table public.whatsapp_conversations add constraint whatsapp_conversations_pkey PRIMARY KEY (id);
alter table public.whatsapp_message_logs add constraint whatsapp_message_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.whatsapp_message_logs add constraint whatsapp_message_logs_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL;
alter table public.whatsapp_message_logs add constraint whatsapp_message_logs_pkey PRIMARY KEY (id);
alter table public.whatsapp_message_logs add constraint whatsapp_message_logs_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES proposals(id) ON DELETE SET NULL;
CREATE INDEX idx_admin_audit_logs_admin_email ON public.admin_audit_logs USING btree (lower(admin_email), created_at DESC);
CREATE INDEX idx_admin_audit_logs_created ON public.admin_audit_logs USING btree (created_at DESC);
CREATE INDEX idx_admin_bug_reports_area_status ON public.admin_bug_reports USING btree (area, status, severity);
CREATE UNIQUE INDEX idx_admin_bug_reports_code_unique ON public.admin_bug_reports USING btree (code);
CREATE INDEX idx_admin_bug_reports_entity ON public.admin_bug_reports USING btree (entity_type, entity_id);
CREATE INDEX idx_admin_bug_reports_last_seen ON public.admin_bug_reports USING btree (last_seen_at DESC);
CREATE INDEX idx_admin_bug_reports_severity ON public.admin_bug_reports USING btree (severity);
CREATE INDEX idx_admin_bug_reports_status ON public.admin_bug_reports USING btree (status);
CREATE INDEX idx_admin_bug_reports_status_severity ON public.admin_bug_reports USING btree (status, severity);
CREATE INDEX idx_admin_scan_runs_started ON public.admin_scan_runs USING btree (started_at DESC);
CREATE INDEX idx_admin_snapshots_created ON public.admin_system_snapshots USING btree (created_at DESC);
CREATE INDEX affiliate_activity_events_kind_idx ON public.affiliate_activity_events USING btree (affiliate_id, kind, created_at DESC);
CREATE INDEX affiliate_activity_events_lead_idx ON public.affiliate_activity_events USING btree (lead_id) WHERE (lead_id IS NOT NULL);
CREATE INDEX affiliate_activity_events_period_idx ON public.affiliate_activity_events USING btree (affiliate_id, created_at DESC);
CREATE INDEX affiliate_audit_logs_affiliate_idx ON public.affiliate_audit_logs USING btree (affiliate_id, created_at DESC);
CREATE INDEX idx_affiliate_audit_logs_actor_user_id ON public.affiliate_audit_logs USING btree (actor_user_id);
CREATE INDEX affiliate_clicks_affiliate_created_idx ON public.affiliate_clicks USING btree (affiliate_id, created_at DESC);
CREATE INDEX affiliate_clicks_session_idx ON public.affiliate_clicks USING btree (session_hash, created_at DESC);
CREATE INDEX affiliate_commissions_affiliate_status_idx ON public.affiliate_commissions USING btree (affiliate_id, status, hold_until);
CREATE INDEX affiliate_commissions_company_idx ON public.affiliate_commissions USING btree (company_id, created_at DESC);
CREATE INDEX idx_affiliate_commissions_payout_id ON public.affiliate_commissions USING btree (payout_id);
CREATE INDEX idx_affiliate_commissions_plan_payment_id ON public.affiliate_commissions USING btree (plan_payment_id);
CREATE INDEX affiliate_course_progress_affiliate_idx ON public.affiliate_course_progress USING btree (affiliate_id, completed_at DESC);
CREATE INDEX affiliate_leads_affiliate_status_idx ON public.affiliate_leads USING btree (affiliate_id, status);
CREATE INDEX affiliate_leads_follow_up_idx ON public.affiliate_leads USING btree (affiliate_id, next_follow_up_at) WHERE (next_follow_up_at IS NOT NULL);
CREATE INDEX affiliate_payouts_affiliate_created_idx ON public.affiliate_payouts USING btree (affiliate_id, created_at DESC);
CREATE UNIQUE INDEX affiliate_payouts_provider_transfer_uidx ON public.affiliate_payouts USING btree (provider_transfer_id) WHERE (provider_transfer_id IS NOT NULL);
CREATE INDEX affiliate_payouts_status_idx ON public.affiliate_payouts USING btree (status, created_at DESC);
CREATE UNIQUE INDEX affiliate_profiles_code_uidx ON public.affiliate_profiles USING btree (upper(code));
CREATE UNIQUE INDEX affiliate_profiles_document_uidx ON public.affiliate_profiles USING btree (document_hash);
CREATE UNIQUE INDEX affiliate_profiles_email_uidx ON public.affiliate_profiles USING btree (lower(email));
CREATE INDEX affiliate_profiles_status_idx ON public.affiliate_profiles USING btree (status, created_at DESC);
CREATE INDEX affiliate_referrals_affiliate_created_idx ON public.affiliate_referrals USING btree (affiliate_id, created_at DESC);
CREATE INDEX affiliate_referrals_company_idx ON public.affiliate_referrals USING btree (company_id);
CREATE INDEX affiliate_referrals_review_idx ON public.affiliate_referrals USING btree (review_status, status, created_at DESC);
CREATE INDEX affiliate_referrals_status_idx ON public.affiliate_referrals USING btree (status, created_at DESC);
CREATE INDEX affiliate_tasks_due_idx ON public.affiliate_tasks USING btree (affiliate_id, completed_at, due_at);
CREATE INDEX affiliate_tasks_lead_idx ON public.affiliate_tasks USING btree (lead_id) WHERE (lead_id IS NOT NULL);
CREATE INDEX affiliate_training_sessions_idx ON public.affiliate_training_sessions USING btree (affiliate_id, completed_at DESC);
CREATE INDEX idx_app_notifications_company_id ON public.app_notifications USING btree (company_id);
CREATE INDEX idx_app_notifications_created ON public.app_notifications USING btree (company_id, created_at DESC);
CREATE INDEX idx_app_notifications_status ON public.app_notifications USING btree (company_id, status);
CREATE INDEX art_approval_requests_active_token_idx ON public.art_approval_requests USING btree (token, expires_at) WHERE (revoked_at IS NULL);
CREATE INDEX idx_art_approval_requests_order_id ON public.art_approval_requests USING btree (order_id);
CREATE INDEX idx_art_approval_requests_proposal_id ON public.art_approval_requests USING btree (proposal_id);
CREATE INDEX idx_art_approvals_company_status ON public.art_approval_requests USING btree (company_id, status, created_at DESC);
CREATE INDEX idx_art_approvals_token ON public.art_approval_requests USING btree (token);
CREATE INDEX business_hours_company_idx ON public.business_hours USING btree (company_id);
CREATE INDEX idx_business_hours_company_weekday ON public.business_hours USING btree (company_id, weekday);
CREATE INDEX companies_business_type_idx ON public.companies USING btree (business_type);
CREATE UNIQUE INDEX companies_founder_number_uq ON public.companies USING btree (founder_number) WHERE ((is_founder = true) AND (founder_number IS NOT NULL));
CREATE INDEX companies_subdomain_slug_idx ON public.companies USING btree (subdomain_slug);
CREATE UNIQUE INDEX companies_subdomain_slug_unique ON public.companies USING btree (lower(subdomain_slug)) WHERE (subdomain_slug IS NOT NULL);
CREATE INDEX idx_companies_access_until ON public.companies USING btree (access_until);
CREATE INDEX idx_companies_assinatura_status ON public.companies USING btree (assinatura_status, assinatura_expira_em);
CREATE INDEX idx_companies_mp_subscription ON public.companies USING btree (mercado_pago_subscription_id);
CREATE INDEX idx_companies_owner_id ON public.companies USING btree (owner_id);
CREATE INDEX idx_companies_slug ON public.companies USING btree (slug);
CREATE INDEX idx_companies_slug_subdomain ON public.companies USING btree (slug, subdomain_slug);
CREATE INDEX idx_companies_subscription_payment_mode ON public.companies USING btree (assinatura_forma_pagamento_preferida);
CREATE INDEX idx_companies_subscription_status ON public.companies USING btree (assinatura_status);
CREATE INDEX idx_companies_tester_id ON public.companies USING btree (tester_id);
CREATE INDEX idx_companies_trial_used_at ON public.companies USING btree (trial_used_at);
CREATE UNIQUE INDEX company_members_company_email_unique ON public.company_members USING btree (company_id, lower(email)) WHERE (status <> 'removido'::text);
CREATE UNIQUE INDEX company_members_company_user_unique ON public.company_members USING btree (company_id, user_id) WHERE (status <> 'removido'::text);
CREATE UNIQUE INDEX idx_company_members_company_email_unique ON public.company_members USING btree (company_id, lower(email));
CREATE INDEX idx_company_members_company_status ON public.company_members USING btree (company_id, status);
CREATE UNIQUE INDEX idx_company_members_company_user_unique ON public.company_members USING btree (company_id, user_id);
CREATE INDEX idx_company_members_created_by ON public.company_members USING btree (created_by);
CREATE INDEX idx_company_members_email_company ON public.company_members USING btree (lower(email), company_id);
CREATE INDEX idx_company_members_user_status ON public.company_members USING btree (user_id, status);
CREATE INDEX idx_company_niche_templates_company ON public.company_niche_templates USING btree (company_id);
CREATE INDEX idx_whatsapp_settings_phone_number ON public.company_whatsapp_settings USING btree (phone_number_id);
CREATE INDEX idx_crm_leads_company_id ON public.crm_leads USING btree (company_id);
CREATE INDEX idx_crm_leads_etapa ON public.crm_leads USING btree (company_id, etapa);
CREATE INDEX idx_crm_leads_next_contact ON public.crm_leads USING btree (company_id, proximo_contato_em);
CREATE INDEX idx_customer_followups_company_phone ON public.customer_followups USING btree (company_id, cliente_telefone, status, due_at);
CREATE INDEX idx_customer_followups_created_by ON public.customer_followups USING btree (created_by);
CREATE INDEX idx_customer_internal_notes_company_id ON public.customer_internal_notes USING btree (company_id);
CREATE INDEX idx_customer_magic_links_company_phone ON public.customer_magic_links USING btree (company_id, customer_phone);
CREATE INDEX idx_customer_magic_links_token ON public.customer_magic_links USING btree (token);
CREATE INDEX idx_customer_notes_company_phone ON public.customer_notes USING btree (company_id, cliente_telefone, created_at DESC);
CREATE INDEX idx_customer_notes_created_by ON public.customer_notes USING btree (created_by);
CREATE INDEX idx_customer_portal_events_company_id ON public.customer_portal_events USING btree (company_id);
CREATE INDEX idx_customer_portal_events_magic_link_id ON public.customer_portal_events USING btree (customer_magic_link_id);
CREATE INDEX deliveries_company_driver_idx ON public.deliveries USING btree (company_id, assigned_driver_id, status);
CREATE INDEX idx_deliveries_assigned_driver_id ON public.deliveries USING btree (assigned_driver_id);
CREATE INDEX idx_deliveries_company_created_at ON public.deliveries USING btree (company_id, created_at DESC);
CREATE INDEX idx_deliveries_company_id ON public.deliveries USING btree (company_id);
CREATE INDEX idx_deliveries_company_status ON public.deliveries USING btree (company_id, status);
CREATE INDEX idx_deliveries_delivery_zone_id ON public.deliveries USING btree (delivery_zone_id);
CREATE INDEX idx_deliveries_order_id ON public.deliveries USING btree (order_id);
CREATE INDEX idx_deliveries_payment_method_id ON public.deliveries USING btree (payment_method_id);
CREATE INDEX delivery_assignments_company_assigned_idx ON public.delivery_assignments USING btree (company_id, assigned_at DESC);
CREATE INDEX delivery_assignments_delivery_idx ON public.delivery_assignments USING btree (delivery_id, assigned_at DESC);
CREATE INDEX delivery_assignments_driver_idx ON public.delivery_assignments USING btree (company_id, driver_id, assigned_at DESC);
CREATE INDEX delivery_assignments_settlement_idx ON public.delivery_assignments USING btree (company_id, settlement_status, assigned_at DESC);
CREATE INDEX idx_delivery_assignments_created_by ON public.delivery_assignments USING btree (created_by);
CREATE INDEX idx_delivery_assignments_driver_id_fk ON public.delivery_assignments USING btree (driver_id);
CREATE INDEX idx_delivery_assignments_order_id_fk ON public.delivery_assignments USING btree (order_id);
CREATE INDEX delivery_drivers_company_active_idx ON public.delivery_drivers USING btree (company_id, is_active, name);
CREATE UNIQUE INDEX delivery_drivers_company_plate_uidx ON public.delivery_drivers USING btree (company_id, upper(TRIM(BOTH FROM vehicle_plate))) WHERE ((vehicle_plate IS NOT NULL) AND (TRIM(BOTH FROM vehicle_plate) <> ''::text));
CREATE INDEX delivery_zones_company_idx ON public.delivery_zones USING btree (company_id);
CREATE INDEX idx_delivery_zones_company_active ON public.delivery_zones USING btree (company_id, is_active);
CREATE INDEX idx_finance_accounts_company ON public.finance_accounts USING btree (company_id, ativo);
CREATE INDEX idx_finance_accounts_company_id ON public.finance_accounts USING btree (company_id);
CREATE INDEX idx_financial_categories_company_id ON public.financial_categories USING btree (company_id);
CREATE INDEX idx_financial_material_company ON public.financial_material_entries USING btree (company_id, created_at DESC);
CREATE INDEX idx_financial_material_entries_company_id ON public.financial_material_entries USING btree (company_id);
CREATE INDEX idx_financial_material_entries_transaction_id ON public.financial_material_entries USING btree (transaction_id);
CREATE INDEX idx_financial_transactions_account_id ON public.financial_transactions USING btree (account_id);
CREATE INDEX idx_financial_transactions_category_id ON public.financial_transactions USING btree (category_id);
CREATE INDEX idx_financial_transactions_company_date ON public.financial_transactions USING btree (company_id, data_competencia DESC);
CREATE INDEX idx_financial_transactions_company_id ON public.financial_transactions USING btree (company_id);
CREATE INDEX idx_financial_transactions_company_type ON public.financial_transactions USING btree (company_id, tipo, status);
CREATE INDEX idx_financial_transactions_created_by ON public.financial_transactions USING btree (created_by);
CREATE INDEX idx_financial_transactions_status ON public.financial_transactions USING btree (company_id, status);
CREATE INDEX idx_financial_transactions_vencimento ON public.financial_transactions USING btree (company_id, vencimento);
CREATE UNIQUE INDEX founder_invites_activated_company_uq ON public.founder_invites USING btree (company_id) WHERE ((status = 'activated'::text) AND (company_id IS NOT NULL));
CREATE UNIQUE INDEX founder_invites_activated_user_uq ON public.founder_invites USING btree (user_id) WHERE ((status = 'activated'::text) AND (user_id IS NOT NULL));
CREATE INDEX founder_invites_activation_claim_idx ON public.founder_invites USING btree (activation_claim_id) WHERE (status = 'activating'::text);
CREATE INDEX founder_invites_created_by_idx ON public.founder_invites USING btree (created_by_admin_id, invited_at DESC);
CREATE INDEX founder_invites_expiry_idx ON public.founder_invites USING btree (token_expires_at) WHERE ((status = 'pending'::text) AND (token_expires_at IS NOT NULL));
CREATE UNIQUE INDEX founder_invites_live_email_uq ON public.founder_invites USING btree (email_normalized) WHERE (status = ANY (ARRAY['pending'::text, 'activating'::text, 'activated'::text]));
CREATE UNIQUE INDEX founder_invites_live_number_uq ON public.founder_invites USING btree (founder_number) WHERE (status = ANY (ARRAY['pending'::text, 'activating'::text, 'activated'::text]));
CREATE UNIQUE INDEX founder_invites_live_sales_lead_uq ON public.founder_invites USING btree (sales_lead_id) WHERE ((sales_lead_id IS NOT NULL) AND (status = ANY (ARRAY['pending'::text, 'activating'::text, 'activated'::text])));
CREATE INDEX founder_invites_revoked_by_admin_idx ON public.founder_invites USING btree (revoked_by_admin_id, revoked_at DESC) WHERE (revoked_by_admin_id IS NOT NULL);
CREATE INDEX founder_invites_sales_lead_idx ON public.founder_invites USING btree (sales_lead_id, invited_at DESC) WHERE (sales_lead_id IS NOT NULL);
CREATE INDEX founder_invites_status_idx ON public.founder_invites USING btree (status, invited_at DESC);
CREATE UNIQUE INDEX founder_invites_token_hash_uq ON public.founder_invites USING btree (token_hash);
CREATE INDEX idx_internal_tasks_company_id ON public.internal_tasks USING btree (company_id);
CREATE INDEX idx_internal_tasks_due ON public.internal_tasks USING btree (company_id, due_at);
CREATE INDEX idx_internal_tasks_status ON public.internal_tasks USING btree (company_id, status);
CREATE INDEX idx_marketplace_commission_rules_company ON public.marketplace_commission_rules USING btree (company_id);
CREATE INDEX idx_marketplace_commission_rules_plan ON public.marketplace_commission_rules USING btree (plan_key);
CREATE INDEX idx_marketplace_commissions_company ON public.marketplace_commissions USING btree (company_id);
CREATE INDEX idx_marketplace_commissions_order_id ON public.marketplace_commissions USING btree (order_id);
CREATE INDEX idx_marketplace_commissions_payment ON public.marketplace_commissions USING btree (marketplace_payment_id);
CREATE INDEX idx_marketplace_coupons_active ON public.marketplace_coupons USING btree (company_id, ativo);
CREATE UNIQUE INDEX idx_marketplace_coupons_company_code ON public.marketplace_coupons USING btree (company_id, codigo_normalizado);
CREATE INDEX idx_marketplace_coupons_company_id ON public.marketplace_coupons USING btree (company_id);
CREATE INDEX idx_marketplace_oauth_states_company_id ON public.marketplace_oauth_states USING btree (company_id);
CREATE INDEX idx_marketplace_oauth_states_hash ON public.marketplace_oauth_states USING btree (state_hash);
CREATE INDEX idx_marketplace_oauth_states_user_id ON public.marketplace_oauth_states USING btree (user_id);
CREATE INDEX idx_marketplace_payment_settings_company ON public.marketplace_payment_settings USING btree (company_id);
CREATE INDEX marketplace_payment_settings_active_idx ON public.marketplace_payment_settings USING btree (company_id, is_active, provider);
CREATE UNIQUE INDEX marketplace_payment_settings_company_provider_uidx ON public.marketplace_payment_settings USING btree (company_id, provider) WHERE ((company_id IS NOT NULL) AND (provider IS NOT NULL));
CREATE INDEX idx_marketplace_payments_company ON public.marketplace_payments USING btree (company_id);
CREATE INDEX idx_marketplace_payments_provider_payment ON public.marketplace_payments USING btree (provider_payment_id);
CREATE INDEX marketplace_payments_company_created_idx ON public.marketplace_payments USING btree (company_id, created_at DESC);
CREATE UNIQUE INDEX marketplace_payments_company_idempotency_uidx ON public.marketplace_payments USING btree (company_id, idempotency_key) WHERE ((company_id IS NOT NULL) AND (idempotency_key IS NOT NULL));
CREATE INDEX marketplace_payments_order_idx ON public.marketplace_payments USING btree (order_id);
CREATE UNIQUE INDEX marketplace_payments_provider_payment_uidx ON public.marketplace_payments USING btree (provider, provider_payment_id) WHERE ((provider IS NOT NULL) AND (provider_payment_id IS NOT NULL));
CREATE INDEX marketplace_stock_reservations_active_product_idx ON public.marketplace_stock_reservations USING btree (company_id, product_id, expires_at) WHERE (status = 'reserved'::text);
CREATE INDEX marketplace_stock_reservations_expiry_idx ON public.marketplace_stock_reservations USING btree (expires_at) WHERE (status = 'reserved'::text);
CREATE INDEX marketplace_stock_reservations_order_idx ON public.marketplace_stock_reservations USING btree (order_id);
CREATE INDEX marketplace_stock_reservations_payment_idx ON public.marketplace_stock_reservations USING btree (company_id, marketplace_payment_id);
CREATE INDEX marketplace_stock_reservations_product_idx ON public.marketplace_stock_reservations USING btree (product_id);
CREATE INDEX idx_notifications_company_created ON public.notifications USING btree (company_id, created_at DESC);
CREATE INDEX idx_notifications_user_read_created ON public.notifications USING btree (user_id, read_at, created_at DESC);
CREATE INDEX idx_order_internal_comments_company_id ON public.order_internal_comments USING btree (company_id);
CREATE INDEX idx_order_internal_comments_created_at ON public.order_internal_comments USING btree (order_id, created_at DESC);
CREATE INDEX idx_order_internal_comments_order_id ON public.order_internal_comments USING btree (order_id);
CREATE INDEX idx_order_items_company_id ON public.order_items USING btree (company_id);
CREATE INDEX idx_order_items_company_order ON public.order_items USING btree (company_id, order_id);
CREATE INDEX idx_order_items_order ON public.order_items USING btree (order_id);
CREATE INDEX idx_order_items_product_id ON public.order_items USING btree (product_id);
CREATE INDEX idx_order_items_respostas ON public.order_items USING gin (respostas);
CREATE INDEX idx_order_payments_company_id ON public.order_payments USING btree (company_id);
CREATE INDEX idx_order_payments_company_order ON public.order_payments USING btree (company_id, order_id);
CREATE INDEX idx_order_payments_company_status ON public.order_payments USING btree (company_id, status);
CREATE INDEX idx_order_payments_order_id ON public.order_payments USING btree (order_id);
CREATE INDEX idx_order_payments_payment_method_id ON public.order_payments USING btree (payment_method_id);
CREATE UNIQUE INDEX order_payments_company_idempotency_uidx ON public.order_payments USING btree (company_id, idempotency_key) WHERE ((company_id IS NOT NULL) AND (idempotency_key IS NOT NULL));
CREATE UNIQUE INDEX order_payments_provider_payment_uidx ON public.order_payments USING btree (provider, provider_payment_id) WHERE ((provider IS NOT NULL) AND (provider_payment_id IS NOT NULL));
CREATE INDEX idx_order_status_history_company_id ON public.order_status_history USING btree (company_id);
CREATE INDEX idx_order_status_history_created_at ON public.order_status_history USING btree (order_id, created_at DESC);
CREATE INDEX idx_order_status_history_order_id ON public.order_status_history USING btree (order_id);
CREATE INDEX idx_orders_cliente_empresa ON public.orders USING btree (cliente_empresa);
CREATE INDEX idx_orders_company_created ON public.orders USING btree (company_id, created_at DESC);
CREATE INDEX idx_orders_company_delivery_type ON public.orders USING btree (company_id, delivery_type);
CREATE INDEX idx_orders_company_id ON public.orders USING btree (company_id);
CREATE INDEX idx_orders_company_payment_status ON public.orders USING btree (company_id, payment_status);
CREATE INDEX idx_orders_company_status_created ON public.orders USING btree (company_id, status, created_at DESC);
CREATE INDEX idx_orders_created_at ON public.orders USING btree (created_at);
CREATE INDEX idx_orders_dados_inteligentes ON public.orders USING gin (dados_inteligentes);
CREATE INDEX idx_orders_delivery_zone_id ON public.orders USING btree (delivery_zone_id);
CREATE INDEX idx_orders_marketplace_payment_id ON public.orders USING btree (marketplace_payment_id);
CREATE INDEX idx_orders_original_order_id ON public.orders USING btree (original_order_id);
CREATE INDEX idx_orders_payment_method_id ON public.orders USING btree (payment_method_id);
CREATE INDEX idx_orders_status ON public.orders USING btree (status);
CREATE INDEX idx_orders_telefone ON public.orders USING btree (telefone);
CREATE UNIQUE INDEX orders_checkout_idempotency_uidx ON public.orders USING btree (company_id, checkout_idempotency_key) WHERE ((company_id IS NOT NULL) AND (checkout_idempotency_key IS NOT NULL));
CREATE INDEX idx_payment_methods_company_active ON public.payment_methods USING btree (company_id, is_active);
CREATE INDEX idx_payment_methods_company_id ON public.payment_methods USING btree (company_id);
CREATE INDEX payment_payouts_company_idx ON public.payment_payouts USING btree (company_id, created_at DESC);
CREATE UNIQUE INDEX payment_payouts_marketplace_payment_id_uidx ON public.payment_payouts USING btree (marketplace_payment_id);
CREATE INDEX payment_payouts_provider_id_idx ON public.payment_payouts USING btree (provider, provider_payout_id);
CREATE INDEX payment_webhook_events_company_idx ON public.payment_webhook_events USING btree (company_id, received_at DESC);
CREATE INDEX payment_webhook_events_object_idx ON public.payment_webhook_events USING btree (provider, provider_object_id);
CREATE INDEX idx_plan_payments_company_id ON public.plan_payments USING btree (company_id);
CREATE INDEX idx_plan_payments_company_status ON public.plan_payments USING btree (company_id, status);
CREATE INDEX idx_plan_payments_payment_id ON public.plan_payments USING btree (mercado_pago_payment_id);
CREATE INDEX idx_plan_payments_preapproval ON public.plan_payments USING btree (mercado_pago_preapproval_id);
CREATE INDEX idx_plan_payments_preference_id ON public.plan_payments USING btree (mercado_pago_preference_id);
CREATE INDEX plan_payments_company_created_idx ON public.plan_payments USING btree (company_id, created_at DESC);
CREATE UNIQUE INDEX plan_payments_company_idempotency_uidx ON public.plan_payments USING btree (company_id, idempotency_key) WHERE ((company_id IS NOT NULL) AND (idempotency_key IS NOT NULL));
CREATE INDEX plan_payments_provider_payment_idx ON public.plan_payments USING btree (provider, provider_payment_id) WHERE (provider_payment_id IS NOT NULL);
CREATE UNIQUE INDEX plan_payments_provider_payment_uidx ON public.plan_payments USING btree (provider, provider_payment_id) WHERE ((provider IS NOT NULL) AND (provider_payment_id IS NOT NULL));
CREATE INDEX plan_payments_provider_subscription_idx ON public.plan_payments USING btree (provider, provider_subscription_id) WHERE (provider_subscription_id IS NOT NULL);
CREATE UNIQUE INDEX plan_payments_provider_subscription_uidx ON public.plan_payments USING btree (provider, provider_subscription_id) WHERE ((provider IS NOT NULL) AND (provider_subscription_id IS NOT NULL));
CREATE UNIQUE INDEX platform_admin_invites_activated_admin_uq ON public.platform_admin_invites USING btree (platform_admin_id) WHERE ((status = 'activated'::text) AND (platform_admin_id IS NOT NULL));
CREATE UNIQUE INDEX platform_admin_invites_activated_user_uq ON public.platform_admin_invites USING btree (user_id) WHERE ((status = 'activated'::text) AND (user_id IS NOT NULL));
CREATE INDEX platform_admin_invites_created_by_idx ON public.platform_admin_invites USING btree (created_by_admin_id, created_at DESC);
CREATE UNIQUE INDEX platform_admin_invites_live_email_uq ON public.platform_admin_invites USING btree (email_normalized) WHERE (status = ANY (ARRAY['pending'::text, 'activating'::text]));
CREATE INDEX platform_admin_invites_status_expires_idx ON public.platform_admin_invites USING btree (status, expires_at);
CREATE UNIQUE INDEX platform_admin_invites_token_hash_uq ON public.platform_admin_invites USING btree (token_hash);
CREATE INDEX idx_platform_admins_email ON public.platform_admins USING btree (lower(email));
CREATE INDEX idx_platform_admins_user ON public.platform_admins USING btree (user_id);
CREATE INDEX platform_admins_role_active_idx ON public.platform_admins USING btree (role, is_active, created_at DESC);
CREATE UNIQUE INDEX platform_admins_single_active_owner_uidx ON public.platform_admins USING btree ((1)) WHERE ((is_active = true) AND (lower(role) = 'owner'::text));
CREATE INDEX product_stock_movements_order_fk_idx ON public.product_stock_movements USING btree (order_id);
CREATE INDEX product_stock_movements_order_idx ON public.product_stock_movements USING btree (company_id, order_id) WHERE (order_id IS NOT NULL);
CREATE INDEX product_stock_movements_payment_idx ON public.product_stock_movements USING btree (marketplace_payment_id);
CREATE INDEX product_stock_movements_product_created_idx ON public.product_stock_movements USING btree (company_id, product_id, created_at DESC);
CREATE INDEX product_stock_movements_product_idx ON public.product_stock_movements USING btree (product_id);
CREATE INDEX product_stock_movements_reservation_idx ON public.product_stock_movements USING btree (reservation_id);
CREATE INDEX idx_production_orders_company_status ON public.production_orders USING btree (company_id, status, due_date);
CREATE INDEX idx_production_orders_company_status_created ON public.production_orders USING btree (company_id, status, created_at DESC);
CREATE INDEX idx_production_orders_order_id ON public.production_orders USING btree (order_id);
CREATE UNIQUE INDEX idx_production_orders_proposal_unique ON public.production_orders USING btree (proposal_id) WHERE (proposal_id IS NOT NULL);
CREATE INDEX idx_production_steps_assigned_to ON public.production_steps USING btree (assigned_to);
CREATE INDEX idx_production_steps_company_id ON public.production_steps USING btree (company_id);
CREATE INDEX idx_production_steps_completed_by ON public.production_steps USING btree (completed_by);
CREATE INDEX idx_production_steps_order_sort ON public.production_steps USING btree (production_order_id, sort_order);
CREATE INDEX idx_products_categoria ON public.products USING btree (categoria);
CREATE INDEX idx_products_company_active_category ON public.products USING btree (company_id, ativo, categoria);
CREATE INDEX idx_products_company_active_created ON public.products USING btree (company_id, ativo, created_at DESC);
CREATE INDEX idx_products_company_ativo ON public.products USING btree (company_id, ativo);
CREATE INDEX idx_products_company_ativo_arquivado ON public.products USING btree (company_id, ativo, arquivado);
CREATE INDEX idx_products_company_categoria ON public.products USING btree (company_id, categoria);
CREATE INDEX idx_products_company_destaque ON public.products USING btree (company_id, destaque);
CREATE INDEX idx_products_company_id ON public.products USING btree (company_id);
CREATE INDEX idx_products_company_margin ON public.products USING btree (company_id, ativo, margem_desejada);
CREATE INDEX idx_products_company_oculto ON public.products USING btree (company_id, oculto);
CREATE INDEX idx_products_created_at ON public.products USING btree (created_at);
CREATE INDEX idx_products_marketplace_company ON public.products USING btree (company_id, ativo, destaque);
CREATE INDEX products_company_business_type_idx ON public.products USING btree (company_id, business_type);
CREATE INDEX idx_proposal_events_company_created ON public.proposal_events USING btree (company_id, created_at DESC);
CREATE INDEX idx_proposal_events_proposal_created ON public.proposal_events USING btree (proposal_id, created_at DESC);
CREATE INDEX idx_proposals_company_id ON public.proposals USING btree (company_id);
CREATE INDEX idx_proposals_company_status_created ON public.proposals USING btree (company_id, status, created_at DESC);
CREATE INDEX idx_proposals_order ON public.proposals USING btree (order_id);
CREATE INDEX idx_proposals_token ON public.proposals USING btree (token);
CREATE INDEX provider_customers_provider_id_idx ON public.provider_customers USING btree (provider, provider_customer_id);
CREATE UNIQUE INDEX idx_quote_templates_company_nome ON public.quote_templates USING btree (company_id, nome);
CREATE UNIQUE INDEX idx_quote_templates_company_tipo_unique ON public.quote_templates USING btree (company_id, tipo);
CREATE INDEX idx_recurring_orders_company_next ON public.recurring_orders USING btree (company_id, next_due_at);
CREATE INDEX idx_recurring_orders_original_order_id ON public.recurring_orders USING btree (original_order_id);
CREATE UNIQUE INDEX idx_security_blocklist_type_value ON public.security_blocklist USING btree (type, lower(value));
CREATE INDEX idx_security_events_actor_user_id ON public.security_events USING btree (actor_user_id);
CREATE INDEX idx_security_events_company_created ON public.security_events USING btree (company_id, created_at DESC);
CREATE INDEX idx_security_events_created ON public.security_events USING btree (created_at DESC);
CREATE INDEX idx_security_events_path ON public.security_events USING btree (path);
CREATE INDEX idx_security_events_type_severity ON public.security_events USING btree (event_type, severity, resolved);
CREATE INDEX idx_signup_lead_followups_lead ON public.signup_lead_followups USING btree (lead_id, created_at DESC);
CREATE INDEX idx_signup_lead_followups_sales_admin ON public.signup_lead_followups USING btree (created_by_admin_id, created_at DESC) WHERE (created_by_admin_id IS NOT NULL);
CREATE INDEX idx_signup_leads_affiliate_referral_id ON public.signup_leads USING btree (affiliate_referral_id);
CREATE INDEX idx_signup_leads_email ON public.signup_leads USING btree (lower(email));
CREATE INDEX idx_signup_leads_sales_assignee_stage ON public.signup_leads USING btree (assigned_to_admin_id, sales_stage, updated_at DESC);
CREATE INDEX idx_signup_leads_sales_creator ON public.signup_leads USING btree (created_by_admin_id, created_at DESC);
CREATE INDEX idx_signup_leads_sales_next_action ON public.signup_leads USING btree (sales_next_action_at) WHERE ((sales_next_action_at IS NOT NULL) AND (sales_stage <> ALL (ARRAY['cliente'::text, 'perdido'::text])));
CREATE INDEX idx_signup_leads_sales_stage ON public.signup_leads USING btree (sales_stage, updated_at DESC);
CREATE INDEX idx_signup_leads_status_next_followup ON public.signup_leads USING btree (status, next_followup_at);
CREATE INDEX idx_signup_leads_whatsapp ON public.signup_leads USING btree (whatsapp);
CREATE INDEX signup_leads_referral_code_idx ON public.signup_leads USING btree (referral_code);
CREATE INDEX idx_site_sections_company_order ON public.site_sections USING btree (company_id, active, sort_order);
CREATE INDEX idx_smart_notification_events_company_id ON public.smart_notification_events USING btree (company_id);
CREATE INDEX idx_smart_notification_events_type ON public.smart_notification_events USING btree (company_id, event_type);
CREATE INDEX idx_subscription_events_company_created ON public.subscription_events USING btree (company_id, created_at DESC);
CREATE UNIQUE INDEX subscription_events_provider_event_uidx ON public.subscription_events USING btree (provider, provider_event_id) WHERE ((provider IS NOT NULL) AND (provider_event_id IS NOT NULL));
CREATE UNIQUE INDEX ux_subscription_events_idempotency ON public.subscription_events USING btree (company_id, event_type, provider_reference);
CREATE INDEX idx_system_audit_logs_company_id ON public.system_audit_logs USING btree (company_id);
CREATE INDEX idx_system_audit_logs_created ON public.system_audit_logs USING btree (company_id, created_at DESC);
CREATE INDEX idx_whatsapp_conversations_company_updated ON public.whatsapp_conversations USING btree (company_id, updated_at DESC);
CREATE INDEX idx_whatsapp_logs_company_created ON public.whatsapp_message_logs USING btree (company_id, created_at DESC);
CREATE INDEX idx_whatsapp_logs_order ON public.whatsapp_message_logs USING btree (order_id, created_at DESC);
CREATE INDEX idx_whatsapp_logs_proposal ON public.whatsapp_message_logs USING btree (proposal_id, created_at DESC);
