import Link from 'next/link'
import {getPersonalProductAccess} from '@/lib/ecosystem/server'
import {planningToday} from '@/lib/wealth/planning-server'
import {timelineQuery,timelinePageHref,timelineSources,timelineOperations,type WealthTimeline} from '@/lib/wealth/timeline'
import styles from '@/components/wealth/calendar.module.css'
export default async function TimelinePage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const access=await getPersonalProductAccess('wealth','wealth.read')
 if(!access.allowed||!access.identity)return <><h1>Timeline do Wealth</h1><p>O acesso ao Wealth não está liberado.</p><Link href="/apps">Voltar ao Hub</Link></>
 const {db,user}=access.identity,today=await planningToday(db,user.id)
 let query:ReturnType<typeof timelineQuery>
 try{query=timelineQuery(await searchParams,today)}catch(error){return <><h1>Revise o período</h1><p>{error instanceof Error?error.message:'Filtro inválido.'}</p><Link href="/apps/wealth/timeline">Voltar à Timeline</Link></>}
 const result=await db.rpc('wealth_timeline',{p_from:query.from,p_to:query.to,p_page:query.page,p_source:query.source,p_operation:query.operation,p_as_of:query.asOf})
 if(result.error){if(result.error.code==='22023')return <><h1>Filtro indisponível</h1><Link href="/apps/wealth/timeline">Atualizar Timeline</Link></>;throw Error('Não foi possível consultar a Timeline.')}
 const timeline=result.data as WealthTimeline,pages=(BigInt(timeline.total)+BigInt(49))/BigInt(50),pageCount=pages>BigInt(0)?pages.toString():'1',formatter=new Intl.DateTimeFormat('pt-BR',{timeZone:timeline.timezone,dateStyle:'medium',timeStyle:'short'})
 return <div className={styles.page}><nav className={styles.nav} aria-label="Histórico Wealth"><Link href="/apps/wealth">Visão geral</Link><Link href="/apps/wealth/timeline" aria-current="page">Timeline</Link><Link href="/apps/wealth/calendario">Calendário</Link></nav>
 <header className={styles.hero}><div><span className={styles.kicker}>Sua trajetória, com contexto</span><h1>Timeline do Wealth</h1><p>Reveja o que você registrou e encontre a decisão ou o documento relacionado.</p></div><aside>Horários em {timeline.timezone}. Esta é a data do registro no Wealth; não comprova pagamento ou recebimento bancário.</aside></header>
 <form className={styles.filters}><label>Desde<input name="from" type="date" required defaultValue={query.from} min="1900-01-01" max="2200-12-31"/></label><label>Até<input name="to" type="date" required defaultValue={query.to} min="1900-01-01" max="2200-12-31"/></label><label>Origem<select name="source" defaultValue={query.source??''}><option value="">Todas as origens</option>{Object.entries(timelineSources).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label>Atividade<select name="operation" defaultValue={query.operation??''}><option value="">Todas as atividades</option>{Object.entries(timelineOperations).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><button className={styles.button}>Consultar histórico</button><Link href="/apps/wealth/timeline">Atualizar últimos 90 dias</Link></form>
 <p className={styles.notice}>A Timeline mostra atividades atribuídas à sua conta na auditoria existente. Rotinas sem autor identificado e períodos anteriores a essa auditoria não estão cobertos. Títulos e links refletem o contexto atual; valores anteriores não são reconstruídos. Metas concluídas são declarações suas.</p>
 <section className={styles.section}><h2>Atividades registradas</h2><p>{timeline.total} atividade(s) · página {query.page} de {pageCount} · até 50 por página. Consulta até {formatter.format(new Date(timeline.asOf))}.</p>
 {timeline.items.length?<ol className={styles.agenda}>{timeline.items.map(event=><li key={event.id} id={`event-${event.id}`} data-event-id={event.id} className={styles.bill}><div className={styles.billHeader}><div><p><time dateTime={event.recorded_at}>{formatter.format(new Date(event.recorded_at))}</time> · {timelineSources[event.source]}</p><h3>{timelineOperations[event.operation]}</h3></div><span className={styles.tag}>{event.contextState==='hypothetical'?'Contexto de simulação':event.contextState==='snapshot'?'Captura declarada':event.contextState==='archived'?'Registro arquivado':event.contextState==='removed'?'Documento removido':event.contextState==='unavailable'?'Contexto indisponível':'Atividade registrada'}</span></div><p>{event.title}</p>{event.href&&<Link href={event.href}>Abrir registro relacionado</Link>}<a href={`${timelinePageHref(query,timeline.asOf,query.page)}#event-${event.id}`}>Referência desta atividade</a></li>)}</ol>:<p className={styles.empty}>Nenhuma atividade registrada neste período e filtro. Amplie o período ou consulte outra origem.</p>}
 <nav className={styles.nav} aria-label="Paginação da Timeline">{query.page>1&&<Link href={timelinePageHref(query,timeline.asOf,query.page-1)}>Página anterior</Link>}{BigInt(query.page)<pages&&query.page<100000&&<Link href={timelinePageHref(query,timeline.asOf,query.page+1)}>Próxima página</Link>}</nav></section>
 <section className={styles.section}><h2>O próximo passo</h2><p>Use o Calendário para datas financeiras e compromissos. Para valores preservados de um momento anterior, consulte os snapshots explícitos de patrimônio.</p><nav className={styles.nav} aria-label="Contexto da Timeline"><Link href="/apps/wealth/calendario">Ver calendário financeiro</Link><Link href="/apps/wealth/patrimonio">Ver patrimônio e snapshots</Link></nav></section></div>
}
