import {formatMoney,formatFinancialDate} from './core'
import {readWealthSummary,type WealthSummary} from './summary'
import {readNetWorth,type NetWorth} from './net-worth'

export type HealthInputs={positions:NetWorth;summary:WealthSummary;debts:{openCount:string;detailedCount:string;minimum:string;balance:string};recurring:{activeCount:string;nextPendingTotal:string;overdueCount:string;next30Count:string;next30Amount:string};snapshots:NetWorth[]}
export type HealthIndicator={id:string;title:string;value:string;source:string;period:string;rule:string;interpretation:string;limitation:string}
const object=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v)
export function readHealthInputs(value:unknown):HealthInputs{
 if(!object(value)||!object(value.debts)||!object(value.recurring)||!Array.isArray(value.snapshots)||value.snapshots.length>2)throw Error('Indicadores indisponíveis')
 for(const [row,keys] of [[value.debts,['openCount','detailedCount','minimum','balance']],[value.recurring,['activeCount','nextPendingTotal','overdueCount','next30Count','next30Amount']]] as const){for(const key of keys)if(typeof row[key]!=='string'||!/^\d{1,60}$/.test(row[key] as string))throw Error('Total inválido')}
 return {positions:readNetWorth(value.positions),summary:readWealthSummary(value.summary),debts:value.debts as HealthInputs['debts'],recurring:value.recurring as HealthInputs['recurring'],snapshots:value.snapshots.map(readNetWorth)}
}
/** Signed ratios, half up to two decimals; absent denominator never becomes zero. */
export function healthRatio(n:bigint,d:bigint,multiplier=1){
 if(d<=BigInt(0))return null
 const abs=n<BigInt(0)?-n:n,scaled=(abs*BigInt(multiplier)*BigInt(100)+d/BigInt(2))/d
 return `${n<BigInt(0)&&scaled!==BigInt(0)?'-':''}${scaled/BigInt(100)},${String(scaled%BigInt(100)).padStart(2,'0')}`
}
export function healthIndicators(input:HealthInputs):HealthIndicator[]{
 const {positions:p,summary:s,debts:d,recurring:r,snapshots}=input
 const immediate=BigInt(p.liquidity.find(row=>row.liquidity==='immediate')?.amount??'0'),income=BigInt(s.income),flow=BigInt(s.cashFlow)
 const prior=s.months.slice(8,11),expenses=prior.reduce((sum,m)=>sum+BigInt(m.expenses),BigInt(0)),observed=prior.filter(m=>BigInt(m.expenses)>BigInt(0)).length
 const months=healthRatio(immediate*BigInt(3),expenses),burden=healthRatio(BigInt(d.minimum),income,100),savings=healthRatio(flow,income,100),liquid=healthRatio(immediate,BigInt(p.liabilities),100)
 const goal=healthRatio(BigInt(s.goalSaved),BigInt(s.goalTarget),100),largest=p.largest.find(row=>row.kind==='asset'),concentration=healthRatio(BigInt(largest?.amount??'0'),BigInt(p.assets),100)
 const current=`${s.month} (mês em andamento; fuso ${p.timezone})`,now=`Posição consultada em ${formatFinancialDate(p.localDate)} · ${p.timezone}`
 const unavailable='Não calculável com os registros atuais'
 const trend=snapshots.length===2?BigInt(snapshots[0].netWorth)-BigInt(snapshots[1].netWorth):null
 return [
  {id:'reserve',title:'Cobertura de reserva',value:months===null?unavailable:`${months} meses`,source:'Ativos de liquidez imediata e despesas registradas.',period:`Três meses completos: ${prior[0].month} a ${prior[2].month}. Ativos atuais.`,rule:'Ativos imediatos ÷ (despesas dos três meses ÷ 3). Denominador zero impede cálculo.',interpretation:'Quantos meses da despesa média registrada caberiam nos ativos imediatos declarados.',limitation:`Proxy de reserva: não confirma que os ativos estejam livres ou reservados para emergências. ${observed} de 3 meses têm despesas; meses sem registros entram como zero e podem superestimar a cobertura.`},
  {id:'burden',title:'Comprometimento com dívidas',value:burden===null?unavailable:`${BigInt(d.detailedCount)<BigInt(d.openCount)?'Parcial: ':''}${burden}%`,source:'Mínimos mensais do Debt Center e receitas registradas.',period:current,rule:'Soma dos mínimos de dívidas abertas detalhadas ÷ receita do mês × 100.',interpretation:'Parcela da receita registrada que seria necessária para os mínimos declarados, não pagamentos comprovados.',limitation:`${d.detailedCount} de ${d.openCount} passivos abertos têm termos. Sem termos, a dívida não contribui com mínimo. Receita parcial ou incompleta distorce a relação.`},
  {id:'savings',title:'Taxa de poupança registrada',value:savings===null?unavailable:`${savings}%`,source:'Receitas menos despesas registradas no mês.',period:current,rule:'(Receitas − despesas) ÷ receitas × 100. Receitas zero impedem cálculo.',interpretation:'Superávit em relação à receita; valor negativo indica despesas registradas acima da receita.',limitation:'Não comprova aporte ou investimento. Transferências, registros ausentes e mês parcial podem distorcer a leitura.'},
  {id:'surplus',title:'Superávit mensal registrado',value:formatMoney(s.cashFlow),source:'Todos os lançamentos ativos de receita e despesa.',period:current,rule:'Receitas − despesas, em centavos exatos.',interpretation:flow<BigInt(0)?'As despesas registradas superam as receitas.':flow===BigInt(0)?'Os registros têm saldo de fluxo zero.':'As receitas registradas superam as despesas.',limitation:'É fluxo registrado, não saldo bancário. Ausência de registros não comprova equilíbrio financeiro.'},
  {id:'liquidity',title:'Cobertura de liquidez',value:liquid===null?'Sem passivos com saldo para comparar':`${liquid}%`,source:'Ativos imediatos e todos os saldos de passivos.',period:now,rule:'Ativos com liquidez imediata ÷ passivos totais × 100.',interpretation:'Quanto dos passivos declarados seria coberto pelos ativos classificados como imediatos.',limitation:'Não considera vencimentos, custos de resgate, impostos ou disponibilidade verificada. Liquidez desconhecida não é considerada imediata.'},
  {id:'trend',title:'Variação do patrimônio',value:trend===null?'Registre dois snapshots para comparar':formatMoney(trend),source:'Dois snapshots explícitos mais recentes.',period:snapshots.length===2?`${snapshots[1].capturedAt} → ${snapshots[0].capturedAt} (instantes com offset)`:'Histórico ainda insuficiente.',rule:'Patrimônio do snapshot mais recente − patrimônio do anterior.',interpretation:'Diferença absoluta entre duas declarações preservadas; não compara com um passado reconstruído.',limitation:'Não é rentabilidade. Cadastro, arquivamento, reclassificação de espécie e atualização de saldo podem explicar a variação; intervalo pode ser muito curto.'},
  {id:'goals',title:'Cobertura das metas',value:goal===null?'Sem objetivo monetário para comparar':`${goal}%`,source:'Todas as metas não arquivadas, incluindo pausadas e concluídas.',period:now,rule:'Soma do reservado limitado ao objetivo de cada meta ÷ soma dos objetivos × 100.',interpretation:`${formatMoney(s.goalSaved)} declarados como reservados para ${formatMoney(s.goalTarget)} em objetivos.`,limitation:'Reservas são declarações e podem apontar para os mesmos ativos; não soma metas ao patrimônio nem comprova segregação do dinheiro.'},
  {id:'concentration',title:'Concentração na maior posição',value:concentration===null?'Sem ativos para comparar':`${concentration}%`,source:'Maior registro de ativo e total integral de ativos.',period:now,rule:'Maior posição ÷ ativos totais × 100.',interpretation:largest?`${largest.title} é o maior registro por valor declarado.`:'Nenhuma posição de ativo declarada.',limitation:'Não consolida exposições por emissor, grupo, moeda ou risco. Dividir um ativo em vários registros altera este indicador.'},
  {id:'recurring',title:'Obrigações recorrentes pendentes',value:formatMoney(r.nextPendingTotal),source:'Próxima ocorrência de cada agendamento ativo de despesa.',period:`Próximas pendências consultadas em ${p.capturedAt}.`,rule:'Soma uma próxima ocorrência por agendamento ativo, inclusive atrasados; exclui receitas, pausados e cancelados.',interpretation:`${r.activeCount} agendamentos; ${r.overdueCount} atrasados. ${r.next30Count} próximas ocorrências nos próximos 30 dias somam ${formatMoney(r.next30Amount)}.`,limitation:'Não é total mensal nem soma todas as repetições futuras. Uma regra diária entra uma vez. Agendamento declara registros; não executa nem comprova pagamentos.'},
 ]
}
